// PROJ5_1128.c
// Generated by decompiling PROJ5.EXE
// using Reko decompiler version 0.12.2.0.

#include "PROJ5.h"

struct seg1128_t * g_ptr11280 = &g_tFFFFB198; // 00011280
// 1128:000E: void main(Register (ptr16 Eq_5868) ds)
void main(struct Eq_5868 * ds)
{
	Eq_12 ds_268;
	struct Eq_6169 Eq_6090::* bp_265;
	Eq_716 bx_266;
	Eq_716 dx_269;
	Eq_716 cx_267;
	Eq_12 ds_232;
	word16 di_231;
	Eq_12 ds_92;
	ds->w2960 = 0x00;
	ds->w2962 = 0x00;
	ds->w2964 = 0x00;
	ds->w2966 = 0x00;
	ds->w29D2 = 0x00;
	ds->w29D4 = 0x0F;
	ds->w29D6 = 0x0A;
	ds->w297A = 0x00;
	ds->w2978 = 0x00;
	ds->dw297C = 0x00;
	ds->dw2980 = 0x00;
	ds->dw2984 = 0x00;
	ds->w29DC = 0x00;
	ds->w296E = 0x00;
	ds->w2970 = 0x00;
	fn0800_1BEC(&ds->dw2984 + 5, (char *) ds + 3783);
	__wait();
	real64 rLoc1_484 = ds->r0ECA;
	__wait();
	ds->r29A2 = rLoc1_484;
	__wait();
	ds->w29AA = 500;
	ds->w29AC = 500;
	ds->w29AE = 500;
	ds->w29B0 = 0x00;
	ds->w29B2 = 0x00;
	ds->w29B4 = 0x00;
	ds->w2972 = 0x00;
	ds->w2974 = 0x00;
	ds->w2976 = 0x00;
	ds->w2A44 = 0x14;
	ds->w2A46 = 0x14;
	ds->w2A48 = 0x3C;
	ds->w29D8 = 0xFF;
	ds->w29B6 = 0x01;
	ds->w29CE = 0x01;
	ds->w29D0 = 0x00;
	ds->w2A4A = 0x01;
	ds->w2A4C = 100;
	ds->w2A4E = 0x01;
	ds->w2A50 = 100;
	ds->w2A52 = 100;
	ds->w2A54 = 100;
	fn1128_4395(ds);
	Eq_12 si_96 = fn1A29_00DA(SEQ(0x01, ds), ds->w29B6, out ds_92);
	fn1A29_04E4(ds_92);
	fn0800_1BEC(SEQ(ds_92, 10718), SEQ(ds_92, 22422));
	Eq_716 cx_142;
	Eq_716 dx_140;
	Eq_716 bx_139;
	segptr32 ptrLoc18_519;
	if (fn1BF1_03F4((word16 *) 0x18010000, out cx_142, out dx_140, out bx_139) < 0x00)
		ptrLoc18_519 = SEQ(ds_92, 0x0ED2);
	else
	{
		<unknown> Eq_6090::* fp;
		struct Eq_5614 * es_173;
		cx_142 = fn1BF1_0979(si_96, 0x01, fp - 0x0A, fp - 6, 0x0EE1, ds_92, out dx_140, out bx_139, out es_173);
		if (fn1BF1_030D() == 0x00)
		{
			if (fn195C_0002(ds_92) == 0x00)
				Mem203[ds_92:0x2960:word16] = 0x01;
			struct Eq_6130 * ds_210 = fn1BC2_003A(es_173, ds_92);
			cup16 si_235 = fn1BC2_0001(ds_210, 0x00, 0x00, 0x0952, ds_210, out di_231, out ds_232);
			Mem260[ds_232:10812:word32] = fn0800_4A9A(ds_232) - 30000;
			uint16 ax_264 = fn0800_475C(ds_232, Mem260[ds_232:10812:word32], out cx_267, out dx_269, out bx_266, out bp_265, out ds_268);
			Mem277[ds_268:10818:word16] = dx_269;
			Mem278[ds_268:0x2A40:word16] = ax_264;
			struct Eq_6182 Eq_6090::* sp_276 = fp - 0x14;
			if ((ax_264 | dx_269) != 0x00)
			{
				Mem292[ds_268:10812:word32] = CONVERT(Mem278[ds_268:10812:word32], uint32, uint64) /u 0x06;
				Eq_12 ds_295 = fn1A29_0326(ds_268);
				while (true)
				{
					struct Eq_6294 Eq_6090::* sp_306 = sp_276 - 2;
					struct Eq_6090 * ss;
					(ss->*sp_306).w0000 = 0x01;
					(ss->*sp_306).wFFFFFFFE = 0x01;
					(ss->*sp_306).tFFFFFFFC.u2 = (byte Eq_4085::*) 0x00;
					fn1BF1_115D((ss->*sp_306).tFFFFFFFC.u2, (ss->*sp_306).wFFFFFFFE, (ss->*sp_306).w0000);
					struct Eq_6216 Eq_6090::* sp_321 = (struct Eq_6216 Eq_6090::*) (&sp_306->w0000 + 1);
					if (di_231 != 0x00)
					{
						(ss->*sp_306).w0000 = si_235;
						Eq_4797 sp_340;
						sp_340.u0 = <invalid>;
						bp_265 = fn1128_43AC(ds_295, (ss->*sp_306).w0000);
						sp_321 = (word16) sp_340 + 2;
					}
					struct Eq_6218 Eq_6090::* sp_351 = sp_321 - 2;
					(ss->*sp_351).w0000 = 0x00;
					(ss->*sp_351).wFFFFFFFE = 0x07;
					(ss->*sp_351).tFFFFFFFC.u2 = (byte Eq_4085::*) ds_295;
					(ss->*sp_351).ptrFFFFFFFA = 0x96;
					(ss->*sp_351).tFFFFFFF8.u2 = (byte Eq_4085::*) ds_295;
					(ss->*sp_351).tFFFFFFF6.u0 = 0xB2;
					(ss->*bp_265).wFFFFFFFE = fn1128_5DC0(ds_295, (ss->*sp_351).tFFFFFFF6.u1, (ss->*sp_351).ptrFFFFFFFA, (ss->*sp_351).wFFFFFFFE, (ss->*sp_351).w0000, out ds_295);
					(ss->*bp_265).wFFFFFFF2 = (ss->*bp_265).wFFFFFFFE;
					si_235 = 0x01;
					di_231 = 0x01;
					sp_276 = (struct Eq_6182 Eq_6090::*) (&sp_351->w0000 + 1);
					word16 cx_384;
					struct Eq_6292 seg1128_t::* bx_385 = (struct Eq_6292 seg1128_t::*) seg1128_t::a0416;
					for (cx_384 = 0x08; cx_384 != 0x00; --cx_384)
					{
						if ((0x1128->*bx_385).w0000 == (ss->*bp_265).wFFFFFFF2)
						{
							bx_385[8]();
							return;
						}
						++bx_385;
					}
				}
			}
			else
			{
				fn0800_302B(cx_267, dx_269, bx_266, ds_268, SEQ(ds_268, 0x0EF1));
				fn1BF1_0E3E();
				__out<byte>(0x031C, 0x00);
				return;
			}
		}
		ptrLoc18_519 = SEQ(ds_92, 0x0EE2);
	}
	fn0800_302B(cx_142, dx_140, bx_139, ds_92, ptrLoc18_519);
}

word16 g_a0416[] = // 1128:0416
	{
	};
Eq_13884 g_a0426[] = // 1128:0426
	{
	};
// 1128:0436: void fn1128_0436(Stack Eq_6243 ptrArg04, Stack int16 wArg08, Stack Eq_12 dwArg0A)
// Called from:
//      fn1128_4FC9
//      fn1128_5DC0
void fn1128_0436(Eq_6243 ptrArg04, int16 wArg08, Eq_12 dwArg0A)
{
	fn1BF1_1211(0x01, 0x3F);
	Eq_12 ax_37;
	ax_37.u2 = (&&(SLICE(ptrArg04, selector, 16)->*((SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04).t0000).u0))[wArg08 *s 0x06 + 0x03].t0000.u2;
	Eq_12 ax_54;
	ax_54.u2 = (&&(SLICE(ptrArg04, selector, 16)->*((SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04).t0000).u0))[wArg08 *s 0x06 + 2].t0000.u2;
	fn1BF1_1C32(ax_54, ax_37, (char *) &ax_54.u1->t0000.u0 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 4], (char *) &ax_37.u1->t0000.u0 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 5]);
	fn1BF1_1211(0x01, 0x00);
	word16 ax_98 = (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x03];
	word16 ax_118 = (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x02];
	fn1BF1_1C32(ax_118 + 0x01, ax_98 + 0x01, ax_118 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x04] + 0x01, ax_98 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x05] + 0x01);
	fn1BF1_1211(0x01, 0x07);
	word16 ax_167 = (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x03];
	word16 ax_186 = (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x02];
	fn1BF1_1C32(ax_186 + 0x01, ax_167 + 0x01, ax_186 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x04], ax_167 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x05]);
	fn1BF1_1D5C(0x00);
	fn1BF1_1F2A((&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x02] + 0x04, (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x03] + 0x04, dwArg0A);
}

// 1128:05BB: void fn1128_05BB(Stack Eq_6243 ptrArg04, Stack int16 wArg08, Stack Eq_12 dwArg0A)
// Called from:
//      fn1128_5DC0
void fn1128_05BB(Eq_6243 ptrArg04, int16 wArg08, Eq_12 dwArg0A)
{
	fn1BF1_1211(0x01, 0x00);
	Eq_12 ax_37;
	ax_37.u2 = (&&(SLICE(ptrArg04, selector, 16)->*((SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04).t0000).u0))[wArg08 *s 0x06 + 0x03].t0000.u2;
	Eq_12 ax_54;
	ax_54.u2 = (&&(SLICE(ptrArg04, selector, 16)->*((SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04).t0000).u0))[wArg08 *s 0x06 + 2].t0000.u2;
	fn1BF1_1C32(ax_54, ax_37, (char *) &ax_54.u1->t0000.u0 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 4], (char *) &ax_37.u1->t0000.u0 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 5]);
	fn1BF1_1211(0x01, 0x07);
	word16 ax_98 = (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x03];
	word16 ax_118 = (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x02];
	fn1BF1_1C32(ax_118 + 0x01, ax_98 + 0x01, ax_118 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x04] + 0x01, ax_98 + (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x05] + 0x01);
	fn1BF1_1D5C(0x00);
	fn1BF1_1F2A((&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x02] + 0x05, (&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[wArg08 *s 0x06 + 0x03] + 0x05, dwArg0A);
}

// 1128:06D5: void fn1128_06D5(Stack Eq_12 wArg04, Stack Eq_12 wArg06, Stack byte bArg08, Stack Eq_12 dwArg0A)
// Called from:
//      fn1128_43AC
//      fn1128_4FC9
void fn1128_06D5(Eq_12 wArg04, Eq_12 wArg06, byte bArg08, Eq_12 dwArg0A)
{
	word16 wArg08;
	fn1BF1_1D5C((byte) wArg08);
	fn1BF1_119E(wArg04, wArg06, &wArg04.u1->b000A, &wArg06.u1->b000A);
	fn1BF1_1F2A((word32) wArg04 + 0x0F, &wArg06.u1->t0002.ptr0000, dwArg0A);
}

// 1128:0715: Register word16 fn1128_0715(Register Eq_12 ds, Stack Eq_6243 ptrArg04, Stack int16 wArg08)
// Called from:
//      fn1128_5DC0
word16 fn1128_0715(Eq_12 ds, Eq_6243 ptrArg04, int16 wArg08)
{
	if (SLICE(ptrArg04, selector, 16):SLICE(ptrArg04, word16, 0)[(wArg08 *s 0x06 + 0x02) * 0x02] >= Mem7[ds:0x5806:word16] || (SLICE(ptrArg04, selector, 16):SLICE(ptrArg04, word16, 0)[(wArg08 *s 0x06 + 0x02) * 0x02] + SLICE(ptrArg04, selector, 16):SLICE(ptrArg04, word16, 0)[(wArg08 *s 0x06 + 0x04) * 0x02] <= Mem25[ds:0x5806:word16] || (SLICE(ptrArg04, selector, 16):SLICE(ptrArg04, word16, 0)[(wArg08 *s 0x06 + 0x03) * 0x02] >= Mem25[ds:0x5808:word16] || SLICE(ptrArg04, selector, 16):SLICE(ptrArg04, word16, 0)[(wArg08 *s 0x06 + 0x03) * 0x02] + SLICE(ptrArg04, selector, 16):SLICE(ptrArg04, word16, 0)[(wArg08 *s 0x06 + 0x05) * 0x02] <= Mem56[ds:0x5808:word16])))
		return 0x00;
	return 0x01;
}

// 1128:07AB: Register Eq_12 fn1128_07AB(Register Eq_12 ds, Stack Eq_12 dwArg04, Stack word16 wArg08, Stack cup16 wArg0A)
// Called from:
//      fn1A29_000C
//      fn1A29_0326
Eq_12 fn1128_07AB(Eq_12 ds, Eq_12 dwArg04, word16 wArg08, cup16 wArg0A)
{
	Eq_12 ds_185;
	fn1BF1_2066(0xB4, 0x0122, 0x0181, 0x0159, SEQ(ds, 10838));
	fn1BF1_1211(0x01, 0x00);
	fn1BF1_1C32(0xB8, 0x0126, 0x0180, 344);
	fn1BF1_1211(0x01, 0x3C);
	fn1BF1_1C32(0xB4, 0x0122, 0x017C, 0x0154);
	fn1BF1_1D5C(0x00);
	fn1BF1_1F2A(0xBE, 0x0129, dwArg04);
	if (wArg08 != 0x00)
		fn1BF1_1F2A(0xBE, 0x0145, SEQ(ds, 0x0F51));
	fn1128_4FC9(SEQ(ds, 0x07BE), SEQ(ds, 0x07B2), wArg08 + 2);
	word16 ax_182 = fn1128_5DC0(ds, SEQ(ds, 0x07BE), SEQ(ds, 0x07B2), wArg08 + 2, wArg0A, out ds_185);
	fn1BF1_1526(0xB4, 0x0122, SEQ(ds_185, 10838), 0x00);
	if (ax_182 == 0x00)
		return ds_185;
	if (ax_182 == 0x01)
		return ds_185;
	if (ax_182 == 0x02)
		return ds_185;
	if (Mem206[ds_185:10714:word16] != 0x0D)
		return ds_185;
	return ds_185;
}

// 1128:4395: void fn1128_4395(Register (ptr16 Eq_5868) ds)
// Called from:
//      main
void fn1128_4395(struct Eq_5868 * ds)
{
	int16 ax_13;
	for (ax_13 = 0x00; ax_13 < 0x0A; ++ax_13)
		ds->a29BA[0][ax_13] = 0x00;
}

// 1128:43AC: Register word16 fn1128_43AC(Register Eq_12 ds, Stack cup16 wArg04)
// Called from:
//      main
word16 fn1128_43AC(Eq_12 ds, cup16 wArg04)
{
	mp16 fp;
	struct Eq_6921 Eq_12::* bp_1112 = fp - 2;
	Eq_12 ax_22;
	if (wArg04 != 0x00)
		ax_22.u0 = 0x00;
	else
		ax_22.u0 = 0x90;
	Eq_12 ax_37;
	if (wArg04 != 0x00)
		ax_37.u0 = 0x027F;
	else
		ax_37.u0 = 464;
	ci16 ax_49;
	if (wArg04 == 0x00)
		ax_49 = 0x01;
	else
		ax_49 = 0x00;
	ci16 si_104;
	for (si_104 = ax_49; si_104 < 0x14; ++si_104)
	{
		fn1BF1_125E(SEQ(ds, (si_104 << 0x03) + 0x0992), 0x01);
		fn1BF1_1C32(ax_22, si_104 << 0x04, ax_37, si_104 + 1 << 0x04);
	}
	ci16 si_106;
	for (si_106 = 0x00; si_106 < 0x0A; ++si_106)
	{
		fn1BF1_125E(SEQ(ds, (0x13 - si_106 << 0x03) + 0x0992), 0x01);
		fn1BF1_1C32(ax_22, si_106 + 20 << 0x04, ax_37, si_106 + 21 << 0x04);
	}
	fn1BF1_1D5C(0x01);
	fn1BF1_1F2A(0xAA, 0x0136, SEQ(ds, 4804));
	fn1BF1_1F2A(0xE6, 0x0140, SEQ(ds, 0x12E5));
	struct Eq_7004 Eq_12::* sp_1022 = fp - 44;
	Eq_12 ss;
	if (wArg04 != 0x00)
	{
		fn1BF1_1211(0x01, 0x01);
		int16 si_221;
		for (si_221 = 0x00; si_221 < 0x07; ++si_221)
		{
			int16 bx_227 = si_221 *s 0x06;
			Eq_7120 bx_232 = bx_227 * 0x02 + 0xB8;
			fn1BF1_1C32((*((word32) ds + 0x00B6))[bx_227] + ~0x01, (word16) (ds->*bx_232) + 0x0000FFFE, (*((word32) ds + 0x00B6))[bx_227] + 0x5D, (word16) (ds->*bx_232) + 21);
		}
		fn1128_4A4A(ds);
		fn1128_4FC9(SEQ(ds, 0xB2), SEQ(ds, 0x96), 0x07);
		fn1128_60AE(ds, fp - 40, ss);
		fn1BF1_1D5C(0x09);
		fn1BF1_1F2A(0x0244, 55, SEQ(ds, 0x90));
		fn1BF1_1D5C(0x3B);
		if (Mem338[ds:10716:word16] != 0x00)
			fn1BF1_1F2A(0x14, 0xEB, SEQ(ss, fp - 40));
		fn1128_06D5(0x1E, 0x32, 0x3B, SEQ(ds, 0x12F5));
		fn1128_06D5(0x1E, 0x46, 0x3B, SEQ(ds, 4855));
		fn1128_06D5(0x1E, 0x91, 0x3B, SEQ(ds, 0x12F9));
		fn1BF1_1211(0x01, 0x3C);
		if (Mem437[ds:0x29B6:word16] != 0x00)
		{
			fn1BF1_1C32(0x1F, 0x47, 0x27, 0x4F);
			fn1128_4979(0x1E, 0x55, Mem468[ds:10680:word16]);
		}
		else
			fn1BF1_1C32(0x1F, 0x33, 0x27, 0x3B);
		if (Mem496[ds:10702:word16] != 0x00)
			fn1BF1_1C32(0x1F, 0x92, 0x27, 0x9A);
		fn1BF1_1F2A(0x14, 0x1E, SEQ(ds, 4866));
		fn1BF1_1F2A(0x41, 0x1E, SEQ(ds, 0x2A2E));
		fn1BF1_1F2A(0x14, 0xAF, SEQ(ds, 0x1308));
		fn0800_40A5(Mem584[ds:0x2984:word32], SEQ(ss, fp - 40), 0x0A);
		fn1BF1_1F2A(0x41, 0xAF, SEQ(ss, fp - 40));
		fn1BF1_1F2A(0x14, 0xC2, SEQ(ds, 4878));
		fn1BF1_1F2A(0x1E, 0x010E, SEQ(ds, 0x1315));
		fn1BF1_1F2A(0x1E, 0x011D, SEQ(ds, 0x131C));
		__wait();
		__wait();
		__wait();
		struct Eq_6921 Eq_12::* bp_698 = fn0800_04AB(ds);
		Eq_4797 sp_700;
		sp_700.u0 = <invalid>;
		ss->*((word16) sp_700 + 0x0C) = ss;
		ss->*((word16) sp_700 + 0x0A) = bp_698 - 38;
		ss->*((word16) sp_700 + 8) = 0x011D;
		ss->*((word16) sp_700 + 6) = 0x32;
		fn1BF1_1F2A(ss->*((word16) sp_700 + 6), ss->*((word16) sp_700 + 8), ss->*((word16) sp_700 + 0x0A));
		ss->*((word16) sp_700 + 0x0C) = ds;
		ss->*((word16) sp_700 + 0x0A) = 0x131F;
		ss->*((word16) sp_700 + 8) = 300;
		ss->*((word16) sp_700 + 6) = 0x1E;
		fn1BF1_1F2A(ss->*((word16) sp_700 + 6), ss->*((word16) sp_700 + 8), ss->*((word16) sp_700 + 0x0A));
		ss->*((word16) sp_700 + 0x0C) = ss;
		ss->*((word16) sp_700 + 0x0A) = bp_698 - 38;
		ss->*((word16) sp_700 + 8) = 0x04;
		Mem749[ss:bp_698 + -6:word16] = Mem747[ds:10666:word16];
		__wait();
		real64 rLoc1_1275 = (real64) (ss->*bp_698).wFFFFFFFA;
		__wait();
		real64 rLoc1_1276 = rLoc1_1275 / CONVERT(Mem749[ds:0x0FF6:real32], real32, real64);
		__wait();
		(ss->*bp_698).rFFFFFFC8 = rLoc1_1276;
		__wait();
		struct Eq_6921 Eq_12::* bp_758 = fn0800_04AB(ds);
		Eq_4797 sp_760;
		sp_760.u0 = <invalid>;
		ss->*((word16) sp_760 + 0x0C) = ss;
		ss->*((word16) sp_760 + 0x0A) = bp_758 - 38;
		ss->*((word16) sp_760 + 8) = 300;
		ss->*((word16) sp_760 + 6) = 0x32;
		fn1BF1_1F2A(ss->*((word16) sp_760 + 6), ss->*((word16) sp_760 + 8), ss->*((word16) sp_760 + 0x0A));
		ss->*((word16) sp_760 + 0x0C) = ds;
		ss->*((word16) sp_760 + 0x0A) = 0x1322;
		ss->*((word16) sp_760 + 8) = 313;
		ss->*((word16) sp_760 + 6) = 0x1E;
		fn1BF1_1F2A(ss->*((word16) sp_760 + 6), ss->*((word16) sp_760 + 8), ss->*((word16) sp_760 + 0x0A));
		ss->*((word16) sp_760 + 0x0C) = ss;
		ss->*((word16) sp_760 + 0x0A) = bp_758 - 38;
		ss->*((word16) sp_760 + 8) = 0x04;
		Mem809[ss:bp_758 + -6:word16] = Mem807[ds:10668:word16];
		__wait();
		real64 rLoc1_1277 = (real64) (ss->*bp_758).wFFFFFFFA;
		__wait();
		real64 rLoc1_1278 = rLoc1_1277 / CONVERT(Mem809[ds:0x0FF6:real32], real32, real64);
		__wait();
		(ss->*bp_758).rFFFFFFC8 = rLoc1_1278;
		__wait();
		struct Eq_6921 Eq_12::* bp_818 = fn0800_04AB(ds);
		Eq_4797 sp_820;
		sp_820.u0 = <invalid>;
		ss->*((word16) sp_820 + 0x0C) = ss;
		ss->*((word16) sp_820 + 0x0A) = bp_818 - 38;
		ss->*((word16) sp_820 + 8) = 313;
		ss->*((word16) sp_820 + 6) = 0x32;
		fn1BF1_1F2A(ss->*((word16) sp_820 + 6), ss->*((word16) sp_820 + 8), ss->*((word16) sp_820 + 0x0A));
		ss->*((word16) sp_820 + 0x0C) = ds;
		ss->*((word16) sp_820 + 0x0A) = 0x1325;
		ss->*((word16) sp_820 + 8) = 0x0146;
		ss->*((word16) sp_820 + 6) = 0x1E;
		fn1BF1_1F2A(ss->*((word16) sp_820 + 6), ss->*((word16) sp_820 + 8), ss->*((word16) sp_820 + 0x0A));
		ss->*((word16) sp_820 + 0x0C) = ss;
		ss->*((word16) sp_820 + 0x0A) = bp_818 - 38;
		ss->*((word16) sp_820 + 8) = 0x04;
		Mem869[ss:bp_818 + -6:word16] = Mem867[ds:10670:word16];
		__wait();
		real64 rLoc1_1279 = (real64) (ss->*bp_818).wFFFFFFFA;
		__wait();
		real64 rLoc1_1280 = rLoc1_1279 / CONVERT(Mem869[ds:0x0FF6:real32], real32, real64);
		__wait();
		(ss->*bp_818).rFFFFFFC8 = rLoc1_1280;
		__wait();
		bp_1112 = fn0800_04AB(ds);
		Eq_4797 sp_880;
		sp_880.u0 = <invalid>;
		ss->*((word16) sp_880 + 0x0C) = ss;
		ss->*((word16) sp_880 + 0x0A) = bp_1112 - 38;
		ss->*((word16) sp_880 + 8) = 0x0146;
		ss->*((word16) sp_880 + 6) = 0x32;
		fn1BF1_1F2A(ss->*((word16) sp_880 + 6), ss->*((word16) sp_880 + 8), ss->*((word16) sp_880 + 0x0A));
		ss->*((word16) sp_880 + 0x0C) = 344;
		ss->*((word16) sp_880 + 0x0A) = 0x60;
		ss->*((word16) sp_880 + 8) = 0x0104;
		ss->*((word16) sp_880 + 6) = 0x14;
		fn1BF1_119E(ss->*((word16) sp_880 + 6), ss->*((word16) sp_880 + 8), ss->*((word16) sp_880 + 0x0A), ss->*((word16) sp_880 + 0x0C));
		if (Mem910[ds:0x2960:word16] != 0x00)
		{
			ss->*((word16) sp_880 + 0x0C) = 0x3C;
			fn1BF1_1D5C(ss->*((word16) sp_880 + 0x0C));
			ss->*((word16) sp_880 + 0x0C) = ds;
			ss->*((word16) sp_880 + 0x0A) = 4904;
			ss->*((word16) sp_880 + 8) = 0x55;
			ss->*((word16) sp_880 + 6) = 565;
			fn1BF1_1F2A(ss->*((word16) sp_880 + 6), ss->*((word16) sp_880 + 8), ss->*((word16) sp_880 + 0x0A));
		}
		ss->*((word16) sp_880 + 0x0C) = 0x00;
		fn1BF1_1D5C(ss->*((word16) sp_880 + 0x0C));
		ss->*((word16) sp_880 + 0x0C) = 0x3B;
		ss->*((word16) sp_880 + 0x0A) = 0x01;
		fn1BF1_1211(ss->*((word16) sp_880 + 0x0A), ss->*((word16) sp_880 + 0x0C));
		ss->*((word16) sp_880 + 0x0C) = 222;
		ss->*((word16) sp_880 + 0x0A) = 0x56;
		ss->*((word16) sp_880 + 8) = 0xCE;
		ss->*((word16) sp_880 + 6) = 0x1F;
		fn1BF1_1C32(ss->*((word16) sp_880 + 6), ss->*((word16) sp_880 + 8), ss->*((word16) sp_880 + 0x0A), ss->*((word16) sp_880 + 0x0C));
		ss->*((word16) sp_880 + 0x0C) = 0x0A;
		ss->*((word16) sp_880 + 0x0A) = ss;
		ss->*((word16) sp_880 + 8) = bp_1112 - 38;
		Mem992[ss:sp_880 + 0x04:word32] = Mem988[ds:0x2980:word32];
		fn0800_40A5(ss->*((word16) sp_880 + 4), ss->*((word16) sp_880 + 8), ss->*((word16) sp_880 + 0x0C));
		ss->*((word16) sp_880 + 0x0C) = ss;
		ss->*((word16) sp_880 + 0x0A) = bp_1112 - 38;
		ss->*((word16) sp_880 + 8) = 211;
		ss->*((word16) sp_880 + 6) = 0x28;
		fn1BF1_1F2A(ss->*((word16) sp_880 + 6), ss->*((word16) sp_880 + 8), ss->*((word16) sp_880 + 0x0A));
		sp_1022 = (word16) sp_880 + 0x0E;
	}
	struct Eq_7009 Eq_12::* sp_1025 = sp_1022 - 2;
	(ss->*sp_1025).t0000.u2 = (byte Eq_4085::*) 0x3B;
	fn1BF1_1D5C((ss->*sp_1025).t0000.u0);
	(ss->*sp_1025).t0000.u2 = (byte Eq_4085::*) ds;
	(ss->*sp_1025).tFFFFFFFE.u2 = (byte Eq_4085::*) 0x2A2E;
	(ss->*sp_1025).tFFFFFFFC.u2 = (byte Eq_4085::*) 0x1E;
	(ss->*sp_1025).tFFFFFFFA.u2 = (byte Eq_4085::*) 0x41;
	fn1BF1_1F2A((ss->*sp_1025).tFFFFFFFA.u2, (ss->*sp_1025).tFFFFFFFC.u2, (ss->*sp_1025).tFFFFFFFE.u1);
	(ss->*sp_1025).t0000.u2 = (byte Eq_4085::*) ds;
	(ss->*sp_1025).tFFFFFFFE.u2 = (byte Eq_4085::*) 4909;
	(ss->*sp_1025).tFFFFFFFC.u2 = (byte Eq_4085::*) 0x0182;
	(ss->*sp_1025).tFFFFFFFA.u2 = (byte Eq_4085::*) 0x14;
	fn1BF1_1F2A((ss->*sp_1025).tFFFFFFFA.u2, (ss->*sp_1025).tFFFFFFFC.u2, (ss->*sp_1025).tFFFFFFFE.u1);
	(ss->*sp_1025).t0000.u2 = (byte Eq_4085::*) 0x00;
	fn1128_4827(ds, (ss->*sp_1025).t0000.u2);
	if (Mem1072[ds:10616:word16] != 0x00)
	{
		(ss->*sp_1025).t0000.u2 = (byte Eq_4085::*) 0x01;
		Mem1091[ss:sp_1025 + -2:word16] = Mem1088[ds:10618:word16];
		fn1128_4ACF(ds, (ss->*sp_1025).tFFFFFFFE.u2, (ss->*sp_1025).t0000.u2);
	}
	return (ss->*bp_1112).w0000;
}

// 1128:4827: void fn1128_4827(Register Eq_12 ds, Stack Eq_12 wArg04)
// Called from:
//      fn1128_43AC
void fn1128_4827(Eq_12 ds, Eq_12 wArg04)
{
	fn1BF1_1D5C(0x3B);
	fn1BF1_1211(0x01, 0x00);
	<unknown> Eq_7976::* fp;
	if (Mem25[ds:0x29B6:word16] != 0x00)
	{
		ui16 wLoc06_331 = 0x01;
		int16 si_110;
		for (si_110 = 0x00; si_110 < 0x03; ++si_110)
		{
			int16 di_114;
			for (di_114 = 0x00; di_114 < 0x03; ++di_114)
			{
				int16 ax_128 = di_114 *s 0x2A;
				fn1BF1_119E(ax_128 + 0x0A, (si_110 << 0x04) + 404, ax_128 + 0x32, (si_110 << 0x04) + 0x01A2);
				if (wArg04 != 0x00)
				{
					Eq_12 ax_161;
					if ((Mem143[ds:20450:word16] & wLoc06_331) != 0x00)
						ax_161.u0 = 0x3C;
					else
						ax_161.u0 = 0x00;
					fn1BF1_1211(0x01, ax_161);
				}
				int16 ax_196 = di_114 *s 0x2A;
				fn1BF1_1C32(ax_196 + 11, (si_110 << 0x04) + 0x0195, ax_196 + 0x31, (si_110 << 0x04) + 0x01A1);
				if ((Mem211[ds:10680:word16] & wLoc06_331) != 0x00)
				{
					word16 bx_432;
					fn0800_4055((*((word32) ds + 0x000029BA))[si_110 *s 0x03 + di_114].t0000.u0, fp - 0x0C, 0x0A, out bx_432);
					fn1BF1_1F2A(di_114 *s 0x2A + 0x0E, (si_110 << 0x04) + 0x0198, fp - 0x0C);
				}
				wLoc06_331 <<= 0x01;
			}
		}
	}
	else
	{
		fn1BF1_119E(0x14, 404, 0x3C, 0x01A2);
		fn1BF1_1C32(0x15, 0x0195, 0x3B, 0x01A1);
		struct Eq_7976 * ss;
		word16 bx_430;
		fn0800_4055(Mem74[ds:10700:word16], SEQ(ss, fp - 0x0C), 0x0A, out bx_430);
		fn1BF1_1F2A(0x18, 0x0198, fp - 0x0C);
	}
}

// 1128:4979: void fn1128_4979(Stack word16 wArg04, Stack word16 wArg06, Stack cui16 wArg08)
// Called from:
//      fn1128_43AC
void fn1128_4979(word16 wArg04, word16 wArg06, cui16 wArg08)
{
	ui16 wLoc06_181 = 0x01;
	int16 si_164;
	for (si_164 = 0x00; si_164 < 0x03; ++si_164)
	{
		ci16 di_161;
		for (di_161 = 0x00; di_161 < 0x03; ++di_161)
		{
			fn1BF1_119E((di_161 << 0x04) + wArg04, (si_164 << 0x04) + wArg06, (di_161 << 0x04) + wArg04 + 0x0E, (si_164 << 0x04) + wArg06 + 0x0E);
			if ((wArg08 & wLoc06_181) != 0x00)
				fn1BF1_1C32((di_161 << 0x04) + wArg04 + 0x01, (si_164 << 0x04) + wArg06 + 0x01, (di_161 << 0x04) + wArg04 + 0x0D, (si_164 << 0x04) + wArg06 + 0x0D);
			<unknown> Eq_8102::* fp;
			word16 bx_235;
			fn0800_4055(si_164 *s 0x03 + di_161 + 0x01, fp - 4, 0x0A, out bx_235);
			fn1BF1_1F2A((di_161 << 0x04) + wArg04 + 0x04, (si_164 << 0x04) + wArg06 + 0x04, fp - 4);
			wLoc06_181 <<= 0x01;
		}
	}
}

// 1128:4A4A: void fn1128_4A4A(Register Eq_12 ds)
// Called from:
//      fn1128_43AC
void fn1128_4A4A(Eq_12 ds)
{
	word16 wLoc04_118 = 0x00;
	int16 wLoc08_119 = 0x02;
	while (wLoc08_119 > 0x00)
	{
		int16 v10_23 = wLoc08_119 - 0x01;
		wLoc08_119 = v10_23;
		int16 si_106;
		for (si_106 = 0x00; si_106 < 0x22; ++si_106)
		{
			Eq_8205 di_112;
			di_112.u0 = 0x00;
			do
			{
				int16 wLoc0A_122 = 0x80;
				ci16 wLoc06_123 = 0x00;
				ci16 v25_82;
				do
				{
					if ((wLoc0A_122 & (uint16) (ds->*((word16) di_112 + ((word16) (si_106 *s 0x0F) + 0x0A32)))) == 0x00)
						fn1BF1_2046((di_112 << 0x03) + wLoc06_123 + v10_23 *s 0x03 + 500, v10_23 *s 0x03 + (0x32 - si_106), (byte) wLoc04_118);
					v25_82 = wLoc06_123 + 0x01;
					wLoc0A_122 >>= 0x01;
					wLoc06_123 = v25_82;
				} while (v25_82 < 0x08);
				di_112 = (word16) di_112 + 1;
			} while (di_112 < 0x0F);
		}
		wLoc04_118 = 0x09;
	}
}

// 1128:4ACF: void fn1128_4ACF(Register Eq_12 ds, Stack Eq_12 wArg04, Stack Eq_12 wArg06)
// Called from:
//      fn1128_43AC
void fn1128_4ACF(Eq_12 ds, Eq_12 wArg04, Eq_12 wArg06)
{
	fn1BF1_1D5C(0x3B);
	fn1BF1_1F2A(0x96, 0x01C5, SEQ(ds, 0x133B));
	Eq_12 bx_41 = Mem30[ds:10618:word16];
	int16 wLoc10;
	int16 wLoc12;
	if (bx_41 <= 0x03)
	{
		switch (bx_41)
		{
		case 0x00:
			fn1BF1_1F2A(0x96, 400, SEQ(ds, 0x133D));
			fn1BF1_1F2A(202, 0x01C5, SEQ(ds, 0x133F));
			wLoc10 = Mem183[ds:10666:word16];
			wLoc12 = Mem196[ds:10668:word16];
			break;
		case 0x01:
			fn1BF1_1F2A(0x96, 400, SEQ(ds, 0x1341));
			fn1BF1_1F2A(202, 0x01C5, SEQ(ds, 0x1343));
			wLoc10 = Mem141[ds:10668:word16];
			wLoc12 = Mem154[ds:10666:word16];
			break;
		case 0x02:
			fn1BF1_1F2A(202, 0x01C5, SEQ(ds, 4933));
			wLoc10 = Mem75[ds:10666:word16];
			goto l1128_4B97;
		case 0x03:
			fn1BF1_1F2A(202, 0x01C5, SEQ(ds, 0x1347));
			wLoc10 = Mem54[ds:10668:word16];
l1128_4B97:
			wLoc12 = Mem90[ds:10670:word16];
			fn1BF1_1F2A(0x96, 400, SEQ(ds, 0x1349));
			break;
		}
	}
	int16 ax_204;
	if (Mem200[ds:10666:word16] > Mem200[ds:10668:word16])
		ax_204 = Mem200[ds:10666:word16];
	else
		ax_204 = Mem200[ds:10668:word16];
	int16 ax_218;
	if (ax_204 > Mem200[ds:10670:word16])
		ax_218 = 3000 /16 ax_204;
	else
		ax_218 = 3000 /16 Mem200[ds:10670:word16];
	int32 dx_ax_251 = (int32) (wLoc10 *s ax_218);
	int32 dx_ax_241 = (int32) (wLoc12 *s ax_218);
	fn1BF1_119E(0xA0, 0x01C2 - dx_ax_241 /16 0x0A, dx_ax_251 /16 0x0A + 0xA0, 0x01C2);
	if (wArg06 != 0x00)
	{
		fn1BF1_1211(0x01, 0x00);
		fn1BF1_1C32(161, 0x01C2 - dx_ax_241 /16 0x0A + 0x01, dx_ax_251 /16 0x0A + 0x9F, 0x01C1);
		Eq_902 dwLoc06_1108;
		dwLoc06_1108.u0 = 0x00;
		while (true)
		{
			uint16 wLoc04_1111 = SLICE(dwLoc06_1108, word16, 16);
			Eq_902 wLoc06_1112 = (word16) dwLoc06_1108;
			if (dwLoc06_1108 >= Mem621[ds:0x2984:word32])
				break;
			int16 wLoc0C_1124;
			int32 dx_ax_1279;
			if (wArg04 == 0x00)
			{
				int32 dx_ax_965 = fn0800_3EB2(0x06, wLoc04_1111, 0x00, wLoc06_1112) + CONVERT(Mem621[ds:0x2A40:word16], uint16, uint32);
				wLoc0C_1124 = (int32) (ax_218 *s ((SLICE(dx_ax_965, word16, 16) << 0x0C) + Mem621[ds:10818:word16])->*(word16) dx_ax_965) /16 100;
				int32 dx_ax_1278 = fn0800_3EB2(0x03, wLoc04_1111, 0x00, wLoc06_1112);
				word16 ax_852 = (word16) dx_ax_1278;
				dx_ax_1279 = SEQ(__rcl<word16,byte>(SLICE(dx_ax_1278 + 0x01, word16, 16), 0x01, cond((ax_852 + 0x01) * 0x02) & 0x02), (ax_852 + 0x01) * 0x02);
				goto l1128_4CF4;
			}
			int16 wLoc0E_1121;
			if (wArg04 == 0x01)
			{
				int32 dx_ax_1284 = fn0800_3EB2(0x03, wLoc04_1111, 0x00, wLoc06_1112);
				word16 ax_756 = (word16) dx_ax_1284;
				Eq_8728 dx_ax_984 = SEQ(__rcl<word16,byte>(SLICE(dx_ax_1284 + 0x01, word16, 16), 0x01, cond((ax_756 + 0x01) * 0x02) & 0x02), (ax_756 + 0x01) * 0x02) + CONVERT(Mem621[ds:0x2A40:word16], uint16, uint32);
				wLoc0C_1124 = (int32) (ax_218 *s ((SLICE(dx_ax_984, word16, 16) << 0x0C) + Mem621[ds:10818:word16])->*(word16) dx_ax_984) /16 100;
				dx_ax_1279 = fn0800_3EB2(0x06, wLoc04_1111, 0x00, wLoc06_1112);
l1128_4CF4:
				Eq_8549 dx_ax_969 = dx_ax_1279 + CONVERT(Mem872[ds:0x2A40:word16], uint16, uint32);
				wLoc0E_1121 = (int32) (ax_218 *s ((SLICE(dx_ax_969, word16, 16) << 0x0C) + Mem872[ds:10818:word16])->*(word16) dx_ax_969) /16 100;
			}
			else
			{
				int32 dx_ax_1282 = fn0800_3EB2(0x03, wLoc04_1111, 0x00, wLoc06_1112);
				word16 ax_637 = (word16) dx_ax_1282;
				Eq_8610 dx_ax_973 = SEQ(__rcl<word16,byte>(SLICE(dx_ax_1282 + 0x02, word16, 16), 0x01, cond((ax_637 + 0x02) * 0x02) & 0x02), (ax_637 + 0x02) * 0x02) + CONVERT(Mem621[ds:0x2A40:word16], uint16, uint32);
				int16 ax_665 = ((SLICE(dx_ax_973, word16, 16) << 0x0C) + Mem621[ds:10818:word16])->*(word16) dx_ax_973;
				__wait();
				__wait();
				real64 rLoc1_1115 = CONVERT(ax_665, int16, real64) * Mem666[ds:0x29A2:real64];
				__wait();
				__wait();
				__wait();
				__wait();
				__wait();
				wLoc0E_1121 = fn0800_0F76(CONVERT(ax_218, int16, real64) * rLoc1_1115 / CONVERT(Mem674[ds:4211:real32], real32, real64));
				ui32 bx_si_976 = fn0800_3EB2(0x03, wLoc04_1111, 0x00, wLoc06_1112) + (uint32) wArg04;
				ui16 si_719 = (word16) bx_si_976 + ~0x01;
				uint32 bx_si_980 = SEQ(__rcl<word16,byte>(SLICE(bx_si_976 + ~0x01, word16, 16), 0x01, cond(si_719 * 0x02) & 0x02), si_719 * 0x02) + CONVERT(Mem707[ds:0x2A40:word16], uint16, uint32);
				wLoc0C_1124 = (int32) (ax_218 *s ((SLICE(bx_si_980, word16, 16) << 0x0C) + Mem707[ds:10818:word16])->*(word16) bx_si_980) /16 100;
			}
			word16 ax_906;
			if (dwLoc06_1108 < Mem901[ds:0x2980:word32])
				ax_906 = 0x3C;
			else
				ax_906 = 0x3B;
			fn1128_4F92(wLoc0C_1124, dx_ax_251 /16 0x0A, wLoc0E_1121, dx_ax_241 /16 0x0A, (byte) ax_906);
			dwLoc06_1108 = (word32) dwLoc06_1108.u0 + 1;
		}
		return;
	}
	int16 wLoc0C_1083;
	int32 dx_ax_1274;
	int16 ax_401;
	if (wArg04 == 0x00)
	{
		int32 dx_ax_959 = fn0800_3EB2(0x06, Mem273[ds:0x2982:word16], 0x00, Mem273[ds:0x2980:word16]) + CONVERT(Mem273[ds:0x2A40:word16], uint16, uint32);
		wLoc0C_1083 = (int32) (ax_218 *s ((SLICE(dx_ax_959, word16, 16) << 0x0C) + Mem273[ds:10818:word16])->*(word16) dx_ax_959) /16 100;
		int32 dx_ax_1273 = fn0800_3EB2(0x03, Mem503[ds:0x2982:word16], 0x00, Mem503[ds:0x2980:word16]);
		word16 ax_511 = (word16) dx_ax_1273;
		dx_ax_1274 = SEQ(__rcl<word16,byte>(SLICE(dx_ax_1273 + 0x01, word16, 16), 0x01, cond((ax_511 + 0x01) * 0x02) & 0x02), (ax_511 + 0x01) * 0x02);
	}
	else
	{
		if (wArg04 != 0x01)
		{
			int32 dx_ax_1285 = fn0800_3EB2(0x03, Mem273[ds:0x2982:word16], 0x00, Mem273[ds:0x2980:word16]);
			word16 ax_297 = (word16) dx_ax_1285;
			Eq_8793 dx_ax_988 = SEQ(__rcl<word16,byte>(SLICE(dx_ax_1285 + 0x02, word16, 16), 0x01, cond((ax_297 + 0x02) * 0x02) & 0x02), (ax_297 + 0x02) * 0x02) + CONVERT(Mem273[ds:0x2A40:word16], uint16, uint32);
			int16 ax_324 = ((SLICE(dx_ax_988, word16, 16) << 0x0C) + Mem273[ds:10818:word16])->*(word16) dx_ax_988;
			__wait();
			__wait();
			real64 rLoc1_1079 = CONVERT(ax_324, int16, real64) * Mem325[ds:0x29A2:real64];
			__wait();
			__wait();
			ui32 bx_si_991 = fn0800_3EB2(0x03, Mem333[ds:0x2982:word16], 0x00, Mem333[ds:0x2980:word16]) + CONVERT(wArg04, uint16, uint32);
			ui16 si_366 = (word16) bx_si_991 + ~0x01;
			uint32 bx_si_995 = SEQ(__rcl<word16,byte>(SLICE(bx_si_991 + ~0x01, word16, 16), 0x01, cond(si_366 * 0x02) & 0x02), si_366 * 0x02) + CONVERT(Mem354[ds:0x2A40:word16], uint16, uint32);
			wLoc0C_1083 = (int32) (ax_218 *s ((SLICE(bx_si_995, word16, 16) << 0x0C) + Mem354[ds:10818:word16])->*(word16) bx_si_995) /16 100;
			__wait();
			__wait();
			__wait();
			ax_401 = fn0800_0F76(CONVERT(ax_218, int16, real64) * rLoc1_1079 / CONVERT(Mem396[ds:4211:real32], real32, real64));
l1128_4F6D:
			fn1128_4F92(wLoc0C_1083, dx_ax_251 /16 0x0A, ax_401, dx_ax_241 /16 0x0A, 0x3C);
			return;
		}
		int32 dx_ax_1287 = fn0800_3EB2(0x03, Mem273[ds:0x2982:word16], 0x00, Mem273[ds:0x2980:word16]);
		word16 ax_415 = (word16) dx_ax_1287;
		Eq_8922 dx_ax_999 = SEQ(__rcl<word16,byte>(SLICE(dx_ax_1287 + 0x01, word16, 16), 0x01, cond((ax_415 + 0x01) * 0x02) & 0x02), (ax_415 + 0x01) * 0x02) + CONVERT(Mem273[ds:0x2A40:word16], uint16, uint32);
		wLoc0C_1083 = (int32) (ax_218 *s ((SLICE(dx_ax_999, word16, 16) << 0x0C) + Mem273[ds:10818:word16])->*(word16) dx_ax_999) /16 100;
		dx_ax_1274 = fn0800_3EB2(0x06, Mem452[ds:0x2982:word16], 0x00, Mem452[ds:0x2980:word16]);
	}
	Eq_8473 dx_ax_963 = dx_ax_1274 + CONVERT(Mem531[ds:0x2A40:word16], uint16, uint32);
	ax_401 = (int32) (ax_218 *s ((SLICE(dx_ax_963, word16, 16) << 0x0C) + Mem531[ds:10818:word16])->*(word16) dx_ax_963) /16 100;
	goto l1128_4F6D;
}

// 1128:4F92: void fn1128_4F92(Stack int16 wArg04, Stack int16 wArg06, Stack int16 wArg08, Stack int16 wArg0A, Stack byte bArg0C)
// Called from:
//      fn1128_4ACF
void fn1128_4F92(int16 wArg04, int16 wArg06, int16 wArg08, int16 wArg0A, byte bArg0C)
{
	if (wArg04 > 0x00 && (wArg04 < wArg06 && (wArg08 > 0x00 && wArg08 < wArg0A)))
	{
		word16 wArg0C;
		fn1BF1_2046(wArg04 + 0xA0, 0x01C2 - wArg08, (byte) wArg0C);
	}
}

// 1128:4FC9: void fn1128_4FC9(Stack Eq_6243 ptrArg04, Stack segptr32 ptrArg08, Stack int16 wArg0C)
// Called from:
//      fn1128_07AB
//      fn1128_43AC
void fn1128_4FC9(Eq_6243 ptrArg04, segptr32 ptrArg08, int16 wArg0C)
{
	int16 si_123;
	for (si_123 = 0x00; si_123 < wArg0C; ++si_123)
	{
		if ((&&(SLICE(ptrArg04, selector, 16)->*(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04).w0000))[si_123].w0000 == 0x01)
		{
			struct Eq_8983 * es_93 = SLICE(ptrArg08, selector, 16);
			union Eq_12 Eq_8983::* bx_91 = (word16) ptrArg08 + (si_123 << 0x02);
			fn1128_0436(ptrArg04, si_123, (es_93->*bx_91).u1);
			goto l1128_504C;
		}
		if ((&&(SLICE(ptrArg04, selector, 16)->*(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04).w0000))[si_123].w0000 == 0x03)
		{
			struct Eq_8999 * es_44 = SLICE(ptrArg08, selector, 16);
			union Eq_12 Eq_8999::* bx_43 = (word16) ptrArg08 + (si_123 << 0x02);
			int16 ax_55 = si_123 *s 0x06;
			fn1128_06D5((&&(SLICE(ptrArg04, selector, 16)->*((SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04).t0000).u0))[ax_55 + 0x02].t0000.u2, (&&(SLICE(ptrArg04, selector, 16)->*((SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04).t0000).u0))[ax_55 + 0x03].t0000.u2, 0x00, (es_44->*bx_43).u1);
l1128_504C:
		}
	}
}

// 1128:5DC0: Register int16 fn1128_5DC0(Register Eq_12 ds, Stack Eq_6243 ptrArg04, Stack segptr32 ptrArg08, Stack int16 wArg0C, Stack cup16 wArg0E, Register out Eq_12 dsOut)
// Called from:
//      main
//      fn1128_07AB
int16 fn1128_5DC0(Eq_12 ds, Eq_6243 ptrArg04, segptr32 ptrArg08, int16 wArg0C, cup16 wArg0E, union Eq_12 & dsOut)
{
	Mem17[ds:10714:word16] = 0x00;
	word16 ax_26;
	int16 ax_264;
	while (true)
	{
		int16 si_143;
		while (true)
		{
			ax_26 = fn1BC2_012F(ds, wArg0E, out ds);
			if (ax_26 != 0x00)
				break;
			word16 wLoc04_403 = 0x00;
			if (Mem145[ds:10712:word16] != 0xFF && fn1128_0715(ds, ptrArg04, Mem145[ds:10712:word16]) != 0x00)
			{
				if (ptrArg04[(Mem156[ds:10712:word16] *s 0x06 + 0x01) * 0x02] == 0x00)
				{
					ax_264 = Mem156[ds:10712:word16];
					goto l1128_5F67;
				}
				if (ptrArg04[(Mem156[ds:10712:word16] *s 0x06 + 0x01) * 0x02] == 0x01)
					wLoc04_403 = 0x01;
			}
			else
			{
				for (si_143 = 0x00; si_143 < wArg0C; ++si_143)
				{
					if (fn1128_0715(ds, ptrArg04, si_143) != 0x00)
					{
						if (*((word32) ptrArg04 + si_143 * 0x0C) == 0x01)
						{
							struct Eq_9215 * es_221 = SLICE(ptrArg08, selector, 16);
							union Eq_12 Eq_9215::* bx_219 = (word16) ptrArg08 + (si_143 << 0x02);
							fn1128_05BB(ptrArg04, si_143, (es_221->*bx_219).u1);
						}
						Mem250[ds:10712:word16] = si_143;
						if ((&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[si_143 *s 0x06 + 0x01] == 0x00)
							goto l1128_5F53;
						wLoc04_403 = 0x01;
					}
				}
			}
			if (wLoc04_403 == 0x00 && Mem292[ds:10712:word16] != 0xFF)
			{
				if (SLICE(ptrArg04, selector, 16):SLICE(ptrArg04, word16, 0)[Mem292[ds:10712:word16] * 0x0C] == 0x01)
				{
					struct Eq_9169 * es_312 = SLICE(ptrArg08, selector, 16);
					word16 bx_310 = SLICE(ptrArg08, word16, 0) + (Mem292[ds:10712:word16] << 0x02);
					fn1128_0436(ptrArg04, Mem319[ds:10712:word16], Mem292[es_312:bx_310 + 0x00:word32]);
				}
				Mem342[ds:10712:word16] = 0xFF;
			}
		}
		if (ax_26 != 0x01)
			break;
		for (si_143 = 0x00; si_143 < wArg0C; ++si_143)
		{
			if (fn1128_0715(ds, ptrArg04, si_143) != 0x00)
			{
				if (*((word32) ptrArg04 + si_143 * 0x0C) == 0x01)
				{
					struct Eq_9130 * es_99 = SLICE(ptrArg08, selector, 16);
					word16 bx_97 = SLICE(ptrArg08, word16, 0) + (Mem68[ds:10712:word16] << 0x02);
					fn1128_0436(ptrArg04, Mem105[ds:10712:word16], Mem68[es_99:bx_97 + 0x00:word32]);
				}
				Mem128[ds:10712:word16] = 0xFF;
				if ((&(SLICE(ptrArg04, selector, 16)->*(word16) ptrArg04))[si_143 *s 0x06 + 0x01] == 0x01)
				{
l1128_5F53:
					ax_264 = si_143;
					goto l1128_5F67;
				}
			}
		}
	}
	Mem48[ds:10714:word16] = ax_26;
	ax_264 = 0xFF;
l1128_5F67:
	dsOut = ds;
	return ax_264;
}

// 1128:5F6B: void fn1128_5F6B(Register Eq_12 ds, Stack Eq_902 dwArg04, Stack int32 dwArg08, Stack word16 wArg0C, Stack Eq_12 wArg0E, Stack Eq_12 wArg10)
// Called from:
//      fn1128_60AE
void fn1128_5F6B(Eq_12 ds, Eq_902 dwArg04, int32 dwArg08, word16 wArg0C, Eq_12 wArg0E, Eq_12 wArg10)
{
	Eq_169 ax_27 = (word16) ((int64) ((dwArg08 + 0x01) *s 100) /32 dwArg04);
	if (wArg0C != 0x00)
	{
		Mem35[ds:0x4FE4:word16] = 0x00;
		Mem36[ds:20454:word16] = ~0x00;
		fn1BF1_1211(0x01, 0x07);
		fn1BF1_1C32(wArg0E, wArg10, (word32) wArg0E + 0x00FE, &wArg10.u1->b000A);
		fn1BF1_2066((word32) wArg0E + 265, &wArg10.u1->t0002.ptr0000, (word32) wArg0E + 0x0121, &wArg10.u1->b000A, SEQ(ds, 18838));
		fn1BF1_1D5C(0x0C);
		fn1BF1_1F2A((word32) wArg0E + 0x0122, &wArg10.u1->t0002.ptr0000, SEQ(ds, 4969));
	}
	if (Mem119[ds:0x4FE4:word16] != ax_27 >>u 0x01)
	{
		Mem126[ds:0x4FE4:word16] = ax_27 >>u 0x01;
		if (Mem126[ds:0x4FE4:word16] != 0x00)
		{
			fn1BF1_1211(0x01, 0x01);
			Eq_9248 wLoc04_308;
			wLoc04_308.u0 = 0x00;
			while (wLoc04_308 <u Mem145[ds:0x4FE4:word16])
			{
				fn1BF1_1C32((word32) wArg0E + 3 + wLoc04_308 *s 0x05, &wArg10.u1->t0002.ptr0000, (word32) wArg0E + 6 + wLoc04_308 *s 0x05, &wArg10.u1->t0008.u0);
				wLoc04_308 = (word16) wLoc04_308 + 1;
			}
		}
	}
	if (Mem181[ds:20454:word16] != ax_27)
	{
		Mem188[ds:20454:word16] = ax_27;
		fn1BF1_1D5C(0x0C);
		fn1BF1_1526((word32) wArg0E + 265, &wArg10.u1->t0002.ptr0000, SEQ(ds, 18838), 0x00);
		<unknown> Eq_9337::* fp;
		word16 bx_402;
		fn1BF1_1F2A((word32) wArg0E + 265, &wArg10.u1->t0002.ptr0000, fn0800_4055(ax_27, fp - 0x0A, 0x0A, out bx_402));
	}
}

// 1128:60AE: void fn1128_60AE(Register Eq_12 ds, Stack Eq_169 wArg04, Stack Eq_12 wArg06)
// Called from:
//      fn1128_43AC
void fn1128_60AE(Eq_12 ds, Eq_169 wArg04, Eq_12 wArg06)
{
	word16 bx_640;
	word16 bx_638;
	word16 bx_636;
	mp16 fp;
	mp16 sp_286 = fp - 30;
	int32 dwLoc0E_560 = 0x00;
	int32 dwLoc0E_632 = 0x00;
	if (Mem10[ds:0x2984:word32] != 0x00)
	{
		fn1BF1_2066(0xA0, 464, 0x01CC, 474, SEQ(ds, 10838));
		word16 wLoc1E;
		fn1128_5F6B(ds, Mem43[ds:0x2984:word32], 0x00010000, 0xA0, 464, wLoc1E);
		int32 dwLoc06_575 = 0x00;
		while (true)
		{
			word16 wLoc04_577 = SLICE(dwLoc06_575, word16, 16);
			ui16 wLoc06_578 = (word16) dwLoc06_575;
			if (Mem60[ds:0x2984:word32] - 0x01 <= dwLoc06_575)
				break;
			uint32 ax_bx_540 = SEQ(__rcl<word16,byte>(SLICE(dwLoc06_575 + 0x03, word16, 16), 0x01, cond((wLoc06_578 + 0x03) * 0x02) & 0x02), (wLoc06_578 + 0x03) * 0x02) + CONVERT(Mem60[ds:0x2A40:word16], uint16, uint32);
			word16 ax_87 = ((SLICE(ax_bx_540, word16, 16) << 0x0C) + Mem60[ds:10818:word16])->*(word16) ax_bx_540;
			uint32 dx_bx_542 = SEQ(__rcl<word16,byte>(wLoc04_577, 0x01, cond(wLoc06_578 * 0x02) & 0x02), wLoc06_578 * 0x02) + CONVERT(Mem60[ds:0x2A40:word16], uint16, uint32);
			int16 ax_104 = ax_87 - ((SLICE(dx_bx_542, word16, 16) << 0x0C) + Mem60[ds:10818:word16])->*(word16) dx_bx_542;
			uint32 ax_bx_546 = SEQ(__rcl<word16,byte>(SLICE(dwLoc06_575 + 0x04, word16, 16), 0x01, cond((wLoc06_578 + 0x04) * 0x02) & 0x02), (wLoc06_578 + 0x04) * 0x02) + CONVERT(Mem112[ds:0x2A40:word16], uint16, uint32);
			word16 ax_133 = ((SLICE(ax_bx_546, word16, 16) << 0x0C) + Mem112[ds:10818:word16])->*(word16) ax_bx_546;
			uint32 dx_bx_550 = SEQ(__rcl<word16,byte>(SLICE(dwLoc06_575 + 0x01, word16, 16), 0x01, cond((wLoc06_578 + 0x01) * 0x02) & 0x02), (wLoc06_578 + 0x01) * 0x02) + CONVERT(Mem112[ds:0x2A40:word16], uint16, uint32);
			int16 ax_154 = ax_133 - ((SLICE(dx_bx_550, word16, 16) << 0x0C) + Mem112[ds:10818:word16])->*(word16) dx_bx_550;
			uint32 ax_bx_554 = SEQ(__rcl<word16,byte>(SLICE(dwLoc06_575 + 0x05, word16, 16), 0x01, cond((wLoc06_578 + 0x05) * 0x02) & 0x02), (wLoc06_578 + 0x05) * 0x02) + CONVERT(Mem162[ds:0x2A40:word16], uint16, uint32);
			word16 ax_183 = ((SLICE(ax_bx_554, word16, 16) << 0x0C) + Mem162[ds:10818:word16])->*(word16) ax_bx_554;
			ui32 dx_bx_558 = SEQ(__rcl<word16,byte>(SLICE(dwLoc06_575 + 0x02, word16, 16), 0x01, cond((wLoc06_578 + 0x02) * 0x02) & 0x02), (wLoc06_578 + 0x02) * 0x02) + CONVERT(Mem162[ds:0x2A40:word16], uint16, uint32);
			dwLoc0E_560 = CONVERT(Mem235[ds:0x2988:word16], word16, int32) *s CONVERT(fn195C_0B84(ds, ax_104, ax_154, ax_183 - Mem162[(SLICE(dx_bx_558, word16, 16) << 0x0C) + Mem162[ds:10818:word16]:SLICE(dx_bx_558, word16, 0) + 0x00:word16]), int16, int32) + dwLoc0E_560;
			fn1128_5F6B(ds, Mem249[ds:0x2984:word32], dwLoc06_575, 0x00, 0xA0, 464);
			++dwLoc06_575;
		}
		fn1BF1_1526(0xA0, 464, SEQ(ds, 10838), 0x00);
		sp_286 = fp - 0x1C;
		dwLoc0E_632 = (int64) dwLoc0E_560 /32 1000;
	}
	struct Eq_9378 Eq_349::* sp_298 = sp_286 - 2;
	Eq_349 ss;
	(ss->*sp_298).t0000.u2 = (byte Eq_4085::*) ds;
	(ss->*sp_298).tFFFFFFFE.u0 = 0x136B;
	(ss->*sp_298).tFFFFFFFC.u2 = (byte Eq_4085::*) wArg06;
	(ss->*sp_298).tFFFFFFFA.u0 = (int16) wArg04;
	fn0800_1BEC((ss->*sp_298).tFFFFFFFA.u2, (ss->*sp_298).tFFFFFFFE.u1);
	(ss->*sp_298).t0000.u2 = (byte Eq_4085::*) 0x0A;
	(ss->*sp_298).tFFFFFFFE.u0 = (word16) ss;
	(ss->*sp_298).tFFFFFFFC.u2 = (byte Eq_4085::*) (fp - 24);
	(ss->*sp_298).tFFFFFFFA.u0 = (int16) ((int32) (word16) dwLoc0E_632 /16 0x0E10);
	Eq_12 dx_ax_635 = fn0800_4055((ss->*sp_298).tFFFFFFFA.u0, (ss->*sp_298).tFFFFFFFC.u1, (ss->*sp_298).t0000.u2, out bx_636);
	(ss->*sp_298).t0000.u2 = SLICE(dx_ax_635, word16, 16);
	(ss->*sp_298).tFFFFFFFE.u0 = (word16) (word16) dx_ax_635;
	(ss->*sp_298).tFFFFFFFC.u2 = (byte Eq_4085::*) wArg06;
	(ss->*sp_298).tFFFFFFFA.u0 = (int16) wArg04;
	fn0800_1B7D((ss->*sp_298).tFFFFFFFA.u2, (ss->*sp_298).tFFFFFFFE.u1);
	(ss->*sp_298).t0000.u2 = (byte Eq_4085::*) ds;
	(ss->*sp_298).tFFFFFFFE.u0 = 0x1372;
	(ss->*sp_298).tFFFFFFFC.u2 = (byte Eq_4085::*) wArg06;
	(ss->*sp_298).tFFFFFFFA.u0 = (int16) wArg04;
	fn0800_1B7D((ss->*sp_298).tFFFFFFFA.u2, (ss->*sp_298).tFFFFFFFE.u1);
	(ss->*sp_298).t0000.u2 = (byte Eq_4085::*) 0x0A;
	(ss->*sp_298).tFFFFFFFE.u0 = (word16) ss;
	(ss->*sp_298).tFFFFFFFC.u2 = (byte Eq_4085::*) (fp - 24);
	(ss->*sp_298).tFFFFFFFA.u0 = (int16) ((int32) (word16) ((int64) dwLoc0E_632 % 0x0E10) /16 0x3C);
	Eq_12 dx_ax_637 = fn0800_4055((ss->*sp_298).tFFFFFFFA.u0, (ss->*sp_298).tFFFFFFFC.u1, (ss->*sp_298).t0000.u2, out bx_638);
	(ss->*sp_298).t0000.u2 = SLICE(dx_ax_637, word16, 16);
	(ss->*sp_298).tFFFFFFFE.u0 = (word16) (word16) dx_ax_637;
	(ss->*sp_298).tFFFFFFFC.u2 = (byte Eq_4085::*) wArg06;
	(ss->*sp_298).tFFFFFFFA.u0 = (int16) wArg04;
	fn0800_1B7D((ss->*sp_298).tFFFFFFFA.u2, (ss->*sp_298).tFFFFFFFE.u1);
	(ss->*sp_298).t0000.u2 = (byte Eq_4085::*) ds;
	(ss->*sp_298).tFFFFFFFE.u0 = 0x1374;
	(ss->*sp_298).tFFFFFFFC.u2 = (byte Eq_4085::*) wArg06;
	(ss->*sp_298).tFFFFFFFA.u0 = (int16) wArg04;
	fn0800_1B7D((ss->*sp_298).tFFFFFFFA.u2, (ss->*sp_298).tFFFFFFFE.u1);
	(ss->*sp_298).t0000.u2 = (byte Eq_4085::*) 0x0A;
	(ss->*sp_298).tFFFFFFFE.u0 = (word16) ss;
	(ss->*sp_298).tFFFFFFFC.u2 = (byte Eq_4085::*) (fp - 24);
	(ss->*sp_298).tFFFFFFFA.u0 = (int16) ((int32) (word16) ((int64) dwLoc0E_632 % 0x0E10) % 0x3C);
	Eq_12 dx_ax_639 = fn0800_4055((ss->*sp_298).tFFFFFFFA.u0, (ss->*sp_298).tFFFFFFFC.u1, (ss->*sp_298).t0000.u2, out bx_640);
	(ss->*sp_298).t0000.u2 = SLICE(dx_ax_639, word16, 16);
	(ss->*sp_298).tFFFFFFFE.u0 = (word16) (word16) dx_ax_639;
	(ss->*sp_298).tFFFFFFFC.u2 = (byte Eq_4085::*) wArg06;
	(ss->*sp_298).tFFFFFFFA.u0 = (int16) wArg04;
	fn0800_1B7D((ss->*sp_298).tFFFFFFFA.u2, (ss->*sp_298).tFFFFFFFE.u1);
}

