// PROJ5_1BC2.c
// Generated by decompiling PROJ5.EXE
// using Reko decompiler version 0.12.2.0.

#include "PROJ5.h"

// 1BC2:0001: Register word16 fn1BC2_0001(Register (ptr16 Eq_6130) ds, Stack word16 wArg04, Stack word16 wArg06, Stack word16 wArg08, Stack (ptr16 Eq_6130) wArg0A, Register out word16 diOut, Register out (ptr16 Eq_6146) dsOut)
// Called from:
//      main
word16 fn1BC2_0001(struct Eq_6130 * ds, word16 wArg04, word16 wArg06, word16 wArg08, struct Eq_6130 * wArg0A, word16 & diOut, struct Eq_6146 & dsOut)
{
	struct Eq_6146 * ds_37;
	word16 di_36;
	ds->w57EC = 0x09;
	ds->w57EE = wArg06;
	ds->w57F0 = wArg04;
	ds->ptr57FC = wArg0A;
	ds->w57F2 = wArg08;
	word16 si_40 = fn0800_5290(0x33, &ds->w57EC, &ds->w57EC, &ds->ptr57FC, out di_36, out ds_37);
	diOut = di_36;
	dsOut = ds_37;
	return si_40;
}

// 1BC2:003A: Register Eq_12 fn1BC2_003A(Register (ptr16 Eq_5614) es, Register Eq_12 ds)
// Called from:
//      main
Eq_12 fn1BC2_003A(struct Eq_5614 * es, Eq_12 ds)
{
	Mem10[ds:22508:word16] = 0x00;
	Eq_12 ds_25 = fn0800_525B(es, ds, 0x33, SEQ(ds, 22508), SEQ(ds, 22508));
	if (Mem20[ds_25:22508:word16] == 0x00)
	{
		fn0800_3431(ds_25, SEQ(ds_25, 5504));
		fn0800_4D6E(ds_25, ~0x00);
	}
	return ds_25;
}

// 1BC2:0072: Register (ptr16 Eq_5614) fn1BC2_0072(Register (ptr16 Eq_5614) es, Register Eq_12 ds, Stack (ptr32 Eq_10471) ptrArg04, Register out Eq_12 dsOut)
// Called from:
//      fn1BC2_012F
struct Eq_5614 * fn1BC2_0072(struct Eq_5614 * es, Eq_12 ds, struct Eq_10471 * ptrArg04, union Eq_12 & dsOut)
{
	Mem10[ds:22508:word16] = 0x03;
	Eq_12 ds_25 = fn0800_525B(es, ds, 0x33, SEQ(ds, 22508), SEQ(ds, 22508));
	Mem40[ptrArg04 + 0x00:byte] = Mem20[ds_25:0x57EE:byte];
	Mem45[ptrArg04 + 1:word16] = Mem40[ds_25:22512:word16];
	Mem50[ptrArg04 + 3:word16] = Mem45[ds_25:22514:word16];
	dsOut = ds_25;
	return SLICE(ptrArg04, selector, 16);
}

// 1BC2:00AC: Register Eq_12 fn1BC2_00AC(Register (ptr16 Eq_5614) es, Register Eq_12 ds, Stack ci16 wArg04, Stack ci16 wArg06)
// Called from:
//      fn1BC2_012F
Eq_12 fn1BC2_00AC(struct Eq_5614 * es, Eq_12 ds, ci16 wArg04, ci16 wArg06)
{
	Mem10[ds:22508:word16] = 0x04;
	Mem12[ds:22512:word16] = wArg04;
	Mem14[ds:22514:word16] = wArg06;
	return fn0800_525B(es, ds, 0x33, SEQ(ds, 22508), SEQ(ds, 22508));
}

// 1BC2:00D5: Register Eq_10486 fn1BC2_00D5(Register Eq_12 ds, Stack (ptr32 Eq_10527) ptrArg04, Register out (ptr16 Eq_10564) esOut, Register out Eq_12 dsOut)
// Called from:
//      fn1BC2_012F
Eq_10486 fn1BC2_00D5(Eq_12 ds, struct Eq_10527 * ptrArg04, struct Eq_10564 & esOut, union Eq_12 & dsOut)
{
	Mem10[ds:22508:word16] = 0x06;
	Mem16[ds:0x57EE:word16] = CONVERT(Mem10[ptrArg04 + 0x00:byte], int8, int16);
	Eq_12 ds_30 = fn0800_525B(SLICE(ptrArg04, selector, 16), ds, 0x33, SEQ(ds, 22508), SEQ(ds, 22508));
	Mem45[ptrArg04 + 1:word16] = Mem26[ds_30:22512:word16];
	Mem50[ptrArg04 + 3:word16] = Mem45[ds_30:22514:word16];
	Eq_10486 ax_51 = Mem50[ds_30:0x57EE:word16];
	esOut = SLICE(ptrArg04, selector, 16);
	dsOut = ds_30;
	return ax_51;
}

// 1BC2:0113: void fn1BC2_0113(Register Eq_12 ds, Stack uint16 wArg04, Stack Eq_12 wArg06)
// Called from:
//      fn1BC2_012F
void fn1BC2_0113(Eq_12 ds, uint16 wArg04, Eq_12 wArg06)
{
	fn0800_4C8F(wArg04);
	fn0800_537F(ds, wArg06);
	fn0800_4CBF();
}

// 1BC2:012F: Register int16 fn1BC2_012F(Register Eq_12 ds, Stack cup16 wArg04, Register out Eq_12 dsOut)
// Called from:
//      fn1128_5DC0
int16 fn1BC2_012F(Eq_12 ds, cup16 wArg04, union Eq_12 & dsOut)
{
	msmouse_show_cursor();
	int16 ax_258;
	while (true)
	{
		if (wArg04 != 0x00)
		{
			fn1BC2_0113(ds, 2100, 0x46);
			fn1BC2_0113(ds, 3000, 0x46);
		}
		<unknown> Eq_10585::* fp;
		struct Eq_5614 * es_68;
		if (fn1BC2_00D5(ds, fp - 8, out es_68, out ds) != 0x00)
			break;
		struct Eq_5614 * es_141 = fn1BC2_0072(es_68, ds, fp - 8, out ds);
		ci16 wLoc07;
		ci16 wLoc05;
		if (false)
		{
			if (Mem85[ds:0x580A:word16] == 0x00)
			{
				Mem356[ds:0x580A:word16] = 0x01;
l1BC2_01F6:
				Mem362[ds:0x5806:word16] = wLoc07;
				Mem364[ds:0x5808:word16] = wLoc05;
				msmouse_hide_cursor();
				ax_258 = 0x00;
				goto l1BC2_02EC;
			}
			if (Mem85[ds:0x580C:word16] == 0x00)
			{
				Mem107[ds:0x580C:word16] = 0x01;
				ci16 si_108;
				for (si_108 = 0x00; si_108 < 0x32; ++si_108)
				{
					fn0800_537F(ds, 0x0A);
					if (fn1BC2_00D5(ds, fp - 8, out es_141, out ds) != 0x00)
						goto l1BC2_01BC;
				}
			}
			fn0800_537F(ds, 0x0A);
			es_141 = fn1BC2_0072(es_141, ds, fp - 8, out ds);
			if (false)
				goto l1BC2_01F6;
		}
		if (fn0800_0FE0(0x01) != 0x00)
		{
			word16 ax_220 = fn0800_0FE0(0x00);
			int8 bLoc0A_418 = (byte) ax_220;
			int8 bLoc09_431 = SLICE(ax_220, byte, 8);
			if (bLoc0A_418 == 0x00)
			{
				if (bLoc09_431 == 75)
					wLoc07 -= 0x08;
				else if (bLoc09_431 == 72)
					wLoc05 -= 0x08;
				else if (bLoc09_431 == 77)
					wLoc07 += 0x08;
				else if (bLoc09_431 == 80)
					wLoc05 += 0x08;
				else
				{
					if (bLoc09_431 > 58 && bLoc09_431 < 82)
					{
						msmouse_hide_cursor();
						ax_258 = (int16) bLoc09_431;
						goto l1BC2_02EC;
					}
					fn1BC2_0113(ds, 1000, 100);
				}
				ds = fn1BC2_00AC(es_141, ds, wLoc07, wLoc05);
			}
			else
			{
				if (bLoc0A_418 == 27)
				{
					msmouse_hide_cursor();
					ax_258 = 0x1B;
					goto l1BC2_02EC;
				}
				if (bLoc0A_418 == 0x0D)
				{
					Mem255[ds:0x5806:word16] = wLoc07;
					Mem257[ds:0x5808:word16] = wLoc05;
					msmouse_hide_cursor();
					ax_258 = 0x0D;
					goto l1BC2_02EC;
				}
				fn1BC2_0113(ds, 1000, 100);
			}
		}
		Mem350[ds:0x580A:word16] = 0x00;
		Mem351[ds:0x580C:word16] = 0x00;
	}
l1BC2_01BC:
	Mem353[ds:0x580A:word16] = 0x00;
	Mem354[ds:0x580C:word16] = 0x00;
	msmouse_hide_cursor();
	ax_258 = 0x01;
l1BC2_02EC:
	dsOut = ds;
	return ax_258;
}

