// PROJ5_0800.c
// Generated by decompiling PROJ5.EXE
// using Reko decompiler version 0.12.2.0.

#include "PROJ5.h"

struct seg0800_t * g_ptr8000 = &g_tFFFFD3BA; // 00008000
// 0800:0146: void fn0800_0146()
// Called from:
//      fn0800_4D14
void fn0800_0146()
{
	selector seg0800;
	fn0800_022C(&Eq_18::t2948, &Eq_18::t2960, seg0800->ptr026D);
}

// 0800:0159: void fn0800_0159()
// Called from:
//      fn0800_4D14
void fn0800_0159()
{
}

// 0800:015A: void fn0800_015A(Stack Eq_24 bArg04)
// Called from:
//      fn0800_4D14
void fn0800_015A(Eq_24 bArg04)
{
	msdos_terminate(bArg04);
}

// 0800:01BB: void fn0800_01BB(Register Eq_12 ds)
// Called from:
//      fn0800_4D14
void fn0800_01BB(Eq_12 ds)
{
	msdos_set_interrupt_vector(0x00, Mem7[ds:0x5A:segptr32]);
	msdos_set_interrupt_vector(0x04, Mem16[ds:0x5E:segptr32]);
	msdos_set_interrupt_vector(0x05, Mem25[ds:0x62:segptr32]);
	msdos_set_interrupt_vector(0x06, Mem34[ds:0x66:segptr32]);
}

// 0800:022C: void fn0800_022C(Register (memptr (ptr16 Eq_18) Eq_16) si, Register (memptr (ptr16 Eq_18) Eq_16) di, Register (ptr16 Eq_18) es)
// Called from:
//      fn0800_0146
void fn0800_022C(struct Eq_16 Eq_18::* si, struct Eq_16 Eq_18::* di, struct Eq_18 * es)
{
	while (true)
	{
		cu8 ah_4 = 0x00;
		struct Eq_16 Eq_18::* dx_13 = di;
		struct Eq_16 Eq_18::* bx_51;
		for (bx_51 = si; bx_51 != di; ++bx_51)
		{
			if ((es->*bx_51).b0000 != ~0x00 && (es->*bx_51).b0001 >= ah_4)
			{
				ah_4 = (es->*bx_51).b0001;
				dx_13 = bx_51;
			}
		}
		if (dx_13 == di)
			break;
		(es->*dx_13).b0000 = ~0x00;
		if ((es->*dx_13).b0000 != 0x00)
			(es->*dx_13).t0002.u0();
		else
		{
			selector seg0800;
			(seg0800->*((es->*dx_13).t0002).u1)();
		}
	}
}

struct Eq_18 * g_ptr026D = null; // 0800:026D
// 0800:04AB: Register word16 fn0800_04AB(Register Eq_12 ds)
// Called from:
//      fn1128_43AC
word16 fn0800_04AB(Eq_12 ds)
{
	fn0800_417A(ds);
	return 0x06;
}

// 0800:0F76: Register word16 fn0800_0F76(FpuStack real64 rArg0)
// Called from:
//      fn1128_4ACF
word16 fn0800_0F76(real64 rArg0)
{
	__wait();
	Eq_123 wLoc04_27 = __fstcw();
	__wait();
	__wait();
	__fldcw(SEQ(SLICE(wLoc04_27, byte, 8) | 0x0C, (byte) wLoc04_27));
	__wait();
	__wait();
	__fldcw(wLoc04_27);
	return (word16) rArg0;
}

// 0800:0FE0: Register word16 fn0800_0FE0(Stack byte bArg04)
// Called from:
//      fn1BC2_012F
word16 fn0800_0FE0(byte bArg04)
{
	__syscall<byte>(22);
	word16 ax_25 = SEQ(bArg04, 0x00);
	if (false)
	{
		if ((bArg04 & 0x01) != 0x00 && ax_25 == 0x00)
			ax_25 = ~0x00;
	}
	else if ((bArg04 & 0x01) != 0x00)
		ax_25 = 0x00;
	return ax_25;
}

// 0800:1969: Sequence word32 fn0800_1969(Stack Eq_169 dwArg04, Stack Eq_170 dwArg08)
// Called from:
//      fn0800_1D65
word32 fn0800_1969(Eq_169 dwArg04, Eq_170 dwArg08)
{
	word16 wArg06 = SLICE(dwArg04, word16, 16);
	word16 wArg04 = (word16) dwArg04;
	Eq_12 ax_23 = fn0800_1C56(dwArg08);
	fn0800_1A99(dwArg04, dwArg08, (word32) ax_23 + 1);
	return SEQ(wArg06, (char *) &ax_23.u1->t0000.u0 + wArg04);
}

// 0800:19A6: Sequence uipr32 fn0800_19A6(Register (ptr16 Eq_191) ds, Stack Eq_192 wArg04, Stack (ptr16 Eq_193) wArg06, Stack (ptr32 byte) dwArg08)
// Called from:
//      fn1A29_00DA
uipr32 fn0800_19A6(struct Eq_191 * ds, Eq_192 wArg04, struct Eq_193 * wArg06, byte * dwArg08)
{
	if ((wArg04 | wArg06) != 0x00)
	{
		ds->ptr5814 = wArg06;
		ds->t5812 = wArg04;
	}
	while (*ds->t5812.u1 != 0x00)
	{
		byte * ptrLoc06_163 = dwArg08;
		while (true)
		{
			word16 wLoc06_164 = (word16) ptrLoc06_163;
			word16 wLoc04_213 = SLICE(ptrLoc06_163, word16, 16);
			if (*ptrLoc06_163 == 0x00 || *ptrLoc06_163 == *(ds->t5812).u1)
				break;
			ptrLoc06_163 = SEQ(wLoc04_213, wLoc06_164 + 0x01);
		}
		if (*ptrLoc06_163 == 0x00)
			break;
		ds->t5812.u1 = (word32) ds->t5812 + 1;
	}
	uipr32 dx_ax_254;
	if (*ds->t5812.u1 == 0x00)
		dx_ax_254 = 0x00;
	else
	{
		struct Eq_193 * dx_80 = ds->ptr5814;
		Eq_192 ax_81 = ds->t5812;
		while (*ds->t5812.u1 != 0x00)
		{
			byte * ptrLoc06_173 = dwArg08;
			while (true)
			{
				word16 wLoc06_174 = (word16) ptrLoc06_173;
				word16 wLoc04_220 = SLICE(ptrLoc06_173, word16, 16);
				if (*ptrLoc06_173 == 0x00)
					break;
				Eq_192 es_bx_112 = ds->t5812;
				if (*ptrLoc06_173 == *es_bx_112.u1)
				{
					*es_bx_112.u1 = 0x00;
					ds->t5812.u1 = (word32) ds->t5812 + 1;
					goto l0800_1A65;
				}
				ptrLoc06_173 = SEQ(wLoc04_220, wLoc06_174 + 0x01);
			}
			ds->t5812.u1 = (word32) ds->t5812 + 1;
		}
l0800_1A65:
		dx_ax_254 = &(dx_80->*ax_81.u1);
	}
	return dx_ax_254;
}

// 0800:1A99: void fn0800_1A99(Stack Eq_169 ptrArg04, Stack Eq_170 ptrArg08, Stack Eq_12 wArg0C)
// Called from:
//      fn0800_1969
//      fn0800_321F
void fn0800_1A99(Eq_169 ptrArg04, Eq_170 ptrArg08, Eq_12 wArg0C)
{
	Eq_319 size_23 = (wArg0C >> 0x01) *32 0x02;
	memcpy(ptrArg04, ptrArg08, size_23);
	struct Eq_327 * es_24 = SLICE(ptrArg04, selector, 16);
	struct Eq_329 * ds_26 = SLICE(ptrArg08, selector, 16);
	byte Eq_329::* si_29 = (word16) (ptrArg08 + size_23);
	byte Eq_327::* di_30 = (word16) (ptrArg04 + size_23);
	if (wArg0C >> 0x01 < 0x00)
		es_24->*di_30 = ds_26->*si_29;
}

// 0800:1B7D: void fn0800_1B7D(Stack Eq_169 ptrArg04, Stack Eq_349 ptrArg08)
// Called from:
//      fn0800_1D65
//      fn1128_60AE
void fn0800_1B7D(Eq_169 ptrArg04, Eq_349 ptrArg08)
{
	struct Eq_357 Eq_369::* di_26 = (word16) ptrArg04 + ((word32) strlen(ptrArg04) + 1);
	Eq_364 size_34 = strlen(ptrArg08) + 1;
	Eq_364 cx_37 = size_34;
	cui16 di_38 = (word16) ptrArg08;
	struct Eq_369 * es_24 = SLICE(ptrArg04, selector, 16);
	struct Eq_371 * es_32 = SLICE(ptrArg08, selector, 16);
	struct Eq_357 Eq_369::* di_46 = di_26 - 1;
	<unknown>* si_47 = di_38;
	if ((di_38 & 0x01) != 0x00)
	{
		(es_24->*di_26).bFFFFFFFF = ptrArg08.u1->b0000;
		si_47 = (<unknown>*) (di_38 + 1);
		di_46 = di_26;
		cx_37 = size_34 - 0x01;
	}
	Eq_382 cx_59 = cx_37 >> 0x01;
	memcpy(&(es_24->*di_46).bFFFFFFFF + 1, si_47, cx_59 *32 0x02);
	byte Eq_371::* si_67 = (byte Eq_371::*) ((char *) si_47 + cx_59 *16 0x02);
	byte Eq_369::* di_68 = (byte Eq_369::*) (di_46 + cx_59 *16 0x02);
	if (cx_59 < 0x00)
		es_24->*di_68 = es_32->*si_67;
}

// 0800:1BEC: Register byte fn0800_1BEC(Stack Eq_169 ptrArg04, Stack Eq_349 ptrArg08)
// Called from:
//      main
//      fn1128_60AE
//      fn1A29_0326
//      fn1A29_04E4
byte fn0800_1BEC(Eq_169 ptrArg04, Eq_349 ptrArg08)
{
	word16 wArg06_52 = SLICE(ptrArg04, word16, 16);
	memcpy(ptrArg04, ptrArg08, (uint32) (strlen(ptrArg08) - ~0x00));
	return SLICE(wArg06_52, byte, 8);
}

// 0800:1C56: Register Eq_440 fn0800_1C56(Stack Eq_170 ptrArg04)
// Called from:
//      fn0800_1969
//      fn0800_3431
Eq_440 fn0800_1C56(Eq_170 ptrArg04)
{
	word16 wArg06_54 = SLICE(ptrArg04, word16, 16);
	word16 di_19 = (word16) ptrArg04;
	Eq_440 ax_16;
	ax_16.u1 = 0x00;
	if (wArg06_54 != 0x00 || di_19 != 0x00)
		ax_16 = strlen(ptrArg04);
	return ax_16;
}

// 0800:1CF4: void fn0800_1CF4(Stack (ptr32 uint16) ptrArg04)
// Called from:
//      fn0800_1D24
void fn0800_1CF4(uint16 * ptrArg04)
{
	*ptrArg04 = (uint16) msdos_get_current_default_drive() + 0x01;
}

// 0800:1D24: Register byte fn0800_1D24()
// Called from:
//      fn1A29_04E4
byte fn0800_1D24()
{
	<unknown> Eq_468::* fp;
	fn0800_1CF4(fp - 4);
	word16 wLoc04;
	return (byte) wLoc04 - 0x01;
}

// 0800:1D65: Sequence Eq_169 fn0800_1D65(Register Eq_12 ds, Stack uint16 wArg02, Stack word16 wArg04, Stack word16 wArg06, Stack Eq_169 dwArg08)
// Called from:
//      fn0800_258A
Eq_169 fn0800_1D65(Eq_12 ds, uint16 wArg02, word16 wArg04, word16 wArg06, Eq_169 dwArg08)
{
	Eq_169 dwArg08_160 = dwArg08;
	if (dwArg08 == 0x00)
		dwArg08_160 = SEQ(ds, 22550);
	Eq_170 dwArg04;
	Eq_170 dx_ax_163;
	if (dwArg04 == 0x00)
		dx_ax_163 = SEQ(ds, 0x21DE);
	else
		dx_ax_163 = dwArg04;
	fn0800_4031(fn0800_1969(dwArg08_160, dx_ax_163), wArg02);
	fn0800_1B7D(dwArg08_160, SEQ(ds, 0x21E2));
	return dwArg08_160;
}

// 0800:1F49: void fn0800_1F49(Register Eq_12 ds, Stack (ptr32 char) ptrArg04)
// Called from:
//      fn1A29_0326
void fn0800_1F49(Eq_12 ds, char * ptrArg04)
{
	Eq_12 ax_22;
	if (msdos_chdir(ptrArg04, out ax_22))
		fn0800_1F84(ds, ax_22);
}

// 0800:1F65: void fn0800_1F65(Register byte al, Register byte dh, Register Eq_12 ds, Stack byte bArg04, Stack word16 wArg06)
// Called from:
//      fn1A29_04E4
void fn0800_1F65(byte al, byte dh, Eq_12 ds, byte bArg04, word16 wArg06)
{
	Eq_12 ax_29 = SEQ(0x47, al);
	segptr32 ptrArg06;
	if (msdos_get_current_directory(bArg04, SLICE(ptrArg06, selector, 16), SEQ(dh, bArg04)))
		fn0800_1F84(ds, ax_29);
}

// 0800:1F84: Register word16 fn0800_1F84(Register Eq_12 ds, Stack Eq_12 wArg02)
// Called from:
//      fn0800_1F49
//      fn0800_1F65
//      fn0800_1FEB
//      fn0800_2018
//      fn0800_2067
//      fn0800_255E
//      fn0800_35B7
//      fn0800_37B4
//      fn0800_37D5
//      fn0800_3808
//      fn0800_3ADF
//      fn0800_3B14
//      fn0800_3CBC
//      fn0800_3D28
//      fn0800_3DF9
//      fn0800_3E55
//      fn0800_4AEA
//      fn0800_5290
word16 fn0800_1F84(Eq_12 ds, Eq_12 wArg02)
{
	Eq_12 dx_16 = wArg02;
	int16 dx_22;
	if (wArg02 >= 0x00)
	{
		if (wArg02 <= 88)
			goto l0800_1F98;
	}
	else
	{
		dx_22 = -wArg02;
		if (dx_22 <= Mem14[ds:0x236C:word16])
		{
			Mem26[ds:8680:word16] = ~0x00;
l0800_1FB5:
			Mem40[ds:0x7E:word16] = dx_22;
			return ~0x00;
		}
	}
	dx_16.u0 = 0x57;
l0800_1F98:
	Mem33[ds:8680:word16] = dx_16;
	dx_22 = (int16) (ds->*((word32) dx_16 + 8682));
	goto l0800_1FB5;
}

// 0800:1FD6: Register cui16 fn0800_1FD6(Stack int16 wArg04)
// Called from:
//      fn0800_2983
cui16 fn0800_1FD6(int16 wArg04)
{
	cui16 dx_17;
	msdos_ioctl_get_device_info(wArg04, out dx_17);
	return dx_17 & 0x80;
}

// 0800:1FEB: Register Eq_12 fn0800_1FEB(Register Eq_12 ds, Stack Eq_12 wArg04, Stack (ptr32 int32) dwArg06, Stack byte bArg0A, Register out word16 dxOut)
// Called from:
//      fn0800_2D94
//      fn0800_306C
//      fn0800_321F
//      fn0800_35B7
//      fn0800_3D28
Eq_12 fn0800_1FEB(Eq_12 ds, Eq_12 wArg04, int32 * dwArg06, byte bArg0A, word16 & dxOut)
{
	int32 * dx_ax_28;
	(*((word32) ds + 8566))[wArg04] &= ~0x0200;
	Eq_12 ax_31 = (word16) dx_ax_28;
	word16 dx_67 = SLICE(dx_ax_28, word16, 16);
	if (msdos_set_file_position(wArg04, dwArg06, bArg0A, out dx_ax_28))
	{
		int32 * dx_ax_41 = (int32 *) fn0800_1F84(ds, ax_31);
		ax_31 = (word16) dx_ax_41;
		dx_67 = SLICE(dx_ax_41, word16, 16);
	}
	dxOut = dx_67;
	return ax_31;
}

// 0800:2018: Register Eq_12 fn0800_2018(Register Eq_12 ds, Stack Eq_12 wArg04, Stack (ptr32 byte) ptrArg06, Stack Eq_12 wArg0A)
// Called from:
//      fn0800_204B
//      fn0800_2B51
//      fn0800_3D28
Eq_12 fn0800_2018(Eq_12 ds, Eq_12 wArg04, byte * ptrArg06, Eq_12 wArg0A)
{
	Eq_12 wLoc08_67;
	Eq_12 ax_30;
	if (((*((word32) ds + 8566))[wArg04] & 0x02) != 0x00)
		wLoc08_67.u0 = 0x05;
	else
	{
		if (!msdos_read_file(wArg04, wArg0A, ptrArg06, out ax_30))
			return ax_30;
		wLoc08_67 = ax_30;
	}
	ax_30 = fn0800_1F84(ds, wLoc08_67);
	return ax_30;
}

// 0800:204B: void fn0800_204B(Register Eq_12 ds, Stack Eq_12 wArg04, Stack (ptr32 byte) dwArg06, Stack Eq_12 wArg0A)
// Called from:
//      fn0800_3D28
void fn0800_204B(Eq_12 ds, Eq_12 wArg04, byte * dwArg06, Eq_12 wArg0A)
{
	fn0800_2018(ds, wArg04, dwArg06, wArg0A);
}

// 0800:2067: void fn0800_2067(Register Eq_12 ds, Stack (ptr32 char) ptrArg04)
// Called from:
//      fn0800_258A
void fn0800_2067(Eq_12 ds, char * ptrArg04)
{
	Eq_12 ax_22;
	if (msdos_delete_file(ptrArg04, out ax_22))
		fn0800_1F84(ds, ax_22);
}

// 0800:2083: Register word16 fn0800_2083(Sequence (ptr32 byte) es_di, Register byte dh, Register byte dl)
// Called from:
//      fn0800_209B
word16 fn0800_2083(byte * es_di, byte dh, byte dl)
{
	struct Eq_666 * es = SLICE(es_di, selector, 16);
	word16 di_10 = fn0800_208A(es_di, dh);
	return fn0800_208A(di_10, dl);
}

// 0800:208A: Register word16 fn0800_208A(Sequence (ptr32 byte) es_di, Register byte al)
// Called from:
//      fn0800_2083
word16 fn0800_208A(byte * es_di, byte al)
{
	struct Eq_678 * es = SLICE(es_di, selector, 16);
	word16 ax_5 = __aam(al);
	byte al_6 = (byte) ax_5;
	word16 di_15 = fn0800_2093(es_di, SLICE(ax_5, byte, 8));
	return fn0800_2093(di_15, al_6);
}

// 0800:2093: Register word16 fn0800_2093(Sequence (ptr32 byte) es_di, Register byte al)
// Called from:
//      fn0800_208A
word16 fn0800_2093(byte * es_di, byte al)
{
	word16 di = (word16) es_di;
	*es_di = (bool) __daa(al + 0x90, &(al + 0x90)) + (al + 0xD0);
	return di + 1;
}

// 0800:209B: void fn0800_209B(Register Eq_716 cx, Register Eq_716 dx, Register Eq_716 bx, Register Eq_12 ds, Stack Eq_12 wArg02, Stack segptr32 ptrArg04)
// Called from:
//      fn0800_302B
void fn0800_209B(Eq_716 cx, Eq_716 dx, Eq_716 bx, Eq_12 ds, Eq_12 wArg02, segptr32 ptrArg04)
{
	Eq_724 fp;
	Eq_722 bLoc16_1532;
	bLoc16_1532.u0 = 0x50;
	struct Eq_726 Eq_12::* sp_1281 = fp - 0x9E;
	byte Eq_12::* wLoc06_1321 = fp - 0x98;
l0800_2108:
	byte Eq_12::* di_1013 = wLoc06_1321;
l0800_210B:
	struct Eq_734 * psegArg06_1804 = SLICE(ptrArg04, selector, 16);
	struct Eq_734 * es_1127 = SLICE(ptrArg04, selector, 16);
	byte Eq_734::* si_1001 = (word16) ptrArg04;
	Eq_12 ss;
	while (true)
	{
		Eq_731 al_37 = es_1127->*si_1001;
		++si_1001;
		Eq_731 al_1000 = al_37;
		if (al_37 == 0x00)
			break;
		if (al_37 == 0x25)
		{
			al_1000 = es_1127->*si_1001;
			++si_1001;
			if (al_1000 == 0x25)
				goto l0800_2118;
			wLoc06_1321 = di_1013;
			cu8 ch_1222 = 0x00;
			Eq_716 wLoc10_1326;
			wLoc10_1326.u0 = 0x00;
			cui16 wLoc04_1327 = 0x20;
			Eq_731 bLoc0D_1328;
			bLoc0D_1328.u0 = 0x00;
			Eq_716 wLoc0A_1329;
			wLoc0A_1329.u0 = ~0x00;
			Eq_716 wLoc0C_1330;
			wLoc0C_1330.u0 = ~0x00;
l0800_2150:
			Eq_716 ax_67;
			ax_67.u2 = (uint16) al_1000;
			uint8 bl_71 = al_1000 - 0x20;
			byte ah_1226 = 0x00;
			dx = ax_67;
			bx.u2 = (uint16) bl_71;
			cx = SEQ(ch_1222, 0x00);
			if (bl_71 < 0x60)
			{
				uint8 bl_78 = (uint8) (ds->*((word16) bx + 8779));
				bx.u2 = (uint16) bl_78;
				cx = SEQ(ch_1222, 0x00);
				if (bx > 0x17)
					goto l0800_24FA;
				bx *= 0x02;
				cx = SEQ(ch_1222, 0x00);
				switch (bx)
				{
				case 0x00:
					cx = SEQ(ch_1222, 0x00);
					if (ch_1222 <= 0x00)
					{
						if (bLoc0D_1328 != 0x2B)
							bLoc0D_1328 = al_1000;
						goto l0800_214E;
					}
					break;
				case 0x01:
					cx = SEQ(ch_1222, 0x00);
					if (ch_1222 <= 0x00)
					{
						wLoc04_1327 |= 0x01;
						goto l0800_214E;
					}
					break;
				case 0x02:
					Eq_716 ax_943 = (ss->*wArg02.u1).t0000.u0;
					ah_1226 = SLICE(ax_943, byte, 8);
					wArg02.u1 = &wArg02.u1->t0002.ptr0000;
					if (ch_1222 >= 0x02)
					{
						cx = SEQ(ch_1222, 0x00);
						if (ch_1222 != 0x04)
							goto l0800_21BC;
						wLoc0C_1330 = ax_943;
						++ch_1222;
						goto l0800_214E;
					}
					else
					{
						Eq_716 ax_953 = ax_943;
						if (ax_943 < 0x00)
						{
							ax_953 = -ax_943;
							wLoc04_1327 |= 0x02;
						}
						wLoc0A_1329 = ax_953;
						ch_1222 = 0x03;
						goto l0800_21DD;
					}
				case 0x03:
					cx = SEQ(ch_1222, 0x00);
					if (ch_1222 <= 0x00)
					{
						wLoc04_1327 |= 0x02;
						goto l0800_214E;
					}
					break;
				case 0x04:
					cx = SEQ(ch_1222, 0x00);
					if (ch_1222 >= 0x04)
						goto l0800_21BC;
					ch_1222 = 0x04;
					wLoc0C_1330 = (word16) wLoc0C_1330 + 1;
					goto l0800_214E;
				case 0x05:
					goto l0800_21FA;
				case 0x06:
					wLoc04_1327 |= 0x10;
					goto l0800_21A4;
				case 0x07:
					wLoc04_1327 |= 0x0100;
					goto l0800_2244;
				case 0x08:
l0800_2244:
					wLoc04_1327 &= ~0x10;
					goto l0800_21A4;
				case 0x09:
					if (ch_1222 <= 0x00)
					{
						if ((wLoc04_1327 & 0x02) == 0x00)
						{
							wLoc04_1327 |= 0x08;
							ch_1222 = 0x01;
							goto l0800_214E;
						}
					}
					else
					{
l0800_21FA:
						Eq_716 ax_886;
						ax_886.u1 = (int16) (al_1000 - 0x30);
						ah_1226 = 0x00;
						if (ch_1222 <= 0x02)
						{
							ch_1222 = 0x02;
							wLoc0A_1329 = ax_886;
							if (wLoc0A_1329 >= 0x00)
							{
								wLoc0A_1329 = (word16) ax_886.u1 + wLoc0A_1329 * 0x0A;
								goto l0800_214E;
							}
						}
						else
						{
							cx = SEQ(ch_1222, 0x00);
							if (ch_1222 != 0x04)
							{
l0800_21BC:
								goto l0800_24FA;
							}
							wLoc0C_1330 = ax_886;
							if (wLoc0C_1330 != 0x00)
							{
								wLoc0C_1330 = (word16) ax_886.u1 + wLoc0C_1330 * 0x0A;
								goto l0800_214E;
							}
						}
					}
l0800_21DD:
					goto l0800_214E;
				case 0x0A:
					uint8 bLoc08_1370 = 0x01;
					Eq_902 ax_363 = (ss->*wArg02.u1).t0000.u0;
					Eq_907 bx_2099 = SEQ(0x0A, bl_78 * 0x02);
					goto l0800_227D;
				case 11:
					Eq_907 bx_2107 = SEQ(0x08, bl_78 * 0x02);
					goto l0800_2259;
				case 0x0C:
					bx_2107 = SEQ(0x0A, bl_78 * 0x02);
					goto l0800_2259;
				case 0x0D:
					bx_2107 = SEQ(0x10, (byte) al_1000 + 233);
l0800_2259:
					bLoc0D_1328.u0 = 0x00;
					bLoc08_1370 = 0x00;
					ax_363 = (ss->*wArg02.u1).t0000.u0;
					bx_2099 = bx_2107;
l0800_227D:
					struct Eq_1068 Eq_12::* di_371 = (struct Eq_1068 Eq_12::*) ((word32) wArg02 + 1);
					int8 bh_439 = SLICE(bx_2099, byte, 8);
					Eq_12 dx_382;
					dx_382.u0 = 0x00;
					Eq_12 di_372;
					di_372.u1 = &di_371->t0001.u0;
					ptrArg04 = &(psegArg06_1804->*si_1001);
					if ((wLoc04_1327 & 0x10) != 0x00)
					{
						dx_382.u2 = (ss->*di_371).t0001.u2;
						di_372.u1 = (char *) &di_371->t0001 + 2;
					}
					wArg02 = di_372;
					if (ax_363 == 0x00 && dx_382 == 0x00)
					{
						if (wLoc0C_1330 == 0x00)
							goto l0800_22BE;
					}
					else
						wLoc04_1327 |= 0x04;
					struct Eq_1121 Eq_12::* sp_422 = sp_1281 - 2;
					(ss->*sp_422).t0000.u2 = (byte Eq_4085::*) dx_382;
					(ss->*sp_422).tFFFFFFFE.u1 = (uint16) ax_363;
					(ss->*sp_422).tFFFFFFFC.u2 = (byte Eq_4085::*) ss;
					(ss->*sp_422).tFFFFFFFA.u2 = (byte Eq_4085::*) (fp - 71);
					(ss->*sp_422).tFFFFFFF8.u2 = (byte Eq_4085::*) (int16) bh_439;
					(ss->*sp_422).tFFFFFFF6.u0 = (uint16) bLoc08_1370;
					(ss->*sp_422).tFFFFFFF4.u1 = (word16) bx_2099;
					word16 dx_2116;
					word16 bx_2117;
					fn0800_3FAF((ss->*sp_422).tFFFFFFF4.u0, (ss->*sp_422).tFFFFFFF6.u1, (ss->*sp_422).tFFFFFFF8.u2, (ss->*sp_422).tFFFFFFFA.u1, (ss->*sp_422).tFFFFFFFE.u0, out dx_2116, out bx_2117);
l0800_22BE:
					union Eq_12 Eq_12::* sp_474 = sp_1281 - 2;
					(ss->*sp_474).u2 = (byte Eq_4085::*) ss;
					Eq_12 es_477;
					es_477.u2 = (ss->*sp_474).u2;
					sp_1281 = (struct Eq_726 Eq_12::*) ((char *) sp_474 + 2);
					dx = wLoc0C_1330;
					Eq_1038 es_di_2102;
					Eq_1038 es_di_2111;
					if (wLoc0C_1330 >= 0x00)
					{
						es_di_2102 = SEQ(es_477, fp - 71);
						goto l0800_23CC;
					}
					else
					{
						es_di_2111 = SEQ(es_477, fp - 71);
						goto l0800_23BE;
					}
				case 0x0E:
					struct Eq_921 Eq_12::* sp_282 = sp_1281 - 2;
					(ss->*sp_282).t0000.u2 = (byte Eq_4085::*) (ss->*wArg02.u1).t0000.u0;
					byte Eq_12::* di_279 = fp - 72;
					wArg02.u1 = &wArg02.u1->t0002.ptr0000;
					ptrArg04 = &(psegArg06_1804->*si_1001);
					if ((wLoc04_1327 & 0x20) != 0x00)
					{
						word16 dx_291 = (ss->*wArg02.u1).t0002.ptr0000;
						(ss->*sp_282).tFFFFFFFE.u2 = (byte Eq_4085::*) ss;
						Eq_12 es_298;
						es_298.u2 = (ss->*sp_282).tFFFFFFFE.u2;
						byte Eq_12::* di_304 = fn0800_2083(SEQ(es_298, fp - 72), SLICE(dx_291, byte, 8), (byte) dx_291);
						es_298->*di_304 = 0x3A;
						wArg02.u1 = (word32) wArg02 + 4;
						di_279 = di_304 + 1;
					}
					(ss->*sp_282).tFFFFFFFE.u2 = (byte Eq_4085::*) ss;
					Eq_12 dx_318;
					dx_318.u2 = (ss->*sp_282).t0000.u2;
					Eq_12 es_316;
					es_316.u2 = (ss->*sp_282).tFFFFFFFE.u2;
					byte Eq_12::* di_325 = fn0800_2083(SEQ(es_316, di_279), SLICE(dx_318, byte, 8), (byte) dx_318);
					ss->*di_325 = 0x00;
					sp_1281 = (struct Eq_726 Eq_12::*) ((char *) &sp_282->t0000 + 2);
					wLoc04_1327 &= ~0x04;
					Eq_716 di_337 = di_325 - (fp - 72);
					dx = wLoc0C_1330;
					if (wLoc0C_1330 <= di_337)
						dx = di_337;
					es_di_2111 = SEQ(es_316, fp - 72);
					goto l0800_23BE;
				case 0x0F:
					Eq_716 cx_221 = wLoc0C_1330;
					ptrArg04 = &(psegArg06_1804->*si_1001);
					if (wLoc0C_1330 < 0x00)
						cx_221.u0 = 0x06;
					struct Eq_1371 Eq_12::* sp_229 = sp_1281 - 2;
					(ss->*sp_229).t0000.u2 = (byte Eq_4085::*) ss;
					(ss->*sp_229).tFFFFFFFE.u2 = (byte Eq_4085::*) wArg02;
					(ss->*sp_229).tFFFFFFFC.u0 = (wchar_t) cx_221;
					(ss->*sp_229).tFFFFFFFA.u2 = (byte Eq_4085::*) ss;
					(ss->*sp_229).ptrFFFFFFF8 = fp - 71;
					(ss->*sp_229).tFFFFFFF6.u0 = (wchar_t) ax_67;
					(ss->*sp_229).wFFFFFFF4 = wLoc04_1327 & 0x01;
					word16 ax_259;
					if ((wLoc04_1327 & 0x0100) != 0x00)
					{
						ax_259 = 0x08;
						wArg02.u1 = &wArg02.u1->b000A;
					}
					else
					{
						wArg02.u1 = &wArg02.u1->t0008.u0;
						ax_259 = 0x06;
					}
					(ss->*sp_229).wFFFFFFF2 = ax_259;
					fn0800_417A(ds);
					(ss->*sp_229).tFFFFFFF0.u2 = (byte Eq_4085::*) ss;
					sp_1281 = sp_229 - 0x0E;
					es_di_2111 = SEQ((ss->*sp_229).tFFFFFFF0.u2, fp - 71);
l0800_23BE:
					byte Eq_12::* di_181 = (word16) es_di_2111;
					Eq_12 es_179;
					es_179.u1 = SLICE(es_di_2111, selector, 16);
					if ((wLoc04_1327 & 0x08) != 0x00)
					{
						dx = wLoc0A_1329;
						es_di_2102 = es_di_2111;
						if (wLoc0A_1329 > 0x00)
						{
l0800_23CC:
							di_181 = (word16) es_di_2102;
							es_179.u1 = SLICE(es_di_2102, selector, 16);
							Eq_716 cx_512 = fn0800_20B5(es_di_2102);
							if (*es_di_2102.u1 == 0x2D)
								--cx_512;
							dx -= cx_512;
							if (dx > 0x00)
								wLoc10_1326 = dx;
						}
					}
					if (es_179->*di_181 != 0x2D)
					{
						if (bLoc0D_1328 == 0x00)
							goto l0800_23FE;
						--di_181;
						es_179->*di_181 = (byte) bLoc0D_1328;
					}
					if (wLoc10_1326 > 0x00 && wLoc0C_1330 < 0x00)
						--wLoc10_1326;
l0800_23FE:
					Eq_716 cx_185 = fn0800_20B5(SEQ(es_179, di_181));
					goto l0800_2401;
				case 0x10:
					union Eq_12 Eq_12::* sp_204 = sp_1281 - 2;
					(ss->*sp_204).u2 = (byte Eq_4085::*) ss;
					wArg02.u1 = &wArg02.u1->t0002.ptr0000;
					es_179.u2 = (ss->*sp_204).u2;
					sp_1281 = (struct Eq_726 Eq_12::*) ((char *) sp_204 + 2);
					di_181 = fp - 71;
					cx_185.u0 = 0x01;
					ptrArg04 = &(psegArg06_1804->*si_1001);
					goto l0800_2401;
				case 0x11:
					ptrArg04 = &(psegArg06_1804->*si_1001);
					bool v73_1311;
					Eq_1038 es_di_147;
					if ((wLoc04_1327 & 0x20) == 0x00)
					{
						<unknown> Eq_12::* di_157 = (<unknown> Eq_12::*) (ss->*wArg02.u1).t0000.u0;
						union Eq_12 Eq_12::* sp_160 = sp_1281 - 2;
						(ss->*sp_160).u2 = (byte Eq_4085::*) ds;
						wArg02.u1 = &wArg02.u1->t0002.ptr0000;
						v73_1311 = di_157 != 0x00;
						es_di_147 = SEQ((ss->*sp_160).u2, di_157);
					}
					else
					{
						es_di_147.u1 = ds->*wArg02;
						wArg02.u1 = (word32) wArg02 + 4;
						v73_1311 = es_di_147 != 0x00;
					}
					Eq_1038 es_di_2096 = es_di_147;
					if (!v73_1311)
					{
						union Eq_12 Eq_12::* sp_172 = sp_1281 - 2;
						(ss->*sp_172).u2 = (byte Eq_4085::*) ds;
						es_di_2096 = SEQ(Mem175[ss:sp_172 + 0x00:selector], 0x2244);
					}
					di_181 = (word16) es_di_2096;
					es_179.u1 = SLICE(es_di_2096, selector, 16);
					cx_185 = fn0800_20B5(es_di_2096);
					if (cx_185 > wLoc0C_1330)
						cx_185 = wLoc0C_1330;
l0800_2401:
					byte Eq_12::* si_1207 = di_181;
					Eq_716 bx_591 = wLoc0A_1329;
					if ((wLoc04_1327 & 0x05) == 0x05)
					{
						if (al_1000 != 111)
						{
							if (al_1000 == 0x78 || al_1000 == 88)
							{
								Eq_716 v44_612 = wLoc10_1326 - 0x02;
								wLoc04_1327 |= 0x40;
								bx_591 = wLoc0A_1329 - 0x02;
								wLoc10_1326 = v44_612;
								if (v44_612 < 0x00)
									wLoc10_1326.u0 = 0x00;
							}
l0800_2444:
							cx = cx_185 + wLoc10_1326;
							if ((wLoc04_1327 & 0x02) == 0x00)
							{
								for (; bx_591 > cx; --bx_591)
									fn0800_20C2(SEQ(ss, fp - 2), 0x20, cx, dx, bx_591, di_1013, out di_1013);
							}
							if ((wLoc04_1327 & 0x40) != 0x00)
							{
								byte Eq_12::* di_694;
								fn0800_20C2(SEQ(ss, fp - 2), 0x30, cx, dx, bx_591, di_1013, out di_694);
								fn0800_20C2(SEQ(ss, fp - 2), al_1000, cx, dx, bx_591, di_694, out di_1013);
							}
							dx = wLoc10_1326;
							if (wLoc10_1326 > 0x00)
							{
								Eq_716 cx_717 = cx - wLoc10_1326;
								bx_591 -= wLoc10_1326;
								Eq_731 al_734 = es_179->*di_181;
								if (al_734 == 0x2D || (al_734 == 0x20 || al_734 == 0x2B))
								{
									fn0800_20C2(SEQ(ss, fp - 2), es_179->*di_181, cx_717, wLoc10_1326, bx_591, di_1013, out di_1013);
									si_1207 = di_181 + 1;
									--cx_717;
									--bx_591;
								}
								Eq_716 cx_770 = wLoc10_1326;
								if (wLoc10_1326 != 0x00)
								{
									do
									{
										fn0800_20C2(SEQ(ss, fp - 2), 0x30, cx_770, cx_717, bx_591, di_1013, out di_1013);
										--cx_770;
									} while (cx_770 != 0x00);
								}
								dx = cx_770;
								cx = cx_717;
							}
							if (cx != 0x00)
							{
								bx_591 -= cx;
								do
								{
									ss->*di_1013 = es_179->*si_1207;
									Eq_722 v48_808 = bLoc16_1532 - 0x01;
									++si_1207;
									++di_1013;
									bLoc16_1532 = v48_808;
									if (v48_808 <= 0x00)
										fn0800_20CB(SEQ(ss, fp - 2), cx, dx, bx_591, di_1013, out di_1013);
									--cx;
								} while (cx != 0x00);
							}
							bx = bx_591;
							if (bx_591 > 0x00)
							{
								cx = bx_591;
								do
								{
									fn0800_20C2(SEQ(ss, fp - 2), 0x20, cx, dx, bx_591, di_1013, out di_1013);
									--cx;
								} while (cx != 0x00);
							}
							goto l0800_210B;
						}
						if (wLoc10_1326 <= 0x00)
							wLoc10_1326.u0 = 0x01;
					}
					goto l0800_2444;
				case 0x12:
					ptrArg04 = &(psegArg06_1804->*si_1001);
					struct Eq_1003 Eq_12::* di_108;
					Eq_12 es_115;
					if ((wLoc04_1327 & 0x20) == 0x00)
					{
						di_108 = (struct Eq_1003 Eq_12::*) (ss->*wArg02.u1).t0000.u0;
						union Eq_12 Eq_12::* sp_113 = sp_1281 - 2;
						(ss->*sp_113).u2 = (byte Eq_4085::*) ds;
						wArg02.u1 = &wArg02.u1->t0002.ptr0000;
						es_115.u2 = (ss->*sp_113).u2;
					}
					else
					{
						segptr32 es_di_104 = (segptr32) (ds->*wArg02);
						es_115.u1 = SLICE(es_di_104, selector, 16);
						di_108 = (word16) es_di_104;
						wArg02.u1 = (word32) wArg02 + 4;
					}
					(es_115->*di_108).w0000 = (uint16) (0x50 - bLoc16_1532);
					if ((wLoc04_1327 & 0x10) != 0x00)
						(es_115->*di_108).w0002 = 0x00;
					goto l0800_2108;
				case 0x13:
				case 0x14:
				case 0x15:
					goto l0800_24FA;
				case 22:
					wLoc04_1327 &= ~0x20;
					goto l0800_21A4;
				case 0x17:
					wLoc04_1327 |= 0x20;
l0800_21A4:
					ch_1222 = 0x05;
l0800_214E:
					al_1000 = es_1127->*si_1001;
					++si_1001;
					goto l0800_2150;
				}
			}
l0800_24FA:
			dx = ax_67;
			byte Eq_734::* si_1011 = si_1001;
			uint16 ax_1015 = SEQ(ah_1226, 0x25);
			uint8 al_1031;
			do
			{
				uint16 ax_1233 = (uint16) al_1031;
				fn0800_20C2(SEQ(ss, fp - 2), (byte) ax_1015, cx, ax_67, bx, di_1013, out di_1013);
				al_1031 = psegArg06_1804->*si_1011;
				++si_1011;
				ax_1015 = ax_1233;
			} while (al_1031 != 0x00);
			break;
		}
l0800_2118:
		ss->*di_1013 = (byte) al_1000;
		Eq_722 v18_1090 = bLoc16_1532 - 0x01;
		++di_1013;
		bLoc16_1532 = v18_1090;
		if (v18_1090 <= 0x00)
			fn0800_20CB(SEQ(ss, fp - 2), cx, dx, bx, di_1013, out di_1013);
	}
	if (bLoc16_1532 < 0x50)
	{
		word16 di_2115;
		fn0800_20CB(SEQ(ss, fp - 2), cx, dx, bx, di_1013, out di_2115);
	}
}

// 0800:20B5: Register Eq_1574 fn0800_20B5(Sequence Eq_1038 es_di)
// Called from:
//      fn0800_209B
Eq_1574 fn0800_20B5(Eq_1038 es_di)
{
	return strlen(es_di);
}

// 0800:20C2: Register byte fn0800_20C2(Sequence (ptr32 Eq_768) ss_bp, Register Eq_731 al, Register Eq_716 cx, Register Eq_716 dx, Register Eq_716 bx, Register (memptr Eq_12 byte) di, Register out (memptr Eq_12 byte) diOut)
// Called from:
//      fn0800_209B
byte fn0800_20C2(struct Eq_768 * ss_bp, Eq_731 al, Eq_716 cx, Eq_716 dx, Eq_716 bx, byte Eq_12::* di, byte & diOut)
{
	word16 ax;
	al = (byte) ax;
	Eq_12 ss;
	ss.u1 = SLICE(ss_bp, selector, 16);
	ss->*di = (byte) al;
	Eq_1590 v9_10 = ss_bp->tFFFFFFEC.u0 - 0x01;
	ss_bp->tFFFFFFEC.u0 = (byte) v9_10;
	if (v9_10 != 0x00)
	{
		diOut = di + 1;
		return SLICE(ax, byte, 8);
	}
	else
	{
		byte Eq_12::* di_19;
		fn0800_20CB(ss_bp, cx, dx, bx, di + 1, out di_19);
		diOut = di_19;
		return 0x00;
	}
}

// 0800:20CB: Register byte fn0800_20CB(Sequence (ptr32 Eq_768) ss_bp, Register Eq_716 cx, Register Eq_716 dx, Register Eq_716 bx, Register (memptr Eq_12 byte) di, Register out (memptr Eq_12 byte) diOut)
// Called from:
//      fn0800_209B
//      fn0800_20C2
byte fn0800_20CB(struct Eq_768 * ss_bp, Eq_716 cx, Eq_716 dx, Eq_716 bx, byte Eq_12::* di, byte & diOut)
{
	word16 bp = (word16) ss_bp;
	word16 di_20 = di - (bp - 0x96);
	selector seg0800;
	(seg0800->*ss_bp->ptr000E)();
	word16 ax_39;
	if (ax_39 == 0x00)
		ss_bp->wFFFFFFEA = 0x01;
	ss_bp->tFFFFFFEC.u1 = 0x50;
	ss_bp->wFFFFFFEE += di_20;
	diOut = bp - 0x96;
	return SLICE(ax_39, byte, 8);
}

// 0800:255E: void fn0800_255E(Register int8 al, Register Eq_12 ds, Stack Eq_12 wArg04)
// Called from:
//      fn0800_258A
void fn0800_255E(int8 al, Eq_12 ds, Eq_12 wArg04)
{
	if (wArg04 >=u Mem14[ds:0x2174:word16])
		fn0800_1F84(ds, 0x06);
	else
	{
		(*((word32) ds + 8566))[wArg04] = 0x00;
		fn0800_37D5(al, ds, wArg04);
	}
}

// 0800:258A: Register Eq_12 fn0800_258A(Register Eq_12 ds, Stack Eq_1663 ptrArg04)
// Called from:
//      fn0800_2983
//      fn1A29_000C
//      fn1A29_0326
Eq_12 fn0800_258A(Eq_12 ds, Eq_1663 ptrArg04)
{
	word16 wArg04 = (word16) ptrArg04;
	if (ptrArg04 == 0x00 || (ptrArg04.u1)->w0012 != wArg04)
		return ds;
	if (ptrArg04.u1->t0006.u2 != 0x00)
	{
		if (ptrArg04.u1->w0000 < 0x00 && fn0800_264B(ds, ptrArg04) != 0x00)
			return ds;
		if ((ptrArg04.u1->w0002 & 0x04) != 0x00)
			fn0800_4648(ds, ptrArg04.u1->t000A.ptr0000, out ds);
	}
	if (ptrArg04.u1->b0004 >= 0x00)
	{
		int8 al_101 = ptrArg04.u1->b0004;
		fn0800_255E(al_101, ds, (int16) al_101);
	}
	ptrArg04.u1->w0002 = 0x00;
	ptrArg04.u1->t0006.u2 = (byte Eq_4085::*) 0x00;
	ptrArg04.u1->w0000 = 0x00;
	ptrArg04.u1->b0004 = ~0x00;
	if (ptrArg04.u1->w0010 != 0x00)
	{
		fn0800_2067(ds, fn0800_1D65(ds, ptrArg04.u1->w0010, 0x00, 0x00, 0x00));
		ptrArg04.u1->w0010 = 0x00;
	}
	return ds;
}

// 0800:264B: Register word16 fn0800_264B(Register Eq_12 ds, Stack Eq_1663 ptrArg04)
// Called from:
//      fn0800_258A
//      fn0800_2D94
//      fn0800_306C
//      fn0800_321F
//      fn0800_38EE
word16 fn0800_264B(Eq_12 ds, Eq_1663 ptrArg04)
{
	word16 wArg04 = (word16) ptrArg04;
	Eq_1704 wArg06 = (Eq_1704) SLICE(ptrArg04, word16, 16);
	if (ptrArg04 == 0x00)
	{
		fn0800_2820(ds);
		goto l0800_271E;
	}
	word16 ax_114;
	if (ptrArg04.u1->w0012 == wArg04)
	{
		if (ptrArg04.u1->w0000 >= 0x00)
		{
			if ((ptrArg04.u1->w0002 & 0x08) != 0x00 || ((ptrArg04.u1)->t000E).ptr0000 == wArg06 && ((ptrArg04.u1)->t000C).u0 == wArg04 + 0x05)
			{
				ptrArg04.u1->w0000 = 0x00;
				if (ptrArg04.u1->t000E.ptr0000 == wArg06 && ((ptrArg04.u1)->t000C).u0 == wArg04 + 0x05)
				{
					Eq_169 ax_111;
					ax_111.u0 = ptrArg04.u1->t0008.u0;
					ptrArg04.u1->t000E.ptr0000 = ptrArg04.u1->t000A.ptr0000;
					ptrArg04.u1->t000C.u0 = (int16) ax_111;
				}
			}
		}
		else
		{
			ci16 ax_37 = (ci16) (ptrArg04.u1->t0006.u2 + (ptrArg04.u1)->w0000);
			ptrArg04.u1->w0000 -= ax_37 + 0x01;
			Eq_1704 dx_47 = (Eq_1704) ptrArg04.u1->t000A.ptr0000;
			Eq_169 ax_48;
			ax_48.u0 = ptrArg04.u1->t0008.u0;
			ptrArg04.u1->t000E.ptr0000 = (struct Eq_14041 *) dx_47;
			ptrArg04.u1->t000C.u0 = (int16) ax_48;
			if (fn0800_35B7(ds, (int16) ptrArg04.u1->b0004, SEQ(dx_47, ax_48), ax_37 + 0x01) != ax_37 + 0x01 && ((ptrArg04.u1)->w0002 & 0x0200) == 0x00)
			{
				ptrArg04.u1->w0002 |= 0x10;
				goto l0800_2719;
			}
		}
l0800_271E:
		ax_114 = 0x00;
		return ax_114;
	}
	else
	{
l0800_2719:
		ax_114 = ~0x00;
		return ax_114;
	}
}

// 0800:2820: void fn0800_2820(Register Eq_12 ds)
// Called from:
//      fn0800_264B
void fn0800_2820(Eq_12 ds)
{
	Eq_12 wLoc08_116 = Mem17[ds:0x2174:word16];
	struct Eq_1889 * ptrLoc06_121 = SEQ(ds, 0x1D8C);
	while (true)
	{
		word16 wLoc06_124 = (word16) ptrLoc06_121;
		word16 wLoc04_129 = SLICE(ptrLoc06_121, word16, 16);
		--wLoc08_116;
		if (wLoc08_116 == 0x00)
			break;
		if (ptrLoc06_121->w0000 < 0x00)
		{
			ci16 ax_40 = ptrLoc06_121->w0006 + ptrLoc06_121->w0000;
			ptrLoc06_121->w0000 -= ax_40 + 0x01;
			word16 dx_51 = ptrLoc06_121->w000A;
			word16 ax_52 = ptrLoc06_121->w0008;
			ptrLoc06_121->w000E = dx_51;
			ptrLoc06_121->w000C = ax_52;
			wLoc06_124 = (word16) ptrLoc06_121;
			wLoc04_129 = SLICE(ptrLoc06_121, word16, 16);
			if (fn0800_35B7(ds, (int16) ptrLoc06_121->b0004, SEQ(dx_51, ax_52), ax_40 + 0x01) != ax_40 + 0x01 && (ptrLoc06_121->w0002 & 0x0200) == 0x00)
				ptrLoc06_121->w0002 |= 0x10;
		}
		ptrLoc06_121 = SEQ(wLoc04_129, wLoc06_124 + 0x14);
	}
}

// 0800:28A9: Register cui16 fn0800_28A9(Register Eq_12 ds, Stack (ptr32 word16) ptrArg02, Stack (ptr32 cui16) ptrArg06, Stack (ptr32 byte) ptrArg0A)
// Called from:
//      fn0800_2983
cui16 fn0800_28A9(Eq_12 ds, word16 * ptrArg02, cui16 * ptrArg06, byte * ptrArg0A)
{
	word16 wArg0A_182 = (word16) ptrArg0A;
	word16 wArg0C_188 = SLICE(ptrArg0A, word16, 16);
	word16 wLoc04_180 = 0x00;
	byte dl_22 = *ptrArg0A;
	byte * ptrArg0A_189 = SEQ(wArg0C_188, wArg0A_182 + 0x01);
	cui16 cx_106;
	cui16 wLoc06_185;
	if (dl_22 == 114)
	{
		cx_106 = 0x01;
		wLoc06_185 = 0x01;
	}
	else
	{
		if (dl_22 == 0x77)
			cx_106 = 770;
		else
		{
			if (dl_22 != 0x61)
				goto l0800_2946;
			cx_106 = 0x0902;
		}
		wLoc04_180 = 0x80;
		wLoc06_185 = 0x02;
	}
	byte dl_44 = *ptrArg0A_189;
	byte * ptrArg0A_194 = SEQ(wArg0C_188, wArg0A_182 + 0x02);
	if (dl_44 == 0x2B || *ptrArg0A_194 == 0x2B && (dl_44 == 116 || dl_44 == 0x62))
	{
		if (dl_44 == 0x2B)
			dl_44 = *ptrArg0A_194;
		cx_106 = cx_106 & ~0x03 | 0x04;
		wLoc04_180 = 0x0180;
		wLoc06_185 = 0x03;
	}
	cui16 cx_107;
	if (dl_44 == 116)
	{
		cx_107 = cx_106 | 0x4000;
		goto l0800_295D;
	}
	if (dl_44 == 0x62)
	{
		cx_107 = cx_106 | 0x8000;
		goto l0800_2959;
	}
	cui16 ax_113;
	if (dl_44 == 0x2B || dl_44 == 0x00)
	{
		cx_107 = cx_106 | Mem102[ds:8666:word16] & 0xC000;
		if ((cx_107 & 0x8000) == 0x00)
		{
l0800_295D:
			Mem139[ds:10006:word16] = 0x0800;
			Mem140[ds:10004:word16] = 14113;
			*ptrArg06 = cx_107;
			*ptrArg02 = wLoc04_180;
			ax_113 = wLoc06_185;
			return ax_113;
		}
l0800_2959:
		wLoc06_185 |= 0x40;
		goto l0800_295D;
	}
l0800_2946:
	ax_113 = 0x00;
	return ax_113;
}

// 0800:2983: Register word16 fn0800_2983(Register Eq_12 ds, Stack cui16 wArg02, Stack (ptr32 byte) dwArg04, Stack (ptr32 char) dwArg08, Stack Eq_1663 ptrArg0C, Register out word16 dxOut, Register out Eq_12 dsOut)
// Called from:
//      fn0800_2AA3
word16 fn0800_2983(Eq_12 ds, cui16 wArg02, byte * dwArg04, char * dwArg08, Eq_1663 ptrArg0C, word16 & dxOut, union Eq_12 & dsOut)
{
	cui16 wLoc06;
	cui16 wLoc04;
	<unknown> Eq_2076::* fp;
	cui16 ax_34 = fn0800_28A9(ds, fp - 6, fp - 4, dwArg04);
	ptrArg0C.u1->w0002 = ax_34;
	if (ax_34 == 0x00)
	{
l0800_29D3:
		ptrArg0C.u1->b0004 = ~0x00;
		ptrArg0C.u1->w0002 = 0x00;
		goto l0800_2A39;
	}
	else
	{
		if (ptrArg0C.u1->b0004 < 0x00)
		{
			int8 al_83 = fn0800_3B14(ds, dwArg08, wLoc04 | wArg02, wLoc06);
			ptrArg0C.u1->b0004 = al_83;
			if (al_83 < 0x00)
				goto l0800_29D3;
		}
		if (fn0800_1FD6((int16) ptrArg0C.u1->b0004) != 0x00)
			ptrArg0C.u1->w0002 |= 0x0200;
		ci16 ax_139;
		if ((ptrArg0C.u1->w0002 & 0x0200) != 0x00)
			ax_139 = 0x01;
		else
			ax_139 = 0x00;
		word16 wArg0E_280 = SLICE(ptrArg0C, word16, 16);
		word16 wArg0C_281 = (word16) ptrArg0C;
		word16 dx_188;
		word16 ax_189;
		if (fn0800_3492(ds, ptrArg0C, 0x00, 0x00, ax_139, 0x0200, out ds) == 0x00)
		{
			ptrArg0C.u1->w0010 = 0x00;
			dx_188 = wArg0E_280;
			ax_189 = wArg0C_281;
l0800_2A4E:
			dxOut = dx_188;
			dsOut = ds;
			return ax_189;
		}
		ds = fn0800_258A(ds, ptrArg0C);
l0800_2A39:
		dx_188 = 0x00;
		ax_189 = 0x00;
		goto l0800_2A4E;
	}
}

// 0800:2A56: Sequence (ptr32 Eq_2180) fn0800_2A56(Register Eq_12 ds)
// Called from:
//      fn0800_2AA3
struct Eq_2180 * fn0800_2A56(Eq_12 ds)
{
	struct Eq_2180 * ptrLoc06_74 = SEQ(ds, 0x1D8C);
	Eq_2191 wLoc06_75;
	do
	{
		wLoc06_75 = (word16) ptrLoc06_74;
		word16 wLoc04_79 = SLICE(ptrLoc06_74, word16, 16);
		if (ptrLoc06_74->b0004 < 0x00)
			break;
		ptrLoc06_74 = SEQ(wLoc04_79, (word16) wLoc06_75.u1 + 20);
	} while (wLoc06_75 <u Mem33[ds:0x2174:word16] *s 0x14 + 0x1D8C);
	struct Eq_2180 * dx_ax_110;
	if (ptrLoc06_74->b0004 >= 0x00)
		dx_ax_110 = 0x00;
	else
		dx_ax_110 = ptrLoc06_74;
	return dx_ax_110;
}

// 0800:2AA3: Sequence uipr32 fn0800_2AA3(Register Eq_12 ds, Stack (ptr32 char) dwArg04, Stack (ptr32 byte) dwArg08, Register out Eq_12 dsOut)
// Called from:
//      fn1A29_000C
//      fn1A29_0326
uipr32 fn0800_2AA3(Eq_12 ds, char * dwArg04, byte * dwArg08, union Eq_12 & dsOut)
{
	Eq_1663 dx_ax_124 = fn0800_2A56(ds);
	uipr32 dx_ax_126;
	if (dx_ax_124 == 0x00)
		dx_ax_126 = 0x00;
	else
	{
		word16 dx_60;
		dx_ax_126 = SEQ(dx_60, fn0800_2983(ds, 0x00, dwArg08, dwArg04, dx_ax_124, out dx_60, out ds));
	}
	dsOut = ds;
	return dx_ax_126;
}

// 0800:2B51: Register Eq_12 fn0800_2B51(Register Eq_12 dx, Register Eq_12 ds, Stack Eq_1663 ptrArg02, Stack Eq_12 wArg06, Stack (ptr32 byte) ptrArg08)
// Called from:
//      fn0800_2C70
Eq_12 fn0800_2B51(Eq_12 dx, Eq_12 ds, Eq_1663 ptrArg02, Eq_12 wArg06, byte * ptrArg08)
{
	byte * ptrArg08_284 = ptrArg08;
	Eq_12 wLoc04_250;
	do
	{
		word16 wArg08_264 = (word16) ptrArg08_284;
		word16 wArg0A_260 = SLICE(ptrArg08_284, word16, 16);
		if (wArg06 == 0x00)
			return wArg06;
		Eq_12 v11_22;
		v11_22.u1 = (word32) wArg06 + 1;
		wArg06 = v11_22;
		Eq_12 ax_33;
		if (ptrArg02.u1->t0006.u2 > v11_22)
			ax_33 = v11_22;
		else
			ax_33.u2 = ptrArg02.u1->t0006.u2;
		Eq_12 wLoc04_246 = ax_33;
		if ((ptrArg02.u1->w0002 & 0x40) == 0x00 || (((ptrArg02.u1)->t0006).u2 == 0x00 || (((ptrArg02.u1)->t0006).u2 >= v11_22 || (ptrArg02.u1)->w0000 != 0x00)))
		{
			while (true)
			{
				Eq_12 v20_134 = wArg06 - 0x01;
				word16 wArg08_285 = (word16) ptrArg08_284;
				word16 wArg0A_327 = SLICE(ptrArg08_284, word16, 16);
				wArg06 = v20_134;
				if (v20_134 == 0x00)
					break;
				Eq_12 v22_142 = wLoc04_246 - 0x01;
				wLoc04_246 = v22_142;
				if (v22_142 == 0x00)
					break;
				ci16 v23_149 = ptrArg02.u1->w0000 - 0x01;
				ptrArg02.u1->w0000 = v23_149;
				Eq_12 ax_161;
				if (v23_149 >= 0x00)
				{
					Eq_1704 dx_176 = (Eq_1704) ptrArg02.u1->t000E.ptr0000;
					Eq_169 si_177;
					si_177.u0 = ptrArg02.u1->t000C.u0;
					ptrArg02.u1->t000C.u0 = (int16) (ptrArg02.u1->t000C.u0 + 0x01);
					ax_161.u1 = (uint16) (dx_176->*si_177.u2);
				}
				else
					ax_161 = fn0800_39AF(ds, ptrArg02);
				dx = ax_161;
				byte dl_193 = (byte) ax_161;
				if (ax_161 == ~0x00)
					break;
				*ptrArg08_284 = dl_193;
				ptrArg08_284 = SEQ(wArg0A_327, wArg08_285 + 0x01);
			}
			if (dx != ~0x00)
				continue;
			goto l0800_2C01;
		}
		wLoc04_250.u0 = 0x00;
		for (wArg06 = v11_22 - 0x01; ptrArg02.u1->t0006.u2 <= wArg06; wArg06 -= ax_71)
		{
			Eq_12 ax_71;
			ax_71.u2 = ptrArg02.u1->t0006.u2;
			wLoc04_250.u1 = wLoc04_250 + ax_71;
		}
		Eq_12 ax_96 = fn0800_2018(ds, (int16) ptrArg02.u1->b0004, ptrArg08_284, wLoc04_250);
		dx = ax_96;
		if (ax_96 == ~0x00)
		{
			ptrArg02.u1->w0002 |= 0x10;
			dx.u0 = 0x00;
		}
		ptrArg08_284 = SEQ(wArg0A_260, (char *) &dx.u1->t0000.u0 + wArg08_264);
	} while (dx == wLoc04_250);
	wArg06.u1 = (char *) &wArg06.u1->t0000.u0 + (wLoc04_250 - dx);
l0800_2C01:
	ptrArg02.u1->w0002 |= 0x20;
	return wArg06;
}

// 0800:2C70: void fn0800_2C70(Register Eq_12 ds, Stack (ptr32 byte) dwArg04, Stack Eq_12 wArg08, Stack uint16 wArg0A, Stack Eq_1663 dwArg0C)
// Called from:
//      fn1A29_000C
//      fn1A29_0326
void fn0800_2C70(Eq_12 ds, byte * dwArg04, Eq_12 wArg08, uint16 wArg0A, Eq_1663 dwArg0C)
{
	if (wArg08 != 0x00)
	{
		word32 dx_ax_294 = fn0800_3F98(wArg0A, 0x00, 0x00, wArg08);
		Eq_12 ax_25 = (word16) dx_ax_294;
		Eq_12 dx_26;
		dx_26.u1 = SLICE(dx_ax_294, word16, 16);
		if (dx_26 <= 0x01 && (dx_26 < 0x01 || true))
			fn0800_2B51(dx_26, ds, dwArg0C, ax_25, dwArg04);
		else
		{
			word16 wLoc04_189 = wArg0A + 0x01;
			while (true)
			{
				word16 v26_52 = wLoc04_189 - 0x01;
				uint16 wArg04_194 = (word16) dwArg04;
				Eq_1704 wArg06_192 = (Eq_1704) SLICE(dwArg04, word16, 16);
				wLoc04_189 = v26_52;
				if (v26_52 == 0x00 || fn0800_2B51(dx_26, ds, dwArg0C, wArg08, dwArg04) != 0x00)
					break;
				Eq_12 dx_105;
				dwArg04 = SEQ(dx_105, fn0800_4B26((uint32) wArg08, wArg04_194, wArg06_192, out dx_105));
				dx_26 = dx_105;
			}
		}
	}
}

// 0800:2D0A: Register ci16 fn0800_2D0A(Stack Eq_1663 ptrArg02)
// Called from:
//      fn0800_2D94
ci16 fn0800_2D0A(Eq_1663 ptrArg02)
{
	byte * ptrLoc08_177;
	ci16 cx_114;
	ci16 ax_29;
	if (ptrArg02.u1->w0000 < 0x00)
	{
		word16 cx_33 = ptrArg02.u1->t0006.u2 + (ptrArg02.u1)->w0000;
		cx_114 = cx_33 + 0x01;
		ax_29 = cx_33 + 0x01;
	}
	else
	{
		ci16 ax_24 = ptrArg02.u1->w0000;
		ax_29 = ax_24;
		cx_114 = ax_24;
	}
	ci16 wLoc04_119 = ax_29;
	if ((ptrArg02.u1->w0002 & 0x40) == 0x00)
	{
		Eq_169 ax_53;
		ax_53.u0 = ptrArg02.u1->t000C.u0;
		Eq_1704 dx_52 = (Eq_1704) ptrArg02.u1->t000E.ptr0000;
		Eq_169 wLoc08_122 = ax_53;
		byte * ptrLoc08_123 = SEQ(dx_52, ax_53);
		if (ptrArg02.u1->w0000 < 0x00)
		{
			while (true)
			{
				--cx_114;
				if (cx_114 == 0x00)
					break;
				Eq_169 v23_90 = wLoc08_122 - 0x01;
				wLoc08_122 = v23_90;
				if (*SEQ(dx_52, v23_90) == 0x0A)
					++wLoc04_119;
			}
		}
		else
		{
			while (true)
			{
				word16 wLoc08_124 = (word16) ptrLoc08_177;
				word16 wLoc06_148 = SLICE(ptrLoc08_177, word16, 16);
				--cx_114;
				if (cx_114 == 0x00)
					break;
				ptrLoc08_123 = SEQ(wLoc06_148, wLoc08_124 + 0x01);
				ptrLoc08_177 = ptrLoc08_123;
				if (*ptrLoc08_177 == 0x0A)
					++wLoc04_119;
			}
		}
	}
	return wLoc04_119;
}

// 0800:2D94: void fn0800_2D94(Register Eq_12 ds, Stack Eq_1663 ptrArg04, Stack (ptr32 int32) dwArg08, Stack word16 wArg0C)
// Called from:
//      fn0800_3492
void fn0800_2D94(Eq_12 ds, Eq_1663 ptrArg04, int32 * dwArg08, word16 wArg0C)
{
	word16 dx_109;
	if (fn0800_264B(ds, ptrArg04) == 0x00)
	{
		if (wArg0C == 0x01 && (ptrArg04.u1)->w0000 > 0x00)
			dwArg08 -= (uint32) fn0800_2D0A(ptrArg04);
		ptrArg04.u1->w0002 &= ~0x01A0;
		ptrArg04.u1->w0000 = 0x00;
		Eq_169 ax_88;
		ax_88.u0 = ptrArg04.u1->t0008.u0;
		ptrArg04.u1->t000E.ptr0000 = ptrArg04.u1->t000A.ptr0000;
		ptrArg04.u1->t000C.u0 = (int16) ax_88;
		word16 ax_106 = fn0800_1FEB(ds, (int16) ptrArg04.u1->b0004, dwArg08, (byte) wArg0C, out dx_109);
		if (dx_109 != ~0x00 || ax_106 != ~0x00)
			;
	}
}

// 0800:302B: void fn0800_302B(Register Eq_716 cx, Register Eq_716 dx, Register Eq_716 bx, Register Eq_12 ds, Stack segptr32 dwArg04)
// Called from:
//      main
void fn0800_302B(Eq_716 cx, Eq_716 dx, Eq_716 bx, Eq_12 ds, segptr32 dwArg04)
{
	mp16 fp;
	fn0800_209B(cx, dx, bx, ds, fp + 8, dwArg04);
}

// 0800:304A: Register word16 fn0800_304A(Register Eq_12 ds, Stack uint8 bArg04, Stack Eq_1663 ptrArg06)
// Called from:
//      fn0800_321F
word16 fn0800_304A(Eq_12 ds, uint8 bArg04, Eq_1663 ptrArg06)
{
	--ptrArg06.u1->w0000;
	return fn0800_306C(ds, bArg04, ptrArg06);
}

// 0800:306C: Register uint16 fn0800_306C(Register Eq_12 ds, Stack uint8 bArg04, Stack Eq_1663 ptrArg06)
// Called from:
//      fn0800_304A
//      fn0800_321F
//      fn0800_3431
uint16 fn0800_306C(Eq_12 ds, uint8 bArg04, Eq_1663 ptrArg06)
{
	Mem17[ds:22564:byte] = bArg04;
	if (ptrArg06.u1->w0000 < ~0x00)
	{
		++ptrArg06.u1->w0000;
		Eq_1704 dx_265 = (Eq_1704) ptrArg06.u1->t000E.ptr0000;
		Eq_169 si_266;
		si_266.u0 = ptrArg06.u1->t000C.u0;
		ptrArg06.u1->t000C.u0 = (int16) (ptrArg06.u1->t000C.u0 + 0x01);
		Mem271[dx_265:si_266 + 0x00:byte] = Mem268[ds:22564:byte];
		if ((ptrArg06.u1->w0002 & 0x08) == 0x00 || Mem271[ds:22564:byte] != 0x0A && Mem271[ds:22564:byte] != 0x0D || fn0800_264B(ds, ptrArg06) == 0x00)
			goto l0800_31FE;
		goto l0800_31F9;
	}
	if ((ptrArg06.u1->w0002 & 0x90) != 0x00 || ((ptrArg06.u1)->w0002 & 0x02) == 0x00)
	{
		ptrArg06.u1->w0002 |= 0x10;
		goto l0800_31F9;
	}
	ptrArg06.u1->w0002 |= 0x0100;
	uint16 ax_313;
	if (ptrArg06.u1->t0006.u2 != 0x00)
	{
		if (ptrArg06.u1->w0000 != 0x00 && fn0800_264B(ds, ptrArg06) != 0x00)
			goto l0800_31F9;
		ptrArg06.u1->w0000 = -ptrArg06.u1->t0006.u2;
		Eq_1704 dx_201 = (Eq_1704) ptrArg06.u1->t000E.ptr0000;
		Eq_169 si_202;
		si_202.u0 = ptrArg06.u1->t000C.u0;
		ptrArg06.u1->t000C.u0 = (int16) (ptrArg06.u1->t000C.u0 + 0x01);
		Mem208[dx_201:si_202 + 0x00:byte] = Mem204[ds:22564:byte];
		if ((ptrArg06.u1->w0002 & 0x08) == 0x00 || Mem208[ds:22564:byte] != 0x0A && Mem208[ds:22564:byte] != 0x0D || fn0800_264B(ds, ptrArg06) == 0x00)
		{
l0800_31FE:
			ax_313 = CONVERT(Mem316[ds:22564:byte], uint8, uint16);
			return ax_313;
		}
	}
	else
	{
		if (((*((word32) ds + 8566))[(int16) ptrArg06.u1->b0004] & 0x0800) != 0x00)
		{
			word16 dx_480;
			fn0800_1FEB(ds, (int16) ptrArg06.u1->b0004, 0x00, 0x02, out dx_480);
		}
		if ((Mem83[ds:22564:byte] != 0x0A || (((ptrArg06.u1)->w0002 & 0x40) != 0x00 || fn0800_3DF9(ds, (int16) (ptrArg06.u1)->b0004, SEQ(ds, 9596), 0x01) == 0x01)) && fn0800_3DF9(ds, (int16) (ptrArg06.u1)->b0004, SEQ(ds, 22564), 0x01) == 0x01 || ((ptrArg06.u1)->w0002 & 0x0200) != 0x00)
			goto l0800_31FE;
		ptrArg06.u1->w0002 |= 0x10;
	}
l0800_31F9:
	ax_313 = ~0x00;
	return ax_313;
}

// 0800:321F: Register Eq_12 fn0800_321F(Register Eq_12 ds, Stack Eq_1663 ptrArg02, Stack Eq_12 wArg06, Stack Eq_170 ptrArg08)
// Called from:
//      fn0800_3431
Eq_12 fn0800_321F(Eq_12 ds, Eq_1663 ptrArg02, Eq_12 wArg06, Eq_170 ptrArg08)
{
	Eq_170 ptrArg08_539;
	if ((ptrArg02.u1->w0002 & 0x08) != 0x00)
	{
		Eq_12 wArg06_546 = wArg06;
		Eq_170 ptrArg08_690;
		do
		{
			word16 wArg08_553 = (word16) ptrArg08_690;
			word16 wArg0A_604 = SLICE(ptrArg08_690, word16, 16);
			--wArg06_546;
			if (wArg06_546 == 0x00)
				goto l0800_3426;
			ptrArg08_539 = SEQ(wArg0A_604, wArg08_553 + 0x01);
			ptrArg08_690 = ptrArg08_539;
		} while (fn0800_306C(ds, *ptrArg08_690.u1, ptrArg02) != ~0x00);
		goto l0800_3422;
	}
	Eq_12 ax_437;
	if ((ptrArg02.u1->w0002 & 0x40) == 0x00)
	{
		ptrArg08_539 = ptrArg08;
		if (ptrArg02.u1->t0006.u2 != 0x00)
		{
			Eq_12 wArg06_532 = wArg06;
			uint16 ax_364;
			do
			{
				word16 wArg08_540 = (word16) ptrArg08_539;
				word16 wArg0A_601 = SLICE(ptrArg08_539, word16, 16);
				--wArg06_532;
				if (wArg06_532 == 0x00)
					goto l0800_3426;
				ci16 v25_341 = ptrArg02.u1->w0000 + 0x01;
				ptrArg02.u1->w0000 = v25_341;
				if (v25_341 < 0x00)
				{
					Eq_1704 dx_377 = (Eq_1704) ptrArg02.u1->t000E.ptr0000;
					Eq_169 si_378;
					si_378.u0 = ptrArg02.u1->t000C.u0;
					ptrArg02.u1->t000C.u0 = (int16) (ptrArg02.u1->t000C.u0 + 0x01);
					uint8 al_387 = (uint8) *ptrArg08_539.u1;
					dx_377->*si_378.u2 = (char) al_387;
					ax_364 = (uint16) al_387;
					ptrArg08_539 = SEQ(wArg0A_601, wArg08_540 + 0x01);
				}
				else
				{
					ax_364 = fn0800_304A(ds, *ptrArg08_539.u1, ptrArg02);
					ptrArg08_539 = SEQ(wArg0A_601, wArg08_540 + 0x01);
				}
			} while (ax_364 != ~0x00);
			goto l0800_3422;
		}
		if (fn0800_35B7(ds, (int16) ptrArg02.u1->b0004, ptrArg08, wArg06) != wArg06)
			goto l0800_3422;
	}
	else if (ptrArg02.u1->t0006.u2 == 0x00)
	{
		if (((*((word32) ds + 8566))[(int16) ptrArg02.u1->b0004] & 0x0800) != 0x00)
		{
			word16 dx_688;
			fn0800_1FEB(ds, (int16) ptrArg02.u1->b0004, 0x00, 0x02, out dx_688);
		}
		if (fn0800_3DF9(ds, (int16) ptrArg02.u1->b0004, ptrArg08, wArg06) != wArg06)
			goto l0800_3422;
	}
	else if (ptrArg02.u1->t0006.u2 < wArg06)
	{
		if (ptrArg02.u1->w0000 != 0x00 && fn0800_264B(ds, ptrArg02) != 0x00)
			goto l0800_3422;
		if (((*((word32) ds + 8566))[(int16) ptrArg02.u1->b0004] & 0x0800) != 0x00)
		{
			word16 dx_689;
			fn0800_1FEB(ds, (int16) ptrArg02.u1->b0004, 0x00, 0x02, out dx_689);
		}
		if (fn0800_3DF9(ds, (int16) ptrArg02.u1->b0004, ptrArg08, wArg06) != wArg06)
		{
l0800_3422:
			ax_437.u0 = 0x00;
			return ax_437;
		}
	}
	else
	{
		if ((char *) &wArg06.u1->t0000.u0 + (ptrArg02.u1)->w0000 >= 0x00)
		{
			if (ptrArg02.u1->w0000 == 0x00)
				ptrArg02.u1->w0000 = ~0x00 - ((ptrArg02.u1)->t0006).u2;
			else if (fn0800_264B(ds, ptrArg02) != 0x00)
				goto l0800_3422;
		}
		fn0800_1A99(ptrArg02.u1->t000C.u2, ptrArg08, wArg06);
		ptrArg02.u1->w0000 = (ci16) ((char *) &wArg06.u1->t0000.u0 + (ptrArg02.u1)->w0000);
		ptrArg02.u1->t000C.u0 = (int16) ((char *) &wArg06.u1->t0000.u0 + ((ptrArg02.u1)->t000C).u0);
	}
l0800_3426:
	ax_437 = wArg06;
	return ax_437;
}

// 0800:3431: void fn0800_3431(Register Eq_12 ds, Stack Eq_170 dwArg04)
// Called from:
//      fn1BC2_003A
void fn0800_3431(Eq_12 ds, Eq_170 dwArg04)
{
	if (dwArg04 != 0x00)
	{
		Eq_12 ax_28 = fn0800_1C56(dwArg04);
		if (fn0800_321F(ds, SEQ(ds, 0x1DA0), ax_28, dwArg04) == ax_28)
			fn0800_306C(ds, 0x0A, SEQ(ds, 0x1DA0)) == 0x0A;
	}
}

// 0800:3492: Register word16 fn0800_3492(Register Eq_12 ds, Stack Eq_1663 ptrArg04, Stack cui16 wArg08, Stack cui16 wArg0A, Stack ci16 wArg0C, Stack Eq_12 wArg0E, Register out Eq_12 dsOut)
// Called from:
//      fn0800_2983
word16 fn0800_3492(Eq_12 ds, Eq_1663 ptrArg04, cui16 wArg08, cui16 wArg0A, ci16 wArg0C, Eq_12 wArg0E, union Eq_12 & dsOut)
{
	cui16 dx_151;
	mp16 fp;
	word16 wArg04_221 = (word16) ptrArg04;
	struct Eq_3112 Eq_3215::* bp_147 = fp - 2;
	word16 ax_196;
	if (ptrArg04.u1->w0012 == wArg04_221 && (wArg0C <= 0x02 && wArg0E <= 0x7FFF))
	{
		if (Mem14[ds:9600:word16] == 0x00 && wArg04_221 == 0x1DA0)
			Mem39[ds:9600:word16] = 0x01;
		else if (Mem14[ds:9598:word16] == 0x00 && wArg04_221 == 0x1D8C)
			Mem38[ds:9598:word16] = 0x01;
		if (ptrArg04.u1->w0000 != 0x00)
			fn0800_2D94(ds, ptrArg04, 0x00, 0x01);
		word16 wArg04_242 = (word16) ptrArg04;
		Eq_1704 wArg06_243 = (Eq_1704) SLICE(ptrArg04, word16, 16);
		if ((ptrArg04.u1->w0002 & 0x04) != 0x00)
			fn0800_4648(ds, ptrArg04.u1->t000A.ptr0000, out ds);
		ptrArg04.u1->w0002 &= ~0x0C;
		ptrArg04.u1->t0006.u2 = (byte Eq_4085::*) 0x00;
		ptrArg04.u1->t000A.ptr0000 = (struct Eq_14041 *) wArg06_243;
		ptrArg04.u1->t0008.u0 = (int16) (wArg04_242 + 0x05);
		ptrArg04.u1->t000E.ptr0000 = (struct Eq_14041 *) wArg06_243;
		ptrArg04.u1->t000C.u0 = (int16) (wArg04_242 + 0x05);
		if (wArg0C != 0x02 && wArg0E > 0x00)
		{
			Mem134[ds:10002:word16] = 0x0800;
			Mem135[ds:10000:word16] = 14187;
			selector ss;
			if ((wArg08 | wArg0A) == 0x00)
			{
				cui16 ax_146 = fn0800_4752(ds, wArg0E, out dx_151, out bp_147, out ds);
				(ss->*bp_147).w000C = dx_151;
				(ss->*bp_147).w000A = ax_146;
				if ((ax_146 | dx_151) == 0x00)
					goto l0800_3581;
				struct Eq_3219 * es_bx_167 = (ss->*bp_147).ptr0006;
				es_bx_167->w0002 |= 0x04;
			}
			struct Eq_3219 * es_bx_178 = (ss->*bp_147).ptr0006;
			cui16 dx_179 = (ss->*bp_147).w000C;
			cui16 ax_180 = (ss->*bp_147).w000A;
			es_bx_178->w000E = dx_179;
			es_bx_178->w000C = ax_180;
			es_bx_178->w000A = dx_179;
			es_bx_178->w0008 = ax_180;
			es_bx_178->w0006 = (ss->*bp_147).w0010;
			if ((ss->*bp_147).w000E == 0x01)
				es_bx_178->w0002 |= 0x08;
		}
		ax_196 = 0x00;
l0800_35B3:
		dsOut = ds;
		return ax_196;
	}
	else
	{
l0800_3581:
		ax_196 = ~0x00;
		goto l0800_35B3;
	}
}

// 0800:35B7: Register Eq_12 fn0800_35B7(Register Eq_12 ds, Stack Eq_12 wArg04, Stack Eq_170 dwArg06, Stack Eq_12 wArg0A)
// Called from:
//      fn0800_264B
//      fn0800_2820
//      fn0800_321F
Eq_12 fn0800_35B7(Eq_12 ds, Eq_12 wArg04, Eq_170 dwArg06, Eq_12 wArg0A)
{
	<unknown> Eq_3352::* fp;
	Eq_12 ax_130;
	if (wArg04 >=u Mem15[ds:0x2174:word16])
		ax_130 = fn0800_1F84(ds, 0x06);
	else if (wArg0A < 0x01)
		ax_130.u0 = 0x00;
	else
	{
		if (((*((word32) ds + 8566))[wArg04] & 0x0800) != 0x00)
		{
			word16 dx_483;
			fn0800_1FEB(ds, wArg04, 0x00, 0x02, out dx_483);
		}
		if (((*((word32) ds + 8566))[wArg04] & 0x4000) == 0x00)
			ax_130 = fn0800_3DF9(ds, wArg04, dwArg06, wArg0A);
		else
		{
			(*((word32) ds + 8566))[wArg04] &= ~0x0200;
			Eq_12 wLoc0A_311 = wArg0A;
			Eq_170 ptrLoc10_326 = dwArg06;
			Eq_12 wLoc04_316;
			cup16 ax_134;
			Eq_12 v27_137;
			Eq_12 dx_187;
			Eq_12 ax_206;
			do
			{
				uint8 * ptrLoc08_479 = (uint8 *) (fp - 0x92);
				word16 wLoc08_338;
				cup16 dx_168;
				do
				{
					word16 wLoc06_330 = SLICE(ptrLoc08_479, word16, 16);
					word16 wLoc10_327 = (word16) ptrLoc10_326;
					word16 wLoc0E_394 = SLICE(ptrLoc10_326, word16, 16);
					word16 wLoc08_315 = (word16) ptrLoc08_479;
					uint8 * ptrLoc08_331 = ptrLoc08_479;
					if (wLoc0A_311 == 0x00)
					{
						Eq_12 dx_90 = wLoc08_315 - (fp - 0x92);
						wLoc04_316 = dx_90;
						if (dx_90 > 0x00)
						{
							Eq_12 ax_114 = fn0800_3DF9(ds, wArg04, fp - 0x92, dx_90);
							if (ax_114 != dx_90)
							{
								if (ax_114 != ~0x00)
								{
									ax_134 = wArg0A + ax_114;
									goto l0800_3713;
								}
								else
								{
									ax_130.u0 = ~0x00;
									goto l0800_3716;
								}
							}
						}
						ax_130 = wArg0A;
						return ax_130;
					}
					v27_137 = wLoc0A_311 - 0x01;
					wLoc0A_311 = v27_137;
					uint8 al_144 = (uint8) *ptrLoc10_326.u1;
					ptrLoc10_326 = SEQ(wLoc0E_394, wLoc10_327 + 0x01);
					if (al_144 == 0x0A)
					{
						*ptrLoc08_479 = 0x0D;
						ptrLoc08_331 = SEQ(wLoc06_330, wLoc08_315 + 0x01);
					}
					*ptrLoc08_331 = al_144;
					wLoc08_338 = (word16) ptrLoc08_331;
					word16 wLoc06_396 = SLICE(ptrLoc08_331, word16, 16);
					dx_168 = wLoc08_338 + 0x01 - (fp - 0x92);
					ptrLoc08_479 = SEQ(wLoc06_396, wLoc08_338 + 0x01);
					if (false)
						continue;
					if (false)
						break;
					ptrLoc08_479 = SEQ(wLoc06_396, wLoc08_338 + 0x01);
				} while (dx_168 < 0x80);
				dx_187 = wLoc08_338 + 0x01 - (fp - 0x92);
				wLoc04_316 = dx_187;
				ax_206 = fn0800_3DF9(ds, wArg04, fp - 0x92, dx_187);
			} while (ax_206 == dx_187);
			if (ax_206 == ~0x00)
				ax_130.u0 = ~0x00;
			else
			{
				ax_134 = (cup16) ((char *) &ax_206.u1->t0000.u0 + (wArg0A - v27_137));
l0800_3713:
				ax_130 = ax_134 - wLoc04_316;
			}
l0800_3716:
		}
	}
	return ax_130;
}

// 0800:37B4: Register Eq_12 fn0800_37B4(Register Eq_12 ds, Stack byte bArg08)
// Called from:
//      fn0800_3B14
Eq_12 fn0800_37B4(Eq_12 ds, byte bArg08)
{
	__syscall<byte>(33);
	Eq_12 ax_26 = SEQ(0x43, bArg08);
	Eq_3454 C;
	Eq_12 ax_28;
	if (!C)
	{
		Eq_12 wArg0A;
		ax_28 = wArg0A;
	}
	else
		ax_28 = fn0800_1F84(ds, ax_26);
	return ax_28;
}

// 0800:37D5: void fn0800_37D5(Register int8 al, Register Eq_12 ds, Stack Eq_12 wArg04)
// Called from:
//      fn0800_255E
//      fn0800_3B14
void fn0800_37D5(int8 al, Eq_12 ds, Eq_12 wArg04)
{
	Eq_12 ax_20 = SEQ(0x3E, al);
	if (!msdos_close_file(wArg04))
		(*((word32) ds + 8566))[wArg04] = 0x00;
	else
		fn0800_1F84(ds, ax_20);
}

// 0800:3808: Register Eq_12 fn0800_3808(Register Eq_12 ds, Stack Eq_12 wArg04)
// Called from:
//      fn0800_39CD
Eq_12 fn0800_3808(Eq_12 ds, Eq_12 wArg04)
{
	word16 dx_28;
	Eq_12 wLoc0C_134;
	if (wArg04 >=u Mem15[ds:0x2174:word16])
	{
		wLoc0C_134.u0 = 0x06;
		goto l0800_387D;
	}
	Eq_12 ax_152;
	if (((*((word32) ds + 8566))[wArg04] & 0x0200) != 0x00)
	{
		ax_152.u0 = 0x01;
		return ax_152;
	}
	Eq_12 ax_26;
	ax_26.u0 = 0x4400;
	byte dl_30 = (byte) dx_28;
	if (!msdos_ioctl_get_device_info(wArg04, out dx_28))
	{
		if ((dl_30 & 0x80) != 0x00)
		{
l0800_3878:
			ax_152.u0 = 0x00;
			return ax_152;
		}
		int32 * dx_ax_42;
		ax_26 = (word16) dx_ax_42;
		if (!msdos_set_file_position(wArg04, 0x00000000<p32>, 0x01, out dx_ax_42))
		{
			int32 * dx_ax_57;
			ax_26 = (word16) dx_ax_57;
			cup16 dx_61 = SLICE(dx_ax_57, word16, 16);
			if (!msdos_set_file_position(wArg04, 0x00000000<p32>, 0x02, out dx_ax_57))
			{
				int32 * dx_ax_70;
				ax_26 = (word16) dx_ax_70;
				cup16 dx_78 = SLICE(dx_ax_70, word16, 16);
				if (!msdos_set_file_position(wArg04, dx_ax_42, 0x00, out dx_ax_70))
				{
					if (dx_78 >= dx_61 && (dx_78 > dx_61 || ax_26 >= ax_26))
					{
						ax_152.u0 = 0x01;
						return ax_152;
					}
					goto l0800_3878;
				}
			}
		}
	}
	wLoc0C_134 = ax_26;
l0800_387D:
	ax_152 = fn0800_1F84(ds, wLoc0C_134);
	return ax_152;
}

// 0800:38EE: void fn0800_38EE(Register Eq_12 ds)
// Called from:
//      fn0800_3933
//      fn0800_39CD
void fn0800_38EE(Eq_12 ds)
{
	word16 wLoc08_77 = 0x32;
	Eq_1663 ptrLoc06_82 = SEQ(ds, 0x1D8C);
	while (true)
	{
		word16 wLoc04_83 = SLICE(ptrLoc06_82, word16, 16);
		word16 wLoc06_88 = (word16) ptrLoc06_82;
		--wLoc08_77;
		if (wLoc08_77 == 0x00)
			break;
		if ((ptrLoc06_82.u1->w0002 & 0x0300) == 0x0300)
			fn0800_264B(ds, ptrLoc06_82);
		ptrLoc06_82 = SEQ(wLoc04_83, wLoc06_88 + 0x14);
	}
}

// 0800:3933: Register word16 fn0800_3933(Register Eq_12 ds, Stack Eq_1663 ptrArg02)
// Called from:
//      fn0800_39CD
word16 fn0800_3933(Eq_12 ds, Eq_1663 ptrArg02)
{
	if ((ptrArg02.u1->w0002 & 0x0200) != 0x00)
		fn0800_38EE(ds);
	Eq_12 v15_38;
	v15_38.u2 = ptrArg02.u1->t0006.u2;
	Eq_1704 dx_42 = (Eq_1704) ptrArg02.u1->t000A.ptr0000;
	Eq_169 ax_43;
	ax_43.u0 = ptrArg02.u1->t0008.u0;
	ptrArg02.u1->t000E.ptr0000 = (struct Eq_14041 *) dx_42;
	ptrArg02.u1->t000C.u0 = (int16) ax_43;
	ci16 ax_55 = fn0800_3D28(ds, (int16) ptrArg02.u1->b0004, SEQ(dx_42, ax_43), v15_38);
	ptrArg02.u1->w0000 = ax_55;
	word16 ax_101;
	if (ax_55 > 0x00)
	{
		ptrArg02.u1->w0002 &= ~0x20;
		ax_101 = 0x00;
	}
	else
	{
		if (ptrArg02.u1->w0000 == 0x00)
			ptrArg02.u1->w0002 = ptrArg02.u1->w0002 & 65151 | 0x20;
		else
		{
			ptrArg02.u1->w0000 = 0x00;
			ptrArg02.u1->w0002 |= 0x10;
		}
		ax_101 = ~0x00;
	}
	return ax_101;
}

// 0800:39AF: Register word16 fn0800_39AF(Register Eq_12 ds, Stack Eq_1663 ptrArg04)
// Called from:
//      fn0800_2B51
word16 fn0800_39AF(Eq_12 ds, Eq_1663 ptrArg04)
{
	++ptrArg04.u1->w0000;
	return fn0800_39CD(ds, ptrArg04);
}

// 0800:39CD: Register uint16 fn0800_39CD(Register Eq_12 ds, Stack Eq_1663 ptrArg04)
// Called from:
//      fn0800_39AF
uint16 fn0800_39CD(Eq_12 ds, Eq_1663 ptrArg04)
{
	uint16 ax_223;
	if (ptrArg04 != 0x00)
	{
		if (ptrArg04.u1->w0000 > 0x00)
			--ptrArg04.u1->w0000;
		else
		{
			if (ptrArg04.u1->w0000 < 0x00 || (((ptrArg04.u1)->w0002 & 0x0110) != 0x00 || ((ptrArg04.u1)->w0002 & 0x01) == 0x00))
			{
				ptrArg04.u1->w0002 |= 0x10;
				goto l0800_3AA7;
			}
			ptrArg04.u1->w0002 |= 0x80;
			if (ptrArg04.u1->t0006.u2 == 0x00)
			{
				do
				{
					if ((ptrArg04.u1->w0002 & 0x0200) != 0x00)
						fn0800_38EE(ds);
					if (fn0800_3D28(ds, (int16) ptrArg04.u1->b0004, SEQ(ds, 22566), 0x01) == 0x00)
					{
						if (fn0800_3808(ds, (int16) ptrArg04.u1->b0004) != 0x01)
							ptrArg04.u1->w0002 |= 0x10;
						else
							ptrArg04.u1->w0002 = ptrArg04.u1->w0002 & 65151 | 0x20;
						goto l0800_3AA7;
					}
				} while (Mem87[ds:22566:byte] == 0x0D && ((ptrArg04.u1)->w0002 & 0x40) == 0x00);
				ptrArg04.u1->w0002 &= ~0x20;
				ax_223 = CONVERT(Mem121[ds:22566:byte], uint8, uint16);
				return ax_223;
			}
			if (fn0800_3933(ds, ptrArg04) != 0x00)
				goto l0800_3AA7;
			--ptrArg04.u1->w0000;
		}
		Eq_1704 dx_215 = (Eq_1704) ptrArg04.u1->t000E.ptr0000;
		Eq_169 si_216;
		si_216.u0 = ptrArg04.u1->t000C.u0;
		ptrArg04.u1->t000C.u0 = (int16) (ptrArg04.u1->t000C.u0 + 0x01);
		ax_223 = (uint16) (dx_215->*si_216.u2);
		return ax_223;
	}
	else
	{
l0800_3AA7:
		ax_223 = ~0x00;
		return ax_223;
	}
}

// 0800:3ADF: Register Eq_12 fn0800_3ADF(Register Eq_12 ds, Stack cui16 wArg02, Stack (ptr32 char) ptrArg04)
// Called from:
//      fn0800_3B14
Eq_12 fn0800_3ADF(Eq_12 ds, cui16 wArg02, char * ptrArg04)
{
	Eq_12 ax_23;
	if (msdos_create_truncate_file(ptrArg04, wArg02, out ax_23))
		ax_23 = fn0800_1F84(ds, ax_23);
	return ax_23;
}

// 0800:3AFE: void fn0800_3AFE(Register Eq_12 ds, Stack Eq_12 wArg02)
// Called from:
//      fn0800_3B14
void fn0800_3AFE(Eq_12 ds, Eq_12 wArg02)
{
	word16 ax_22;
	msdos_write_file(wArg02, 0x00, SEQ(ds, 0x00), out ax_22);
}

// 0800:3B14: Register byte fn0800_3B14(Register Eq_12 ds, Stack (ptr32 char) dwArg04, Stack cui16 wArg08, Stack cui16 wArg0A)
// Called from:
//      fn0800_2983
byte fn0800_3B14(Eq_12 ds, char * dwArg04, cui16 wArg08, cui16 wArg0A)
{
	if ((wArg08 & 0xC000) == 0x00)
		wArg08 |= Mem15[ds:8666:word16] & 0xC000;
	int16 ax_30 = Mem29[ds:0x7E:word16];
	cui16 ax_47 = fn0800_37B4(ds, 0x00);
	cui16 wLoc04_417 = ax_47;
	Eq_12 wLoc10_429;
	if (ax_47 == ~0x00 && Mem52[ds:8680:word16] != 0x02)
	{
		wLoc10_429 = Mem52[ds:8680:word16];
		goto l0800_3BBC;
	}
	Mem62[ds:0x7E:word16] = ax_30;
	Eq_12 wLoc0A_443;
	if ((wArg08 & 0x0100) != 0x00)
	{
		cui16 v20_68 = wArg0A & Mem62[ds:8668:word16];
		if ((v20_68 & 0x0180) == 0x00)
			fn0800_1F84(ds, 0x01);
		Eq_12 ax_375;
		if (ax_47 != ~0x00)
		{
			if ((wArg08 & 0x0400) != 0x00)
			{
				wLoc10_429.u0 = 0x50;
l0800_3BBC:
				ax_375 = fn0800_1F84(ds, wLoc10_429);
				return (byte) ax_375;
			}
			goto l0800_3BE6;
		}
		cui16 ax_105;
		if ((v20_68 & 0x80) != 0x00)
			ax_105 = 0x00;
		else
			ax_105 = 0x01;
		wLoc04_417 = ax_105;
		if ((wArg08 & 0xF0) != 0x00)
		{
			Eq_12 ax_155 = fn0800_3ADF(ds, 0x00, dwArg04);
			wLoc0A_443 = ax_155;
			int8 al_171 = (byte) ax_155;
			if (ax_155 >= 0x00)
			{
				fn0800_37D5(al_171, ds, ax_155);
				goto l0800_3BE6;
			}
		}
		else
		{
			Eq_12 ax_130 = fn0800_3ADF(ds, ax_105, dwArg04);
			wLoc0A_443 = ax_130;
			if (ax_130 >= 0x00)
			{
l0800_3C6F:
				if (wLoc0A_443 >= 0x00)
				{
					Mem327[ds:10010:word16] = 0x0800;
					Mem328[ds:10008:word16] = 0x1F2F;
					cui16 ax_333;
					if ((wArg08 & 0x0300) != 0x00)
						ax_333 = 0x1000;
					else
						ax_333 = 0x00;
					cui16 ax_344 = ax_333 | wArg08 & ~0x0700;
					cui16 ax_353;
					if ((wLoc04_417 & 0x01) != 0x00)
						ax_353 = 0x00;
					else
						ax_353 = 0x0100;
					(*((word32) ds + 8566))[wLoc0A_443] = ax_344 | ax_353;
				}
				goto l0800_3CB3;
			}
		}
l0800_3CB3:
		ax_375 = wLoc0A_443;
		return (byte) ax_375;
	}
	else
	{
l0800_3BE6:
		Eq_12 ax_195 = fn0800_3CBC(ds, dwArg04, wArg08);
		wLoc0A_443 = ax_195;
		if (ax_195 >= 0x00)
		{
			if ((fn0800_3E55(ds, 0x00) & 0x80) != 0x00)
			{
				cui16 v27_254 = wArg08 | 0x2000;
				wArg08 = v27_254;
				if ((v27_254 & 0x8000) != 0x00)
					fn0800_3E55(ds, 0x01);
			}
			else if ((wArg08 & 0x0200) != 0x00)
				fn0800_3AFE(ds, ax_195);
			if ((wLoc04_417 & 0x01) != 0x00 && ((wArg08 & 0x0100) != 0x00 && (wArg08 & 0xF0) != 0x00))
				fn0800_37B4(ds, 0x01);
		}
		goto l0800_3C6F;
	}
}

// 0800:3CBC: Register Eq_12 fn0800_3CBC(Register Eq_12 ds, Stack (ptr32 char) ptrArg04, Stack cui16 wArg08)
// Called from:
//      fn0800_3B14
Eq_12 fn0800_3CBC(Eq_12 ds, char * ptrArg04, cui16 wArg08)
{
	byte bArg08_86 = (byte) wArg08;
	byte al_16 = 0x01;
	if ((wArg08 & 0x02) == 0x00)
	{
		al_16 = 0x02;
		if ((wArg08 & 0x04) == 0x00)
			al_16 = 0x00;
	}
	Eq_12 ax_45;
	Eq_12 ax_51;
	if (!msdos_open_file(ptrArg04, al_16 | bArg08_86 & 0xF0, out ax_45))
	{
		(*((word32) ds + 8566))[ax_45] = wArg08 & ~0x4700 | 0x8000;
		ax_51 = ax_45;
	}
	else
		ax_51 = fn0800_1F84(ds, ax_45);
	return ax_51;
}

// 0800:3D28: Register Eq_12 fn0800_3D28(Register Eq_12 ds, Stack Eq_12 wArg04, Stack (ptr32 byte) ptrArg06, Stack Eq_12 wArg0A)
// Called from:
//      fn0800_3933
//      fn0800_39CD
Eq_12 fn0800_3D28(Eq_12 ds, Eq_12 wArg04, byte * ptrArg06, Eq_12 wArg0A)
{
	struct Eq_4085 * wArg08 = SLICE(ptrArg06, word16, 16);
	Eq_4087 wArg06 = (word16) ptrArg06;
	Eq_12 ax_178;
	if (wArg04 >=u Mem15[ds:0x2174:word16])
		ax_178 = fn0800_1F84(ds, 0x06);
	else if (wArg0A >= 0x01 && ((*((word32) ds + 8566))[wArg04] & 0x0200) == 0x00)
	{
		Eq_4087 di_155;
		do
		{
			Eq_12 ax_47 = fn0800_2018(ds, wArg04, ptrArg06, wArg0A);
			if (ax_47 < 0x01 || ((*((word32) ds + 8566))[wArg04] & 0x4000) == 0x00)
			{
				ax_178 = ax_47;
				return ax_178;
			}
			Eq_12 cx_122 = ax_47;
			Eq_4087 si_69 = wArg06;
			di_155 = wArg06;
			do
			{
				byte al_76 = (byte) (wArg08->*si_69);
				si_69 = (word16) si_69 + 1;
				if (al_76 == 0x1A)
				{
					word16 dx_360;
					fn0800_1FEB(ds, wArg04, (int32) -cx_122, 0x01, out dx_360);
					(*((word32) ds + 8566))[wArg04] |= 0x0200;
					goto l0800_3DF0;
				}
				if (al_76 != 0x0D)
				{
					wArg08->*di_155 = al_76;
					di_155 = (word16) di_155 + 1;
					--cx_122;
					if (cx_122 == 0x00)
						goto l0800_3DC6;
					continue;
				}
				--cx_122;
			} while (cx_122 != 0x00);
			<unknown> Eq_4172::* fp;
			fn0800_204B(ds, wArg04, fp - 5, 0x01);
			byte bLoc05;
			wArg08->*di_155 = bLoc05;
			di_155 = (word16) di_155 + 1;
l0800_3DC6:
		} while (di_155 == wArg06);
l0800_3DF0:
		ax_178 = di_155 - wArg06;
	}
	else
		ax_178.u0 = 0x00;
	return ax_178;
}

// 0800:3DF9: Register Eq_12 fn0800_3DF9(Register Eq_12 ds, Stack Eq_12 wArg04, Stack Eq_170 ptrArg06, Stack Eq_12 wArg0A)
// Called from:
//      fn0800_306C
//      fn0800_321F
//      fn0800_35B7
Eq_12 fn0800_3DF9(Eq_12 ds, Eq_12 wArg04, Eq_170 ptrArg06, Eq_12 wArg0A)
{
	Eq_12 wLoc08_78;
	Eq_12 ax_45;
	if (((*((word32) ds + 8566))[wArg04] & 0x01) != 0x00)
		wLoc08_78.u0 = 0x05;
	else
	{
		Eq_12 ax_30;
		if (!msdos_write_file(wArg04, wArg0A, ptrArg06, out ax_30))
		{
			(*((word32) ds + 8566))[wArg04] |= 0x1000;
			ax_45 = ax_30;
			return ax_45;
		}
		wLoc08_78 = ax_30;
	}
	ax_45 = fn0800_1F84(ds, wLoc08_78);
	return ax_45;
}

// 0800:3E55: Register Eq_12 fn0800_3E55(Register Eq_12 ds, Stack word16 wArg06)
// Called from:
//      fn0800_3B14
Eq_12 fn0800_3E55(Eq_12 ds, word16 wArg06)
{
	segptr32 ptrArg08;
	byte bArg06 = (byte) wArg06;
	msdos_unknown_2144();
	Eq_12 dx_39 = (word16) ptrArg08;
	Eq_12 ax_27 = SEQ(0x44, bArg06);
	Eq_4234 C;
	if (!C)
	{
		if (wArg06 == 0x00)
			ax_27 = dx_39;
	}
	else
		ax_27 = fn0800_1F84(ds, ax_27);
	return ax_27;
}

// 0800:3EB2: Sequence word32 fn0800_3EB2(Register uint16 ax, Register uint16 cx, Register uint16 dx, Register Eq_902 bx)
// Called from:
//      fn1128_4ACF
word32 fn0800_3EB2(uint16 ax, uint16 cx, uint16 dx, Eq_902 bx)
{
	uint16 ax_15 = dx;
	if (dx != 0x00)
		ax_15 = bx *16 dx;
	if (cx != 0x00)
		ax_15 = ax * cx + ax_15;
	uint32 dx_ax_43 = bx *32 ax;
	return SEQ(SLICE(dx_ax_43, word16, 16) + ax_15, (word16) dx_ax_43);
}

// 0800:3F77: Sequence uint32 fn0800_3F77(Sequence uint32 dx_ax, Register cu8 cl, Register out byte clOut)
// Called from:
//      fn0800_4A0B
uint32 fn0800_3F77(uint32 dx_ax, cu8 cl, byte & clOut)
{
	ui16 dx_10;
	byte cl_9;
	word16 ax_8 = fn0800_3F7A(dx_ax, cl, out cl_9, out dx_10);
	clOut = cl_9;
	return SEQ(dx_10, ax_8);
}

// 0800:3F7A: Register cui16 fn0800_3F7A(Sequence uint32 dx_ax, Register cu8 cl, Register out cu8 clOut, Register out ui16 dxOut)
// Called from:
//      fn0800_3F77
cui16 fn0800_3F7A(uint32 dx_ax, cu8 cl, cu8 & clOut, ui16 & dxOut)
{
	cui16 ax = (word16) dx_ax;
	if (cl >= 0x10)
	{
		clOut = cl - 0x10;
		dxOut = ax << cl - 0x10;
		return 0x00;
	}
	else
	{
		clOut = -cl + 0x10;
		ui32 dx_ax_27 = dx_ax << cl;
		dxOut = SLICE(dx_ax_27, word16, 16);
		return (word16) dx_ax_27;
	}
}

// 0800:3F98: Sequence word32 fn0800_3F98(Register uint16 ax, Register uint16 cx, Register uint16 dx, Register Eq_12 bx)
// Called from:
//      fn0800_2C70
//      fn0800_537F
word32 fn0800_3F98(uint16 ax, uint16 cx, uint16 dx, Eq_12 bx)
{
	uint16 ax_15 = dx;
	if (dx != 0x00)
		ax_15 = bx *16 dx;
	if (cx != 0x00)
		ax_15 = ax * cx + ax_15;
	uint32 dx_ax_43 = bx *32 ax;
	return SEQ(SLICE(dx_ax_43, word16, 16) + ax_15, (word16) dx_ax_43);
}

// 0800:3FAF: Register word16 fn0800_3FAF(Stack Eq_907 bArg02, Stack Eq_1146 bArg04, Stack Eq_12 wArg06, Stack Eq_12 ptrArg08, Stack Eq_902 dwArg0C, Register out word16 dxOut, Register out Eq_12 bxOut)
// Called from:
//      fn0800_209B
//      fn0800_4031
//      fn0800_4055
//      fn0800_40A5
word16 fn0800_3FAF(Eq_907 bArg02, Eq_1146 bArg04, Eq_12 wArg06, Eq_12 ptrArg08, Eq_902 dwArg0C, word16 & dxOut, union Eq_12 & bxOut)
{
	Eq_4333 fp;
	word16 wArg0A_185 = SLICE(ptrArg08, word16, 16);
	word16 wArg08_193 = (word16) ptrArg08;
	uint16 wArg0C = (word16) dwArg0C;
	Eq_4312 wArg0E = SLICE(dwArg0C, word16, 16);
	struct Eq_4314 * es_36 = SLICE(ptrArg08, selector, 16);
	byte Eq_4314::* di_124 = (word16) ptrArg08;
	cu8 bl_23 = (byte) wArg06;
	if (wArg06 > 0x24 || bl_23 < 0x02)
	{
l0800_401F:
		es_36->*di_124 = 0x00;
		dxOut = wArg0A_185;
		bxOut = wArg06;
		return wArg08_193;
	}
	uint16 ax_26 = wArg0C;
	Eq_4312 cx_28 = wArg0E;
	if (wArg0E < 0x00 && bArg04 != 0x00)
	{
		ptrArg08.u1->t0000.u1 = 0x2D;
		ui32 cx_ax_166 = -dwArg0C;
		++di_124;
		ax_26 = (word16) cx_ax_166;
		cx_28 = SLICE(cx_ax_166, word16, 16);
	}
	byte Eq_4355::* si_107 = fp - 36;
	selector ss;
	if (cx_28 != 0x00)
	{
		Eq_4312 ax_58;
		do
		{
			uint32 dx_ax_54 = (uint32) cx_28;
			uint32 dx_ax_62 = SEQ(dx_ax_54 % wArg06, ax_26);
			ss->*si_107 = (byte) (dx_ax_62 % wArg06);
			ax_58 = dx_ax_54 /u wArg06;
			cx_28 = ax_58;
			ax_26 = dx_ax_62 /u wArg06;
			++si_107;
		} while (ax_58 != 0x00);
l0800_4001:
		if (ax_26 == 0x00)
		{
			int16 cx_104 = (int16) (si_107 + (36 - fp));
			do
			{
				--si_107;
				cu8 al_111 = ss->*si_107;
				byte al_116;
				if (al_111 < 0x0A)
					al_116 = al_111 + 0x30;
				else
					al_116 = (byte) bArg02.u0 + (al_111 - 0x0A);
				es_36->*di_124 = al_116;
				++di_124;
				--cx_104;
			} while (cx_104 != 0x00);
			goto l0800_401F;
		}
	}
	uint32 dx_ax_82 = (uint32) ax_26;
	ss->*si_107 = (byte) (dx_ax_82 % wArg06);
	ax_26 = dx_ax_82 /u wArg06;
	++si_107;
	goto l0800_4001;
}

// 0800:4031: void fn0800_4031(Stack Eq_12 dwArg02, Stack uint16 wArg06)
// Called from:
//      fn0800_1D65
void fn0800_4031(Eq_12 dwArg02, uint16 wArg06)
{
	word16 dx_76;
	word16 bx_77;
	fn0800_3FAF(0x61, 0x00, 0x0A, dwArg02, (uint32) wArg06, out dx_76, out bx_77);
}

// 0800:4055: Sequence int32 fn0800_4055(Stack Eq_169 wArg04, Stack Eq_12 dwArg06, Stack Eq_12 wArg0A, Register out word16 bxOut)
// Called from:
//      fn1128_4827
//      fn1128_4979
//      fn1128_5F6B
//      fn1128_60AE
int32 fn0800_4055(Eq_169 wArg04, Eq_12 dwArg06, Eq_12 wArg0A, word16 & bxOut)
{
	word16 bx_56;
	int16 dx_57;
	word16 ax_55 = fn0800_3FAF(0x61, 0x01, wArg0A, dwArg06, (uint32) wArg04, out dx_57, out bx_56);
	bxOut = bx_56;
	return SEQ(dx_57, ax_55);
}

// 0800:40A5: void fn0800_40A5(Stack Eq_902 dwArg04, Stack Eq_12 dwArg08, Stack Eq_12 wArg0C)
// Called from:
//      fn1128_43AC
void fn0800_40A5(Eq_902 dwArg04, Eq_12 dwArg08, Eq_12 wArg0C)
{
	word16 ax_32;
	if (wArg0C == 0x0A)
		ax_32 = 0x01;
	else
		ax_32 = 0x00;
	word16 dx_91;
	word16 bx_92;
	fn0800_3FAF(0x61, (byte) ax_32, wArg0C, dwArg08, dwArg04, out dx_91, out bx_92);
}

// 0800:40D1: Register word16 fn0800_40D1(Register (ptr16 Eq_191) ds, Stack segptr32 ptrArg04)
// Called from:
//      fn1A29_00DA
word16 fn0800_40D1(struct Eq_191 * ds, segptr32 ptrArg04)
{
	struct Eq_4458 * es_163 = SLICE(ptrArg04, selector, 16);
	byte Eq_4458::* si_164 = (word16) ptrArg04;
	uint8 bl_31;
	do
	{
		bl_31 = es_163->*si_164;
		++si_164;
	} while ((ds->a25BF[(uint16) bl_31] & 0x01) != 0x00);
	ci16 bp_120 = 0x00;
	Eq_4480 dx_ax_263;
	dx_ax_263.u0 = 0x00;
	Eq_4480 dx_ax_258;
	if (bl_31 != 0x2B)
	{
		dx_ax_258.u0 = 0x00;
		if (bl_31 != 0x2D)
		{
l0800_4102:
			Mem152 = Mem19;
			uint16 ax_63 = (word16) dx_ax_258;
			Eq_4480 dx_ax_253 = dx_ax_258;
			if (bl_31 > 0x39)
			{
l0800_4136:
				word16 ax_133 = (word16) dx_ax_253;
				if (bp_120 >= 0x01)
					ax_133 = (word16) -dx_ax_253;
				return ax_133;
			}
			uint8 bl_57 = bl_31 - 0x30;
			uint16 bx_71 = (uint16) bl_57;
			dx_ax_253 = dx_ax_258;
			if (bl_57 < 0x00)
				goto l0800_4136;
			ui8 dh_75 = SLICE(ax_63 *32 0x0A, byte, 24);
			ui24 dl_ax_170 = (word24) (ax_63 *32 0x0A) + SEQ(dh_75, bx_71);
			byte dl_77 = SLICE(dl_ax_170, byte, 16);
			word16 ax_72 = (word16) dl_ax_170;
			ui16 dx_131 = SEQ(dh_75, dl_77);
			dx_ax_263 = SEQ(dx_131, ax_72);
			if (dl_77 != 0x00)
			{
				Eq_4480 dx_ax_175 = SEQ(dx_131, ax_72);
				while (true)
				{
					uint16 ax_93 = (word16) dx_ax_175;
					uint16 dx_90 = SLICE(dx_ax_175, word16, 16);
					uint8 bl_83 = es_163->*si_164;
					++si_164;
					dx_ax_253 = dx_ax_175;
					if (bl_83 > 0x39)
						break;
					uint16 bx_113 = (uint16) (bl_83 - 0x30);
					dx_ax_253 = dx_ax_175;
					if (bl_83 < 0x30)
						break;
					dx_ax_175 = SEQ(dx_90 * 0x0A, ax_93 * 0x0A) + SEQ(SLICE(ax_93 *32 0x0A, word16, 16), bx_113);
				}
				goto l0800_4136;
			}
			goto l0800_40FE;
		}
		bp_120 = 0x01;
		dx_ax_263.u0 = 0x00;
	}
l0800_40FE:
	bl_31 = es_163->*si_164;
	++si_164;
	dx_ax_258 = dx_ax_263;
	goto l0800_4102;
}

// 0800:417A: void fn0800_417A(Register Eq_12 ds)
// Called from:
//      fn0800_04AB
//      fn0800_209B
void fn0800_417A(Eq_12 ds)
{
	Mem0[ds:0x2908:word16]();
}

Eq_1704 g_t4508 = // 0800:4508
	{
		null,
	};
Eq_1704 g_t450A = // 0800:450A
	{
		null,
	};
Eq_1704 g_t450C = // 0800:450C
	{
		null,
	};
Eq_12 g_t450E = // 0800:450E
	{
		0x00
	};
// 0800:4514: Register Eq_1704 fn0800_4514(Register Eq_1704 dx)
// Called from:
//      fn0800_4648
Eq_1704 fn0800_4514(Eq_1704 dx)
{
	selector seg0800;
	if (dx != seg0800->t4508)
	{
		Eq_1704 ds_9 = Mem0[dx:0x02:selector];
		Eq_12 ds_36;
		Eq_1704 wLoc02_69;
		if (Mem0[ds_9:0x02:word16] != 0x00)
		{
			seg0800->t450A = ds_9;
l0800_4567:
			ds_36 = seg0800->t450E;
			wLoc02_69 = dx;
			return fn0800_49C8(ds_36, 0x00, wLoc02_69);
		}
		if (ds_9 != seg0800->t4508)
		{
			Mem20[0800:450A:word16] = Mem0[ds_9:0x08:word16];
			fn0800_45E8(ds_9);
			wLoc02_69 = ds_9;
			ds_36 = seg0800->t450E;
			return fn0800_49C8(ds_36, 0x00, wLoc02_69);
		}
		dx = seg0800->t4508;
	}
	seg0800->t4508 = (Eq_1704) 0x00;
	seg0800->t450A = (Eq_1704) 0x00;
	seg0800->t450C = (Eq_1704) 0x00;
	goto l0800_4567;
}

// 0800:4577: void fn0800_4577(Register Eq_1704 dx)
// Called from:
//      fn0800_4648
void fn0800_4577(Eq_1704 dx)
{
	Eq_1704 es_9 = Mem8[dx:0x02:selector];
	Mem10[dx:0x02:word16] = 0x00;
	Mem11[dx:0x08:word16] = es_9;
	Eq_1704 wLoc02_68 = dx;
	selector seg0800;
	if (dx != seg0800->t4508 && Mem11[es_9:0x02:word16] == 0x00)
	{
		Eq_4637 ax_26 = Mem11[dx:0x00:word16];
		Mem32[es_9:0x00:word16] = Mem30[es_9:0x00:word16] + ax_26;
		wLoc02_68 = es_9;
		struct Eq_4645 * dx_34 = dx + ax_26;
		if (dx_34->t0002 == 0x00)
			dx_34->t0008 = es_9;
		else
			dx_34->t0002 = es_9;
	}
	else
		fn0800_4611(dx);
	Eq_1704 ax_49 = wLoc02_68 + Mem44[wLoc02_68:0x00:word16];
	if (Mem44[ax_49:0x02:word16] != 0x00)
		return;
	Mem55[wLoc02_68:0x00:word16] = Mem44[wLoc02_68:0x00:word16] + Mem44[ax_49:0x00:word16];
	(ax_49 + Mem55[ax_49:0x00:word16])->t0002 = wLoc02_68;
	fn0800_45E8(ax_49);
}

// 0800:45E8: void fn0800_45E8(Register Eq_1704 ds)
// Called from:
//      fn0800_4514
//      fn0800_4577
//      fn0800_4752
void fn0800_45E8(Eq_1704 ds)
{
	selector seg0800;
	if (ds == Mem0[ds:0x06:word16])
		seg0800->t450C = (Eq_1704) 0x00;
	else
	{
		Eq_1704 es_10 = Mem0[ds:0x06:selector];
		Eq_1704 ds_11 = Mem0[ds:0x04:selector];
		Mem12[ds_11:0x06:word16] = es_10;
		Mem13[es_10:0x04:word16] = ds_11;
		seg0800->t450C = ds_11;
	}
}

// 0800:4611: void fn0800_4611(Register Eq_1704 ds)
// Called from:
//      fn0800_4577
void fn0800_4611(Eq_1704 ds)
{
	selector seg0800;
	Eq_1704 ax_5 = seg0800->t450C;
	if (ax_5 == 0x00)
	{
		seg0800->t450C = ds;
		Mem13[ds:0x04:word16] = ds;
		Mem14[ds:0x06:word16] = ds;
	}
	else
	{
		__cli();
		Eq_1704 es_23 = Mem21[ax_5:0x06:selector];
		Mem24[ax_5:0x06:word16] = ds;
		Mem25[ds:0x04:word16] = ax_5;
		Mem29[es_23:0x04:word16] = ds;
		Mem30[ds:0x06:word16] = es_23;
	}
}

// 0800:4648: Register Eq_1704 fn0800_4648(Register Eq_12 ds, Stack Eq_1704 wArg06, Register out Eq_12 dsOut)
// Called from:
//      fn0800_258A
//      fn0800_3492
//      fn0800_4C67
Eq_1704 fn0800_4648(Eq_12 ds, Eq_1704 wArg06, union Eq_12 & dsOut)
{
	selector seg0800;
	seg0800->t450E = ds;
	Eq_1704 dx_18 = wArg06;
	if (wArg06 != 0x00)
	{
		if (wArg06 == seg0800->t450A)
			dx_18 = fn0800_4514(wArg06);
		else
			fn0800_4577(wArg06);
	}
	dsOut = seg0800->t450E;
	return dx_18;
}

// 0800:4671: Register Eq_4637 fn0800_4671(Register Eq_4637 ax, Register out Eq_4797 cxOut, Register out Eq_1704 dxOut, Register out Eq_4797 bxOut)
// Called from:
//      fn0800_4752
Eq_4637 fn0800_4671(Eq_4637 ax, union Eq_4797 & cxOut, struct Eq_1704 & dxOut, union Eq_4797 & bxOut)
{
	word16 dx_136;
	word16 cx_135;
	selector seg0800;
	cui16 ax_17 = fn0800_4A0B(seg0800->t450E, 0x00, out cx_135, out dx_136);
	if ((ax_17 & 0x0F) != 0x00)
	{
		word16 cx_137;
		word16 dx_138;
		fn0800_4A0B(seg0800->t450E, (uint32) (0x10 - (ax_17 & 0x0F)), out cx_137, out dx_138);
	}
	word16 cx_77;
	Eq_1704 dx_78;
	if (fn0800_4A0B(seg0800->t450E, SEQ((uint16) SLICE(ax, byte, 8) >> 0x04, ax << 0x04), out cx_77, out dx_78) == ~0x00)
	{
		cxOut.u0 = <invalid>;
		dxOut = (Eq_1704) 0x00;
		bxOut.u0 = <invalid>;
		return 0x00;
	}
	else
	{
		seg0800->t4508 = dx_78;
		seg0800->t450A = dx_78;
		Mem97[dx_78:0x00:word16] = ax;
		Mem98[dx_78:0x02:word16] = dx_78;
		cxOut.u0 = <invalid>;
		dxOut = dx_78;
		bxOut.u0 = <invalid>;
		return 0x04;
	}
}

// 0800:46D5: Register Eq_4637 fn0800_46D5(Register Eq_4637 ax, Register out Eq_1704 cxOut, Register out Eq_1704 dxOut, Register out Eq_4797 bxOut)
// Called from:
//      fn0800_4752
Eq_4637 fn0800_46D5(Eq_4637 ax, struct Eq_1704 & cxOut, struct Eq_1704 & dxOut, union Eq_4797 & bxOut)
{
	Eq_1704 dx_25;
	Eq_1704 cx_104;
	selector seg0800;
	uint8 ah_9 = SLICE(ax, byte, 8);
	Eq_12 ds_17 = seg0800->t450E;
	cui16 ax_22 = fn0800_4A0B(ds_17, SEQ((uint16) ah_9 >> 0x04, ax << 0x04), out cx_104, out dx_25);
	if (ax_22 != ~0x00)
	{
		if ((ax_22 & 0x0F) == 0x00)
		{
l0800_46F8:
			Eq_1704 cx_79 = seg0800->t450A;
			seg0800->t450A = dx_25;
			Mem84[dx_25:0x00:word16] = ax;
			Mem85[dx_25:0x02:word16] = cx_79;
			cxOut = cx_79;
			dxOut = dx_25;
			bxOut.u0 = <invalid>;
			return 0x04;
		}
		word16 dx_133;
		if (fn0800_4A0B(ds_17, (uint32) (-(ax_22 & 0x0F) + 0x10), out cx_104, out dx_133) != ~0x00)
		{
			dx_25 = (Eq_1704) ((char *) &dx_25.ptr0000->t0000 + 1);
			goto l0800_46F8;
		}
	}
	cxOut = cx_104;
	dxOut = (Eq_1704) 0x00;
	bxOut.u0 = <invalid>;
	return 0x00;
}

// 0800:472F: Register Eq_4637 fn0800_472F(Register Eq_4637 ax, Register Eq_1704 dx, Register Eq_1704 ds, Register out (ptr16 Eq_4877) dxOut, Register out (ptr16 Eq_4888) bxOut)
// Called from:
//      fn0800_4752
Eq_4637 fn0800_472F(Eq_4637 ax, Eq_1704 dx, Eq_1704 ds, struct Eq_4877 & dxOut, struct Eq_4888 & bxOut)
{
	Mem10[ds:0x00:word16] = Mem0[ds:0x00:word16] - ax;
	struct Eq_4877 * dx_11 = dx + Mem10[ds:0x00:word16];
	dx_11->t0000 = ax;
	dx_11->t0002 = dx;
	struct Eq_4888 * bx_16 = dx_11 + dx_11->t0000;
	bx_16->ptr0002 = dx_11;
	dxOut = dx_11;
	bxOut = bx_16;
	return 0x04;
}

// 0800:4752: Register word16 fn0800_4752(Register Eq_12 ds, Stack Eq_12 wArg04, Register out word16 dxOut, Register out (memptr (ptr16 Eq_3215) Eq_3263) bpOut, Register out (ptr16 Eq_3265) dsOut)
// Called from:
//      fn0800_3492
//      fn0800_4C7D
word16 fn0800_4752(Eq_12 ds, Eq_12 wArg04, word16 & dxOut, struct Eq_3263 & bpOut, struct Eq_3265 & dsOut)
{
	struct Eq_3265 * ds_18;
	struct Eq_3263 Eq_3215::* bp_16;
	word16 bx_35;
	word16 dx_21;
	word16 cx_34;
	word16 ax_20 = fn0800_4765((uint32) wArg04, ds, out cx_34, out dx_21, out bx_35, out bp_16, out ds_18);
	dxOut = dx_21;
	bpOut = bp_16;
	dsOut = ds_18;
	return ax_20;
}

// 0800:475C: Register word16 fn0800_475C(Register Eq_12 ds, Stack Eq_4899 dwArg04, Register out word16 cxOut, Register out word16 dxOut, Register out word16 bxOut, Register out word16 bpOut, Register out (ptr16 Eq_4931) dsOut)
// Called from:
//      main
word16 fn0800_475C(Eq_12 ds, Eq_4899 dwArg04, word16 & cxOut, word16 & dxOut, word16 & bxOut, word16 & bpOut, struct Eq_4931 & dsOut)
{
	struct Eq_4931 * ds_15;
	word16 bp_13;
	word16 bx_19;
	word16 dx_18;
	word16 cx_14;
	word16 ax_17 = fn0800_4765(dwArg04, ds, out cx_14, out dx_18, out bx_19, out bp_13, out ds_15);
	cxOut = cx_14;
	dxOut = dx_18;
	bxOut = bx_19;
	bpOut = bp_13;
	dsOut = ds_15;
	return ax_17;
}

// 0800:4765: Register cu16 fn0800_4765(Sequence Eq_4899 dx_ax, Register Eq_12 ds, Register out cui16 cxOut, Register out Eq_1704 dxOut, Register out Eq_1704 bxOut, Register out word16 bpOut, Register out Eq_12 dsOut)
// Called from:
//      fn0800_4752
//      fn0800_475C
cu16 fn0800_4765(Eq_4899 dx_ax, Eq_12 ds, cui16 & cxOut, struct Eq_1704 & dxOut, struct Eq_1704 & bxOut, word16 & bpOut, union Eq_12 & dsOut)
{
	cu16 ax = (word16) dx_ax;
	Eq_1704 dx = (Eq_1704) SLICE(dx_ax, word16, 16);
	cui16 cx_147 = ax | dx;
	selector seg0800;
	seg0800->t450E = ds;
	byte ch_149 = SLICE(cx_147, byte, 8);
	Eq_1704 bx;
	if (cx_147 != 0x00)
	{
		cu16 dx_24 = SLICE((word32) dx_ax.u0 + 19, word16, 16);
		if (dx_24 >= 0x00 && (dx_24 & ~0x0F) == 0x00)
		{
			Eq_4637 ax_49 = SEQ(SLICE(ax + 0x13 >> 0x04, byte, 8) | (byte) dx_24 << 0x04, (byte) (ax + 0x13 >> 0x04));
			cx_147 = SEQ(ch_149, 0x04);
			if (seg0800->t4508 != 0x00)
			{
				Eq_1704 dx_60 = seg0800->t450C;
				dx = dx_60;
				if (dx_60 != 0x00)
				{
					do
					{
						if (Mem19[dx:0x00:word16] >=u ax_49)
						{
							if (Mem19[dx:0x00:word16] <=u ax_49)
							{
								fn0800_45E8(dx);
								bx = Mem19[dx:0x08:word16];
								Mem89[dx:0x02:word16] = bx;
								ax = 0x04;
							}
							else
								ax = fn0800_472F(ax_49, dx, dx, out dx, out bx);
							goto l0800_47D0;
						}
						dx = Mem19[dx:0x06:word16];
					} while (dx != dx_60);
				}
				ax = fn0800_46D5(ax_49, out cx_147, out dx, out bx);
			}
			else
				ax = fn0800_4671(ax_49, out cx_147, out dx, out bx);
		}
		else
		{
			ax = 0x00;
			dx = (Eq_1704) 0x00;
		}
	}
l0800_47D0:
	Eq_12 ds_109 = seg0800->t450E;
	cxOut = cx_147;
	dxOut = dx;
	bxOut = bx;
	word16 wArg00;
	bpOut = wArg00;
	dsOut = ds_109;
	return ax;
}

// 0800:493A: Register word16 fn0800_493A(Register Eq_12 ds, Stack uint16 wArg02, Stack Eq_1704 wArg04, Register out cu16 cxOut, Register out Eq_1704 dxOut)
// Called from:
//      fn0800_49C8
//      fn0800_4A0B
word16 fn0800_493A(Eq_12 ds, uint16 wArg02, Eq_1704 wArg04, cu16 & cxOut, struct Eq_1704 & dxOut)
{
	byte ch;
	cu16 v12_21 = wArg04 + 0x01 - Mem18[ds:122:word16];
	cu16 cx_135 = SEQ(ch, 0x06);
	Eq_1704 dx_141;
	word16 ax_127;
	if (v12_21 + 0x3F >>u 0x06 != Mem27[ds:9994:word16])
	{
		cu16 wLoc04_108 = __align(v12_21 + 0x3F, 64);
		cu16 dx_33 = Mem32[ds:0x8E:word16];
		cu16 ax_35 = __align(v12_21 + 0x3F, 64) + Mem32[ds:122:word16];
		byte al_53 = (byte) ax_35;
		if (ax_35 > dx_33)
		{
			cu16 ax_39 = dx_33 - Mem32[ds:122:word16];
			al_53 = (byte) ax_39;
			wLoc04_108 = ax_39;
		}
		Eq_1704 ax_56 = fn0800_4AEA(al_53, ds, Mem48[ds:122:word16], wLoc04_108);
		cx_135 = wLoc04_108;
		byte ch_139 = SLICE(wLoc04_108, byte, 8);
		dx_141 = ax_56;
		if (ax_56 != ~0x00)
		{
			Mem70[ds:0x8E:word16] = Mem52[ds:122:word16] + ax_56;
			Mem71[ds:0x8C:word16] = 0x00;
			ax_127 = 0x00;
l0800_49C0:
			cxOut = cx_135;
			dxOut = dx_141;
			return ax_127;
		}
		Mem80[ds:9994:word16] = wLoc04_108 >>u 0x06;
		cx_135 = SEQ(ch_139, 0x06);
	}
	Mem87[ds:0x8A:word16] = wArg04;
	Mem88[ds:0x88:word16] = wArg02;
	dx_141 = wArg04;
	ax_127 = 0x01;
	goto l0800_49C0;
}

// 0800:49C8: Register word16 fn0800_49C8(Register Eq_12 ds, Stack uint16 wArg02, Stack Eq_1704 wArg04)
// Called from:
//      fn0800_4514
word16 fn0800_49C8(Eq_12 ds, uint16 wArg02, Eq_1704 wArg04)
{
	word16 cx_115;
	word16 dx_100;
	fn0800_4BAE(wArg02, Mem14[ds:0x86:word16], wArg04, Mem14[ds:0x84:word16], out cx_115, out dx_100);
	Eq_5148 C_25;
	C_25.u0 = <invalid>;
	if (C_25)
		return dx_100;
	word16 cx_116;
	fn0800_4BAE(wArg02, Mem14[ds:0x8E:word16], wArg04, Mem14[ds:0x8C:word16], out cx_116, out dx_100);
	Eq_5148 Z_38;
	Z_38.u0 = <invalid>;
	Eq_5148 C_37;
	C_37.u0 = <invalid>;
	word16 cx_117;
	if ((Z_38 | C_37) != 0x00 || fn0800_493A(ds, wArg02, wArg04, out cx_117, out dx_100) == 0x00)
		return dx_100;
	return dx_100;
}

// 0800:4A0B: Register uint16 fn0800_4A0B(Register Eq_12 ds, Stack uint32 dwArg02, Register out word16 cxOut, Register out Eq_1704 dxOut)
// Called from:
//      fn0800_4671
//      fn0800_46D5
uint16 fn0800_4A0B(Eq_12 ds, uint32 dwArg02, word16 & cxOut, struct Eq_1704 & dxOut)
{
	Eq_1704 dx_57;
	byte ch;
	byte cl_26;
	uint32 dx_ax_134 = fn0800_3F77(CONVERT(Mem15[ds:0x8A:word16], uint16, uint32), 0x04, out cl_26) + CONVERT(Mem15[ds:0x88:word16], uint16, uint32) + dwArg02;
	cup16 ax_36 = (word16) dx_ax_134;
	ci16 dx_39 = SLICE(dx_ax_134, word16, 16);
	word16 cx_165 = SEQ(ch, cl_26);
	Eq_1704 dx_113;
	uint16 ax_114;
	if (dx_39 < 0x0F || dx_39 <= 0x0F && ax_36 <= ~0x00)
	{
		uint16 ax_54 = fn0800_4B26(dwArg02, Mem15[ds:0x88:word16], Mem15[ds:0x8A:word16], out dx_57);
		word16 dx_193;
		fn0800_4BAE(ax_54, Mem63[ds:0x86:word16], dx_57, Mem63[ds:0x84:word16], out cx_165, out dx_193);
		Eq_5148 C_71;
		C_71.u0 = <invalid>;
		if (!C_71)
		{
			word16 dx_194;
			fn0800_4BAE(ax_54, Mem63[ds:0x8E:word16], dx_57, Mem63[ds:0x8C:word16], out cx_165, out dx_194);
			Eq_5148 Z_84;
			Z_84.u0 = <invalid>;
			Eq_5148 C_83;
			C_83.u0 = <invalid>;
			if ((Z_84 | C_83) == 0x00)
			{
				Eq_1704 dx_87 = Mem63[ds:0x8A:word16];
				uint16 ax_88 = Mem63[ds:0x88:word16];
				word16 dx_195;
				if (fn0800_493A(ds, ax_54, dx_57, out cx_165, out dx_195) != 0x00)
				{
					dx_113 = dx_87;
					ax_114 = ax_88;
l0800_4A94:
					cxOut = cx_165;
					dxOut = dx_113;
					return ax_114;
				}
			}
		}
	}
	dx_113 = (Eq_1704) ~0x00;
	ax_114 = ~0x00;
	goto l0800_4A94;
}

// 0800:4A9A: Sequence word32 fn0800_4A9A(Register Eq_12 ds)
// Called from:
//      main
word32 fn0800_4A9A(Eq_12 ds)
{
	up32 dx_ax_95 = fn0800_4B86(Mem18[ds:0x8C:word16], Mem18[ds:0x8A:word16], Mem18[ds:0x8E:word16], Mem18[ds:0x88:word16]);
	cui16 ax_24 = (word16) dx_ax_95;
	word16 wLoc04_74 = SLICE(dx_ax_95, word16, 16);
	cui16 wLoc06_75 = ax_24;
	if (dx_ax_95 > 0x10)
	{
		wLoc06_75 = ax_24 - 0x10;
		wLoc04_74 = SLICE(dx_ax_95 - 0x10, word16, 16);
	}
	return SEQ(wLoc04_74, wLoc06_75 & ~0x0F);
}

// 0800:4AEA: Register word16 fn0800_4AEA(Register byte al, Register Eq_12 ds, Stack (ptr16 Eq_5035) psegArg04, Stack cu16 wArg06)
// Called from:
//      fn0800_493A
word16 fn0800_4AEA(byte al, Eq_12 ds, struct Eq_5035 * psegArg04, cu16 wArg06)
{
	Eq_12 ax_24 = SEQ(0x4A, al);
	word16 bx_18;
	word16 ax_35;
	if (!msdos_resize_memory_block(psegArg04, wArg06, out bx_18))
		ax_35 = ~0x00;
	else
	{
		fn0800_1F84(ds, ax_24);
		ax_35 = bx_18;
	}
	return ax_35;
}

// 0800:4B26: Register uint16 fn0800_4B26(Sequence uint32 cx_bx, Register uint16 ax, Register Eq_1704 dx, Register out word16 dxOut)
// Called from:
//      fn0800_2C70
//      fn0800_4A0B
uint16 fn0800_4B26(uint32 cx_bx, uint16 ax, Eq_1704 dx, word16 & dxOut)
{
	word16 dx_11;
	uint16 ax_9 = fn0800_4B29(cx_bx, ax, dx, out dx_11);
	dxOut = dx_11;
	return ax_9;
}

// 0800:4B29: Register uint16 fn0800_4B29(Sequence uint32 cx_bx, Register uint16 ax, Register Eq_1704 dx, Register out word16 dxOut)
// Called from:
//      fn0800_4B26
uint16 fn0800_4B29(uint32 cx_bx, uint16 ax, Eq_1704 dx, word16 & dxOut)
{
	ci16 cx = SLICE(cx_bx, word16, 16);
	word16 bx = (word16) cx_bx;
	byte dh_24 = SLICE(dx, byte, 8);
	byte dl_35 = (byte) dx;
	byte cl_20 = (byte) cx;
	if (cx >= 0x00)
	{
		cu16 ax_13 = ax + bx;
		byte al_29 = (byte) ax_13;
		if (ax_13 < 0x00)
		{
			dh_24 = SLICE((char *) &dx.ptr0000->t0008.ptr0000 + 0x0FF8, byte, 8);
			dl_35 = (byte) dx;
		}
		dxOut = SEQ(dh_24 + (cl_20 << 0x04), dl_35) + (ax_13 >> 0x04);
		return SEQ(SLICE(ax_13 >> 0x04, byte, 8), al_29) & 0x0F;
	}
	else
	{
		ui32 cx_bx_83 = ~cx_bx;
		word16 bx_49 = (word16) cx_bx_83 + 0x01;
		byte cl_60 = SLICE(cx_bx_83 + 0x01, byte, 16);
		cu16 ax_54 = ax - bx_49;
		byte al_69 = (byte) ax_54;
		if (ax_54 < 0x00)
			dx -= 0x1000;
		dxOut = dx - SEQ(cl_60 << 0x04, 0x00) + (ax_54 >> 0x04);
		return SEQ(SLICE(ax_54 >> 0x04, byte, 8), al_69) & 0x0F;
	}
}

// 0800:4B86: Sequence word32 fn0800_4B86(Register uint16 ax, Register Eq_1704 cx, Register cu16 dx, Register uint16 bx)
// Called from:
//      fn0800_4A9A
word32 fn0800_4B86(uint16 ax, Eq_1704 cx, cu16 dx, uint16 bx)
{
	word16 dx_12;
	return SEQ(dx_12, fn0800_4B89(ax, cx, dx, bx, out dx_12));
}

// 0800:4B89: Register uint16 fn0800_4B89(Register uint16 ax, Register Eq_1704 cx, Register cu16 dx, Register uint16 bx, Register out int16 dxOut)
// Called from:
//      fn0800_4B86
uint16 fn0800_4B89(uint16 ax, Eq_1704 cx, cu16 dx, uint16 bx, int16 & dxOut)
{
	bcu8 dh = SLICE(dx, byte, 8);
	uint24 ch_dx_49 = SEQ(dh >> 0x04, dx << 0x04) + (uint24) ax - (SEQ(SLICE(cx, byte, 8) >> 0x04, bx) + (uint24) (cx << 0x04));
	dxOut = (int16) SLICE(ch_dx_49, byte, 16);
	return (word16) ch_dx_49;
}

// 0800:4BAE: FlagGroup ui32 fn0800_4BAE(Register uint16 ax, Register cu16 cx, Register Eq_1704 dx, Register uint16 bx, Register out word16 cxOut, Register out word16 dxOut)
// Called from:
//      fn0800_49C8
//      fn0800_4A0B
ui32 fn0800_4BAE(uint16 ax, cu16 cx, Eq_1704 dx, uint16 bx, word16 & cxOut, word16 & dxOut)
{
	byte al = (byte) ax;
	byte bl = (byte) bx;
	word16 dx_15 = (char *) &dx.ptr0000->t0000.u0 + (ax >> 0x04);
	word16 cx_24 = cx + (bx >> 0x04);
	ui32 SCZO_31 = cond(dx_15 - cx_24);
	cui16 ax_26 = SEQ(bl, al);
	cui16 bx_29 = SEQ(SLICE(bx >> 0x04, byte, 8), bl);
	ui32 Z_32 = SCZO_31 & 0x04;
	ui32 C_37 = SCZO_31 & 0x02;
	if (dx_15 == cx_24)
	{
		ui32 SCZO_33 = cond((ax_26 & 0x0F) - (bx_29 & 0x0F));
		C_37 = SCZO_33 & 0x02;
		Z_32 = SCZO_33 & 0x04;
	}
	cxOut = cx_24;
	dxOut = dx_15;
	return C_37 | Z_32;
}

// 0800:4C55: void fn0800_4C55(Register Eq_12 ds, Stack Eq_24 wArg04)
// Called from:
//      fn1BF1_032A
void fn0800_4C55(Eq_12 ds, Eq_24 wArg04)
{
	fn0800_4D6E(ds, wArg04);
}

// 0800:4C67: Register Eq_1704 fn0800_4C67(Register Eq_12 ds, Stack Eq_1704 wArg06, Register out word16 dxOut, Register out (ptr16 Eq_5476) dsOut)
// Called from:
//      fn1BF1_0380
Eq_1704 fn0800_4C67(Eq_12 ds, Eq_1704 wArg06, word16 & dxOut, struct Eq_5476 & dsOut)
{
	struct Eq_5476 * ds_22;
	dxOut = fn0800_4648(ds, wArg06, out ds_22);
	dsOut = ds_22;
	return wArg06;
}

// 0800:4C7D: Register cui16 fn0800_4C7D(Register Eq_12 ds, Stack Eq_12 wArg04, Register out word16 dxOut, Register out (ptr16 Eq_5489) dsOut)
// Called from:
//      fn1BF1_034E
cui16 fn0800_4C7D(Eq_12 ds, Eq_12 wArg04, word16 & dxOut, struct Eq_5489 & dsOut)
{
	struct Eq_5489 * ds_23;
	word16 bp_46;
	word16 dx_24;
	cui16 ax_19 = fn0800_4752(ds, wArg04, out dx_24, out bp_46, out ds_23);
	dxOut = dx_24;
	dsOut = ds_23;
	return ax_19;
}

// 0800:4C8F: void fn0800_4C8F(Stack uint16 wArg04)
// Called from:
//      fn1BC2_0113
void fn0800_4C8F(uint16 wArg04)
{
	if (wArg04 > 0x12)
	{
		uint16 ax_23 = 1193181 /u wArg04;
		byte bl_36 = (byte) ax_23;
		byte bh_39 = SLICE(ax_23, byte, 8);
		byte al_25 = __in<byte>(0x61);
		if ((al_25 & 0x03) == 0x00)
		{
			__out<byte>(0x61, al_25 | 0x03);
			__out<byte>(0x43, ~0x49);
		}
		__out<byte>(66, bl_36);
		__out<byte>(66, bh_39);
	}
}

// 0800:4CBF: void fn0800_4CBF()
// Called from:
//      fn1BC2_0113
void fn0800_4CBF()
{
	__out<byte>(0x61, __in<byte>(0x61) & 252);
}

// 0800:4D14: void fn0800_4D14(Register Eq_12 ds, Stack Eq_24 wArg02, Stack word16 wArg04, Stack word16 wArg06)
// Called from:
//      fn0800_4D6E
void fn0800_4D14(Eq_12 ds, Eq_24 wArg02, word16 wArg04, word16 wArg06)
{
	mp16 fp;
	if (wArg06 == 0x00)
	{
		while (Mem18[ds:9998:word16] != 0x00)
		{
			Mem22[ds:9998:word16] = Mem18[ds:9998:word16] - 0x01;
			ui16 bx_23 = Mem22[ds:9998:word16];
			(*((word32) ds + 22576))[bx_23]();
		}
		fn0800_0146();
		Mem18[ds:10000:segptr32]();
	}
	fn0800_01BB(ds);
	fn0800_0159();
	mp16 sp_66 = fp - 6;
	if (wArg04 != 0x00)
		return;
	if (wArg06 == 0x00)
	{
		Mem59[ds:10004:segptr32]();
		Mem59[ds:10008:segptr32]();
	}
	union Eq_24 Eq_5569::* sp_87 = sp_66 - 2;
	selector ss;
	(ss->*sp_87).u1 = (word16) wArg02;
	fn0800_015A((ss->*sp_87).u0);
}

// 0800:4D6E: void fn0800_4D6E(Register Eq_12 ds, Stack Eq_24 wArg04)
// Called from:
//      fn0800_4C55
//      fn1BC2_003A
void fn0800_4D6E(Eq_12 ds, Eq_24 wArg04)
{
	fn0800_4D14(ds, wArg04, 0x00, 0x00);
}

// 0800:4DFC: void fn0800_4DFC(Register (ptr16 Eq_5614) es, Register Eq_12 ds, Stack word16 wArg02, Stack (ptr32 Eq_5617) ptrArg04)
// Called from:
//      fn0800_525B
void fn0800_4DFC(struct Eq_5614 * es, Eq_12 ds, word16 wArg02, struct Eq_5617 * ptrArg04)
{
	ptrArg04->ptr0000 = es;
	ptrArg04->w0002 = wArg02;
	struct Eq_5624 * ss;
	ptrArg04->ptr0004 = ss;
	ptrArg04->t0006.u2 = (byte Eq_4085::*) ds;
}

// 0800:525B: Register Eq_12 fn0800_525B(Register (ptr16 Eq_5614) es, Register Eq_12 ds, Stack word16 wArg04, Stack (ptr32 Eq_5634) dwArg06, Stack (ptr32 Eq_5635) dwArg0A)
// Called from:
//      fn1BC2_003A
//      fn1BC2_0072
//      fn1BC2_00AC
//      fn1BC2_00D5
Eq_12 fn0800_525B(struct Eq_5614 * es, Eq_12 ds, word16 wArg04, struct Eq_5634 * dwArg06, struct Eq_5635 * dwArg0A)
{
	word16 wLoc14;
	<unknown> Eq_5639::* fp;
	fn0800_4DFC(es, ds, wLoc14, fp - 0x0A);
	word16 di_100;
	Eq_12 ds_54;
	fn0800_5290(wArg04, dwArg06, dwArg0A, fp - 0x0A, out di_100, out ds_54);
	return ds_54;
}

// 0800:5290: Register word16 fn0800_5290(Stack word16 wArg04, Stack (ptr32 Eq_5634) ptrArg06, Stack (ptr32 Eq_5635) ptrArg0A, Stack (ptr32 Eq_5650) ptrArg0E, Register out word16 diOut, Register out Eq_12 dsOut)
// Called from:
//      fn0800_525B
//      fn1BC2_0001
word16 fn0800_5290(word16 wArg04, struct Eq_5634 * ptrArg06, struct Eq_5635 * ptrArg0A, struct Eq_5650 * ptrArg0E, word16 & diOut, union Eq_12 & dsOut)
{
	<unknown> Eq_5664::* fp;
	cu8 al_25 = (byte) wArg04;
	<anonymous> * ptrLoc06_158 = (<anonymous> *) (fp - 16);
	word16 v16_42 = ptrArg0E->w0000;
	word16 v17_46 = ptrArg0E->w0006;
	ptrLoc06_158();
	word16 di_56 = ptrArg06->w000A;
	word16 si_57 = ptrArg06->w0008;
	struct Eq_5664 * ss;
	struct Eq_5690 Eq_5664::* sp_64;
	word32 SCZDOP_70;
	(ss->*sp_64).tFFFFFFFE.u2 = (byte Eq_4085::*) (word16) SCZDOP_70;
	(ss->*sp_64).wFFFFFFFC = (word16) SCZDOP_70;
	(ss->*sp_64).wFFFFFFFA = si_57;
	(ss->*sp_64).wFFFFFFF8 = v17_46;
	(ss->*sp_64).wFFFFFFF6 = v16_42;
	ptrArg0E->w0000 = (ss->*sp_64).wFFFFFFF6;
	ptrArg0E->w0006 = (ss->*sp_64).wFFFFFFF8;
	ptrArg0A->w0008 = (ss->*sp_64).wFFFFFFFA;
	ptrArg0A->w000E = (ss->*sp_64).wFFFFFFFC;
	ptrArg0A->t000C.u2 = (ss->*sp_64).tFFFFFFFE.u2;
	ptrArg0A->t000C.u2 = (byte Eq_4085::*) (ptrArg0A->t000C.u2 & 0x01);
	ptrArg0A->w000A = di_56;
	word16 dx_68;
	ptrArg0A->w0006 = dx_68;
	word16 cx_65;
	ptrArg0A->w0004 = cx_65;
	word16 bx_67;
	ptrArg0A->w0002 = bx_67;
	Eq_12 ax_66;
	ptrArg0A->t0000.u2 = (byte Eq_4085::*) ax_66;
	Eq_12 ds_109;
	ds_109.u2 = (ss->*sp_64).t0000.u2;
	if (ptrArg0A->t000C.u2 != 0x00)
	{
		(ss->*sp_64).t0000.u2 = (byte Eq_4085::*) ax_66;
		(ss->*sp_64).tFFFFFFFE.u2 = (byte Eq_4085::*) ax_66;
		fn0800_1F84(ds_109, (ss->*sp_64).tFFFFFFFE.u2);
	}
	word16 si_131 = (ss->*sp_64).w0004;
	diOut = (ss->*sp_64).w0002;
	dsOut = ds_109;
	return si_131;
}

// 0800:532A: void fn0800_532A()
// Called from:
//      fn0800_532F
void fn0800_532A()
{
}

// 0800:532F: Register word16 fn0800_532F()
// Called from:
//      fn0800_537F
word16 fn0800_532F()
{
	__cli();
	__out<byte>(0x43, 0x00);
	fn0800_532A();
	byte al_16 = __in<byte>(0x40);
	fn0800_532A();
	return ~SEQ(__in<byte>(0x40), al_16);
}

// 0800:537F: void fn0800_537F(Register Eq_12 ds, Stack Eq_12 wArg04)
// Called from:
//      fn1BC2_0113
//      fn1BC2_012F
void fn0800_537F(Eq_12 ds, Eq_12 wArg04)
{
	uint16 ax_17 = fn0800_532F();
	uint32 bx_cx_114 = CONVERT(ax_17, uint16, uint32) + fn0800_3F98(Mem35[ds:10084:word16], 0x00, Mem35[ds:0x2766:word16], wArg04);
	uint16 wLoc08_118 = ax_17;
	uint16 cx_51 = (word16) bx_cx_114;
	cup16 wLoc04_122 = SLICE(bx_cx_114, word16, 16);
	while (true)
	{
		uint16 ax_58 = fn0800_532F();
		if (wLoc04_122 <= 0x00 && (wLoc04_122 != 0x00 || ax_58 >= cx_51))
			break;
		if (ax_58 < wLoc08_118)
		{
			if (wLoc04_122 <= 0x01 && (wLoc04_122 < 0x01 || cx_51 < 0x00))
				return;
			--wLoc04_122;
		}
		wLoc08_118 = ax_58;
	}
}

