// PROJ5_195C.c
// Generated by decompiling PROJ5.EXE
// using Reko decompiler version 0.12.2.0.

#include "PROJ5.h"

// 195C:0002: Register word16 fn195C_0002(Register Eq_12 ds)
// Called from:
//      main
word16 fn195C_0002(Eq_12 ds)
{
	Mem10[ds:0x4FF6:byte] = 0x07;
	__out<byte>(0x030C, Mem10[ds:0x4FF6:byte]);
	__out<byte>(0x031C, 0x00);
	__out<byte>(779, 0x82);
	__out<byte>(776, 0x96);
	__out<byte>(778, ~0x02);
	__out<byte>(778, ~0x00);
	__out<byte>(778, 252);
	__out<byte>(0x0313, 0x91);
	__out<byte>(0x0311, ~0x00);
	__out<byte>(0x0313, 0x09);
	__out<byte>(0x0313, 11);
	__out<byte>(0x0313, 0x0D);
	__out<byte>(0x0303, 0x34);
	__out<byte>(0x0303, 0x78);
	__out<byte>(0x0303, 0xB4);
	__out<byte>(775, 0x34);
	__out<byte>(775, 0x78);
	__out<byte>(775, 0xB8);
	__out<byte>(0x0317, 0x34);
	__out<byte>(0x0317, 122);
	__out<byte>(0x0317, 0xB8);
	fn195C_01EB(Mem54[ds:0x2988:word16], 0x01);
	if (__in<byte>(776) == 0x96)
		return 0x01;
	return 0x00;
}

// 195C:01EB: void fn195C_01EB(Stack int16 wArg04, Stack byte bArg06)
// Called from:
//      fn195C_0002
void fn195C_01EB(int16 wArg04, byte bArg06)
{
	__out<byte>(788, (byte) ((word32) (wArg04 *s 100) % 0x0100));
	__out<byte>(788, (byte) ((word32) (wArg04 *s 100) /16 0x0100));
	__out<byte>(0x0315, bArg06);
	__out<byte>(0x0315, 0x00);
}

// 195C:0B84: Register word16 fn195C_0B84(Register Eq_12 ds, Stack int16 wArg04, Stack int16 wArg06, Stack int16 wArg08)
// Called from:
//      fn1128_60AE
word16 fn195C_0B84(Eq_12 ds, int16 wArg04, int16 wArg06, int16 wArg08)
{
	int16 ax_44;
	if (wArg04 > wArg06)
		ax_44 = wArg04;
	else
		ax_44 = wArg06;
	int32 eax_52 = (int32) ax_44;
	int32 eax_76;
	if ((int32) wArg08 < eax_52)
		eax_76 = eax_52;
	else
		eax_76 = (int32) wArg08;
	int32 eax_92 = CONVERT(eax_76 *s 1000, int32, int64) /32 CONVERT(Mem81[ds:10636:word16], word16, int32);
	int32 ebx_94 = CONVERT(Mem93[ds:0x2988:word16], word16, int32);
	word16 ax_102 = (word16) ((int64) eax_92 /32 ebx_94);
	word16 cx_104 = ax_102 + 0x01;
	if (CONVERT(eax_92, int32, int64) %s ebx_94 > CONVERT(Mem95[ds:0x2988:word16] - Mem95[ds:0x2994:word16], int16, int32))
		cx_104 = ax_102 + 0x02;
	return cx_104;
}

