// PROJ5_1A29.c
// Generated by decompiling PROJ5.EXE
// using Reko decompiler version 0.12.2.0.

#include "PROJ5.h"

// 1A29:000C: Register Eq_12 fn1A29_000C(Register Eq_12 ds, Stack (ptr32 char) dwArg04, Stack (ptr32 byte) dwArg08, Stack uint16 wArg0C)
// Called from:
//      fn1A29_00DA
Eq_12 fn1A29_000C(Eq_12 ds, char * dwArg04, byte * dwArg08, uint16 wArg0C)
{
	Eq_12 ds_24;
	Eq_1663 dx_ax_171 = fn0800_2AA3(ds, dwArg04, SEQ(ds, 0x1428), out ds_24);
	if (dx_ax_171 == 0x00)
		return fn1128_07AB(ds_24, SEQ(ds_24, 0x1418), 0x00, 0x00);
	fn0800_2C70(ds_24, dwArg08, 0x01, wArg0C, dx_ax_171);
	return fn0800_258A(ds_24, dx_ax_171);
}

// 1A29:00DA: Register word16 fn1A29_00DA(Sequence (ptr32 byte) si_ds, Stack word16 wArg04, Register out (ptr16 Eq_191) dsOut)
// Called from:
//      main
word16 fn1A29_00DA(byte * si_ds, word16 wArg04, struct Eq_191 & dsOut)
{
	Eq_12 ds = (selector) si_ds;
	byte * dwLoc70_544;
	<unknown> Eq_193::* fp;
	char * dwLoc74_547;
	if (wArg04 != 0x00)
	{
		dwLoc70_544 = (byte *) (fp - 0x0068);
		dwLoc74_547 = SEQ(ds, 0x1430);
	}
	else
	{
		dwLoc70_544 = (byte *) (fp - 0x0068);
		dwLoc74_547 = SEQ(ds, 0x143B);
	}
	struct Eq_191 * ds_51 = fn1A29_000C(ds, dwLoc74_547, dwLoc70_544, 0x32);
	struct Eq_193 * ss;
	ds_51->w2968 = fn0800_40D1(ds_51, fn0800_19A6(ds_51, fp - 0x0068, ss, SEQ(ds, 5166)));
	ds_51->w296A = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, si_ds));
	word16 wLoc68;
	ds_51->w296C = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, SEQ(wLoc68, ds)));
	word16 wLoc66;
	ds_51->w2996 = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, SEQ(wLoc66, ds)));
	word16 wLoc64;
	ds_51->w2988 = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, SEQ(wLoc64, ds)));
	word16 wLoc62;
	ds_51->w298A = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, SEQ(wLoc62, ds)));
	word16 wLoc60;
	ds_51->w298C = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, SEQ(wLoc60, ds)));
	word16 wLoc5E;
	ds_51->w298E = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, SEQ(wLoc5E, ds)));
	word16 wLoc5C;
	ds_51->w2994 = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, SEQ(wLoc5C, ds)));
	word16 wLoc5A;
	ds_51->w57EA = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, SEQ(wLoc5A, ds)));
	word16 Eq_193::* sp_472 = fp - 88;
	if (wArg04 != 0x00)
	{
		word16 wLoc58;
		ds_51->w29B8 = fn0800_40D1(ds_51, fn0800_19A6(ds_51, 0x00, 5166, SEQ(wLoc58, ds)));
		sp_472 = fp - 0x56;
	}
	word16 si_524 = ss->*sp_472;
	dsOut = ds_51;
	return si_524;
}

// 1A29:0326: Register Eq_12 fn1A29_0326(Register Eq_12 ds)
// Called from:
//      main
Eq_12 fn1A29_0326(Eq_12 ds)
{
	Eq_12 ds_121;
	fn1A29_04E4(ds);
	<unknown> Eq_10305::* fp;
	fn0800_1BEC(fp - 80, SEQ(ds, 22422));
	fn0800_1F49(ds, SEQ(ds, 10718));
	Eq_1663 dx_ax_257 = fn0800_2AA3(ds, SEQ(ds, 0x1446), SEQ(ds, 5200), out ds_121);
	if (dx_ax_257 == 0x00)
		ds_121 = fn1128_07AB(ds_121, SEQ(ds_121, 0x1418), 0x00, 0x00);
	fn0800_2C70(ds_121, fp - 0x0E, 0x01, 0x08, dx_ax_257);
	Eq_12 ds_144 = fn0800_258A(ds_121, dx_ax_257);
	byte bLoc0E;
	byte bLoc0D;
	byte bLoc0C;
	byte bLoc0B;
	Mem161[ds_144:0x4FE8:word32] = (CONVERT(bLoc0E, byte, word32) << 0x18) + (CONVERT(bLoc0D, byte, word32) << 0x10) + (CONVERT(bLoc0C, byte, word32) << 0x08) + CONVERT(bLoc0B, byte, word32);
	byte bLoc0A;
	byte bLoc09;
	byte bLoc08;
	byte bLoc07;
	Mem173[ds_144:20460:word32] = (CONVERT(bLoc0A, byte, word32) << 0x18) + (CONVERT(bLoc09, byte, word32) << 0x10) + (CONVERT(bLoc08, byte, word32) << 0x08) + CONVERT(bLoc07, byte, word32);
	fn0800_1F49(ds_144, fp - 80);
	return ds_144;
}

// 1A29:04E4: void fn1A29_04E4(Register Eq_12 ds)
// Called from:
//      main
//      fn1A29_0326
void fn1A29_04E4(Eq_12 ds)
{
	fn0800_1BEC(SEQ(ds, 22422), SEQ(ds, 0x1460));
	byte al_37 = fn0800_1D24();
	Mem40[ds:22422:byte] = al_37 + 0x41;
	fn0800_1F65(al_37 + 0x41, 0x00, ds, 0x00, 22425);
}

