// PROJ5_1BF1.c
// Generated by decompiling PROJ5.EXE
// using Reko decompiler version 0.12.2.0.

#include "PROJ5.h"

struct seg1BF1_t * g_ptr1BF10 = &g_tFFFF8B55; // 0001BF10
// 1BF1:0031: void fn1BF1_0031(Stack Eq_6087 ptrArg02, Stack Eq_10765 ptrArg06)
// Called from:
//      fn1BF1_0979
void fn1BF1_0031(Eq_6087 ptrArg02, Eq_10765 ptrArg06)
{
	struct Eq_10766 * ds_47 = SLICE(ptrArg02, selector, 16);
	byte Eq_10766::* si_21 = (word16) ptrArg02;
	struct Eq_10770 * es_49 = SLICE(ptrArg06, selector, 16);
	byte Eq_10770::* di_26 = (word16) ptrArg06;
	byte al_23;
	do
	{
		al_23 = ds_47->*si_21;
		es_49->*di_26 = al_23;
		++si_21;
		++di_26;
	} while (al_23 != 0x00);
}

// 1BF1:0050: Register int16 fn1BF1_0050(Stack word16 wArg02, Stack (ptr32 Eq_10791) ptrArg04, Stack (ptr32 Eq_10792) ptrArg08, Register out word16 cxOut)
// Called from:
//      fn1BF1_03F4
int16 fn1BF1_0050(word16 wArg02, <unknown> * ptrArg04, <unknown>* ptrArg08, word16 & cxOut)
{
	memcmp(ptrArg08, ptrArg04, (uint32) wArg02);
	int16 firstDifference_27 = __find_first_difference__(ptrArg08, ptrArg04);
	int16 ax_34 = (int16) (((char *) (word16) ptrArg08 + firstDifference_27)[-1] - ((char *) ((word16) ptrArg04) + firstDifference_27)[-1]);
	cxOut = wArg02 - firstDifference_27;
	return ax_34;
}

// 1BF1:0094: Sequence ptr32 fn1BF1_0094(Stack Eq_10765 ptrArg02)
// Called from:
//      fn1BF1_0979
ptr32 fn1BF1_0094(Eq_10765 ptrArg02)
{
	return (char *) (word16) ptrArg02 + ((word32) strlen(ptrArg02) + 1) - 0x01;
}

// 1BF1:00AD: void fn1BF1_00AD(Stack segptr32 ptrArg02, Stack Eq_12 ptrArg06, Stack segptr32 ptrArg0A)
// Called from:
//      fn1BF1_072D
//      fn1BF1_07A5
//      fn1BF1_165B
void fn1BF1_00AD(segptr32 ptrArg02, Eq_12 ptrArg06, segptr32 ptrArg0A)
{
	struct Eq_10842 * ds_20 = SLICE(ptrArg06, selector, 16);
	byte Eq_10842::* si_22 = (word16) ptrArg06;
	struct Eq_10846 * es_80 = SLICE(ptrArg0A, selector, 16);
	byte Eq_10846::* di_34 = (word16) ptrArg0A;
	if (ptrArg06 != 0x00)
	{
		byte al_31;
		do
		{
			al_31 = ds_20->*si_22;
			es_80->*di_34 = al_31;
			++si_22;
			++di_34;
		} while (al_31 != 0x00);
		--di_34;
	}
	struct Eq_10852 * ds_82 = SLICE(ptrArg02, selector, 16);
	byte Eq_10852::* si_51 = (word16) ptrArg02;
	byte al_53;
	do
	{
		al_53 = ds_82->*si_51;
		es_80->*di_34 = al_53;
		++si_51;
		++di_34;
	} while (al_53 != 0x00);
}

// 1BF1:00DB: void fn1BF1_00DB(Stack segptr32 ptrArg02)
// Called from:
//      fn1BF1_032A
void fn1BF1_00DB(segptr32 ptrArg02)
{
	msdos_display_string(ptrArg02);
}

// 1BF1:00EB: void fn1BF1_00EB(Register Eq_12 ds)
// Called from:
//      fn1BF1_00F8
//      fn1BF1_013D
//      fn1BF1_07A5
//      fn1BF1_165B
void fn1BF1_00EB(Eq_12 ds)
{
	msdos_close_file(Mem7[ds:0x1903:word16]);
}

// 1BF1:00F8: Register word16 fn1BF1_00F8(Register Eq_12 ds, Stack (ptr32 cup16) ptrArg04, Stack (ptr32 char) ptrArg08, Register out word16 cxOut, Register out word16 dxOut)
// Called from:
//      fn1BF1_072D
word16 fn1BF1_00F8(Eq_12 ds, cup16 * ptrArg04, char * ptrArg08, word16 & cxOut, word16 & dxOut)
{
	int32 * dx_ax_33;
	word16 dx_18 = (word16) ptrArg08;
	word16 ax_20;
	word16 ax_54;
	if (!msdos_open_file(ptrArg08, 0x00, out ax_20))
	{
		ax_54 = ~0x02;
		goto l1BF1_0138;
	}
	Mem24[ds:0x1903:word16] = ax_20;
	word16 cx = 0x00;
	cup16 ax_35 = (word16) dx_ax_33;
	word16 dx_41 = SLICE(dx_ax_33, word16, 16);
	if (!msdos_set_file_position(ax_20, 0x00000000<p32>, 0x02, out dx_ax_33) && ax_35 != 0x00)
	{
		dx_18 = dx_41;
		if (dx_41 == 0x00 && ax_35 <= 0x7FFF)
		{
			*ptrArg04 = ax_35;
			ax_54 = 0x00;
l1BF1_0138:
			cxOut = cx;
			dxOut = dx_18;
			return ax_54;
		}
	}
	fn1BF1_00EB(ds);
	dx_18 = dx_41;
	word16 wArg02;
	ax_54 = wArg02;
	goto l1BF1_0138;
}

// 1BF1:013D: Register word16 fn1BF1_013D(Register Eq_12 ds, Stack Eq_10955 ptrArg02, Stack Eq_12 wArg06, Stack uint16 wArg08)
// Called from:
//      fn1BF1_07A5
//      fn1BF1_165B
word16 fn1BF1_013D(Eq_12 ds, Eq_10955 ptrArg02, Eq_12 wArg06, uint16 wArg08)
{
	int32 * dx_ax_18;
	word16 ax_28;
	if (!msdos_set_file_position(Mem7[ds:0x1903:word16], CONVERT(wArg08, uint16, uint32), 0x00, out dx_ax_18) && !msdos_read_file(Mem21[ds:0x1903:word16], wArg06, ptrArg02, out ax_28))
		return 0x00;
	fn1BF1_00EB(ds);
	Mem36[ds:0x17A6:word16] = ~0x0B;
	return 0x01;
}

// 1BF1:0178: Register word16 fn1BF1_0178(Stack Eq_10993 ptrArg02, Stack Eq_10994 ptrArg06, Stack word16 wArg0A)
// Called from:
//      fn1BF1_0979
word16 fn1BF1_0178(Eq_10993 ptrArg02, Eq_10994 ptrArg06, word16 wArg0A)
{
	memcpy(ptrArg02, ptrArg06, (uint32) wArg0A);
	return 0x00;
}

// 1BF1:030D: Register Eq_12 fn1BF1_030D()
// Called from:
//      main
Eq_12 fn1BF1_030D()
{
	selector seg20D3;
	Eq_12 ax_16 = seg20D3->t17A6;
	seg20D3->t17A6 = 0x00;
	return ax_16;
}

// 1BF1:032A: void fn1BF1_032A(Register Eq_12 ds)
// Called from:
//      fn1BF1_08A1
void fn1BF1_032A(Eq_12 ds)
{
	word16 ax_14;
	if (Mem7[ds:0x17B9:word16] != 0x00)
		ax_14 = 0x1B7F;
	else
		ax_14 = 7078;
	fn1BF1_00DB(SEQ(ds, ax_14));
	fn0800_4C55(ds, ~0x00);
}

// 1BF1:034E: Register word16 fn1BF1_034E(Register Eq_12 ds, Stack Eq_12 ptrArg02, Stack Eq_12 wArg06, Register out cui16 cxOut, Register out Eq_1704 dxOut, Register out Eq_1704 dsOut)
// Called from:
//      fn1BF1_07A5
//      fn1BF1_0979
//      fn1BF1_165B
word16 fn1BF1_034E(Eq_12 ds, Eq_12 ptrArg02, Eq_12 wArg06, cui16 & cxOut, struct Eq_1704 & dxOut, struct Eq_1704 & dsOut)
{
	Eq_1704 ds_16;
	Eq_1704 dx_17;
	Eq_4341 ax_13 = fn0800_4C7D(ds, wArg06, out dx_17, out ds_16);
	cui16 cx_27 = ax_13 | dx_17;
	if (cx_27 != 0x00 && (ax_13 == 0x00 && ds_16 == dx_17))
	{
		cx_27 = 0x00;
		dx_17 = (Eq_1704) 0x00;
	}
	ptrArg02.u1->t0000.u0 = (cui16) ax_13;
	ptrArg02.u1->t0002.ptr0000 = (struct Eq_14041 *) dx_17;
	word16 ax_55 = 0x01;
	if (cx_27 != 0x00)
		ax_55 = 0x00;
	cxOut = cx_27;
	dxOut = dx_17;
	dsOut = ds_16;
	return ax_55;
}

// 1BF1:0380: Register word16 fn1BF1_0380(Register Eq_12 ds, Stack Eq_12 ptrArg02, Stack Eq_12 wArg06, Register out cui16 dxOut, Register out (ptr16 Eq_11085) esOut, Register out Eq_12 dsOut)
// Called from:
//      fn1BF1_04A8
//      fn1BF1_07A5
//      fn1BF1_0979
//      fn1BF1_0E3E
//      fn1BF1_165B
word16 fn1BF1_0380(Eq_12 ds, Eq_12 ptrArg02, Eq_12 wArg06, cui16 & dxOut, struct Eq_11085 & esOut, union Eq_12 & dsOut)
{
	word16 cx;
	cui16 dx;
	if ((ptrArg02.u1->t0000.u0 | ((ptrArg02.u1)->t0002).ptr0000) != 0x00 && wArg06 != 0x00)
		cx = fn0800_4C67(ds, ptrArg02.u1->t0002.ptr0000, out dx, out ds);
	ptrArg02.u1->t0002.ptr0000 = (struct Eq_14041 *) 0x00;
	ptrArg02.u1->t0000.u0 = 0x00;
	dxOut = dx;
	esOut = SLICE(ptrArg02, selector, 16);
	dsOut = ds;
	return cx;
}

// 1BF1:03B8: Register word16 fn1BF1_03B8(Stack word16 wArg02, Stack (ptr32 word16) ptrArg04, Stack (memptr Eq_12 Eq_6076) wArg08, Stack word16 wArg0A, Register out word16 cxOut, Register out (ptr16 Eq_11119) dxOut)
// Called from:
//      fn1BF1_03F4
//      fn1BF1_04A8
word16 fn1BF1_03B8(word16 wArg02, word16 * ptrArg04, struct Eq_6076 Eq_12::* wArg08, word16 wArg0A, word16 & cxOut, struct Eq_11119 & dxOut)
{
	byte ch;
	cu16 si_19 = (char *) wArg08 + *ptrArg04;
	*ptrArg04 -= si_19 & 0x0F;
	struct Eq_11119 * dx_28 = wArg0A + (si_19 >> 0x04);
	word16 cx_46 = SEQ(ch, 0x04);
	if ((si_19 & 0x0F) != 0x00)
	{
		memcpy(*dx_28, si_19 & 0x0F, (uint32) wArg02);
		cx_46 = 0x00;
	}
	cxOut = cx_46;
	dxOut = dx_28;
	return 0x00;
}

// 1BF1:03F4: Register Eq_12 fn1BF1_03F4(Stack (ptr32 word16) ptrArg04, Register out word16 cxOut, Register out word16 dxOut, Register out (memptr Eq_12 Eq_6076) bxOut)
// Called from:
//      main
//      fn1BF1_07A5
Eq_12 fn1BF1_03F4(word16 * ptrArg04, word16 & cxOut, word16 & dxOut, struct Eq_6076 & bxOut)
{
	word16 dx_105;
	word16 wArg06 = SLICE(ptrArg04, word16, 16);
	struct Eq_6076 Eq_12::* wArg04 = (word16) ptrArg04;
	word16 dx_119 = wArg06;
	struct Eq_11152 * ptrLoc06_166 = SEQ(wArg06, (char *) wArg04 + 0x0080);
	selector seg20D3;
	Eq_12 ax_130;
	if (seg20D3->t17B9 != 0x03)
	{
		struct Eq_6076 Eq_12::* bx = wArg04;
		word16 cx;
		if (*ptrArg04 != 0x6B70)
			ax_130.u0 = ~0x03;
		else
		{
			bx = (struct Eq_6076 Eq_12::*) ((char *) wArg04 + 0x0080);
			if (ptrLoc06_166->b0006 >= 0x02 && ptrLoc06_166->b0008 <= 0x01)
			{
				Eq_12 si_37;
				si_37.u0 = 0x00;
				while (si_37 < seg20D3->t17F6)
				{
					int32 dx_ax_59 = si_37 *s32 0x1A;
					dx_119 = SLICE(dx_ax_59, word16, 16);
					if (fn1BF1_0050(0x08, SEQ(0x20D3, (char *) (word16) dx_ax_59 + 0x00001801), SEQ(wArg06, (char *) wArg04 + 0x008B), out cx) == 0x00)
					{
						int32 dx_ax_118 = si_37 *s32 0x1A;
						struct Eq_6076 Eq_12::* ax_120 = (word16) dx_ax_118;
						word16 ax_102 = fn1BF1_03B8(SEQ(wArg06, (char *) wArg04 + 0x0080)->w0004, SEQ(wArg06, (char *) wArg04 + 0x0080), wArg04, wArg06, out cx, out dx_105);
						(0x20D3->*ax_120).w1810 = dx_105;
						(0x20D3->*ax_120).w180E = ax_102;
						seg20D3->t17A6 = 0x00;
						dx_119 = SLICE(dx_ax_118, word16, 16);
						bx = ax_120;
						ax_130 = si_37;
						goto l1BF1_04A2;
					}
					si_37.u1 = (word32) si_37 + 1;
				}
				goto l1BF1_049C;
			}
			ax_130.u0 = ~0x11;
		}
l1BF1_049F:
		seg20D3->t17A6 = ax_130;
l1BF1_04A2:
		cxOut = cx;
		dxOut = dx_119;
		bxOut = bx;
		return ax_130;
	}
	else
	{
l1BF1_049C:
		ax_130.u0 = ~0x0A;
		goto l1BF1_049F;
	}
}

// 1BF1:04A8: Register Eq_12 fn1BF1_04A8(Stack (ptr32 word16) ptrArg04)
// Called from:
//      fn1BF1_165B
Eq_12 fn1BF1_04A8(word16 * ptrArg04)
{
	word16 dx_161;
	word16 cx_376;
	selector seg20D3;
	word16 wArg06_233 = SLICE(ptrArg04, word16, 16);
	struct Eq_6076 Eq_12::* wArg04_241 = (word16) ptrArg04;
	Eq_12 ax_173;
	if (*ptrArg04 == 0x4B50)
	{
		struct Eq_11249 * es_201 = SLICE(ptrArg04, selector, 16);
		struct Eq_11251 Eq_11249::* di_202 = (word16) ptrArg04;
		word16 cx_27 = ~0x00;
		while (cx_27 != 0x00)
		{
			++di_202;
			--cx_27;
			if ((es_201->*di_202).b0000 != 0x1A)
				break;
		}
		struct Eq_11255 * ptrLoc06_211 = (struct Eq_11255 *) &&(es_201->*(es_201->*di_202).b0000);
		if (ptrLoc06_211->b0008 >= 0x01 && ptrLoc06_211->b000A <= 0x01)
		{
			word16 dx_57 = ptrLoc06_211->w0004;
			word16 ax_58 = ptrLoc06_211->w0002;
			Eq_11287 wLoc0C_214;
			wLoc0C_214.u0 = 0x00;
			Eq_11289 si_108;
			si_108.u0 = 0x15FD;
			while (wLoc0C_214 < 0x14)
			{
				word16 ax_71 = (word16) (0x20D3->*((word16) si_108 + 0x0A));
				if (0x20D3->*((word16) si_108 + 0x0C) == dx_57 && ax_71 == ax_58)
					break;
				wLoc0C_214 = (word16) wLoc0C_214.u1 + 1;
				si_108 = (word16) si_108 + 0x0F;
			}
			if (wLoc0C_214 == 0x14)
			{
				Eq_11287 ax_90 = seg20D3->t15FB;
				wLoc0C_214 = ax_90;
				if (ax_90 >= 0x14)
				{
					ax_173.u0 = ~0x0A;
l1BF1_0532:
					seg20D3->t17A6 = ax_173;
					return ax_173;
				}
				int16 ax_96 = seg20D3->t15FB *s16 0x0F;
				seg20D3->t15FB = seg20D3->t15FB + 0x01;
				(*((byte) ~0x2C + 5641))[seg20D3->t15FB].w0000 = dx_57;
				(*((byte) ~0x2C + 5639))[seg20D3->t15FB].w0000 = ax_58;
				si_108 = ax_96 + 0x15FD;
			}
			word16 dx_374;
			selector es_375;
			Eq_12 ds_129;
			fn1BF1_0380(0x20D3, SEQ(0x20D3, si_108), 0x20D3->*((word16) si_108 + 8), out dx_374, out es_375, out ds_129);
			ds_129->*((word16) si_108 + 2) = 0x00;
			ds_129->*si_108 = 0x00;
			word16 ax_158 = fn1BF1_03B8(*((char *) &&(es_201->*(es_201->*di_202).b0000) + 6), &&(es_201->*(es_201->*di_202).b0000), wArg04_241, wArg06_233, out cx_376, out dx_161);
			ds_129->*((word16) si_108 + 6) = dx_161;
			ds_129->*((word16) si_108 + 4) = ax_158;
			ds_129->*((word16) si_108 + 8) = 0x00;
			ax_173.u1 = (word16) wLoc0C_214.u1 + 1;
			return ax_173;
		}
	}
	ax_173.u0 = ~0x0C;
	goto l1BF1_0532;
}

// 1BF1:069F: Register (memptr Eq_12 Eq_11388) fn1BF1_069F(Register Eq_12 ds)
// Called from:
//      fn1BF1_0979
//      fn1BF1_0E3E
struct Eq_11388 Eq_12::* fn1BF1_069F(Eq_12 ds)
{
	Mem9[ds:5935:word16] = 0x1BF1;
	Mem10[ds:5933:word16] = 0x032A;
	Mem11[ds:0x172B:word16] = 0x1BF1;
	Mem12[ds:5929:word16] = 0x032A;
	Mem13[ds:0x178C:word16] = 0x1744;
	Mem14[ds:6036:word16] = 0x00;
	Mem15[ds:0x1792:word16] = 0x00;
	Mem16[ds:0x17AA:word16] = 0x00;
	Mem17[ds:6056:word16] = 0x00;
	Mem18[ds:6040:word16] = 0x00;
	Mem19[ds:0x1796:word16] = 0x00;
	Mem20[ds:6046:word16] = 0x00;
	Mem21[ds:6044:word16] = 0x00;
	struct Eq_11388 Eq_12::* bx_22 = Mem21[ds:0x178C:word16];
	(ds->*bx_22).w000E = 0x00;
	(ds->*bx_22).w000C = 0x00;
	(ds->*bx_22).w0010 = 0x00;
	(ds->*bx_22).w0028 = 0x00;
	(ds->*bx_22).w0026 = 0x00;
	(ds->*bx_22).w002A = 0x00;
	(ds->*bx_22).b0016 = 0x00;
	Mem31[ds:6050:word16] = 0x01;
	Mem32[ds:0x17A0:word16] = 0x01;
	Mem33[ds:6077:word16] = 0x00;
	Mem34[ds:0x17B9:word16] = 0x00;
	return bx_22;
}

// 1BF1:072D: Register word16 fn1BF1_072D(Register Eq_12 ds, Stack (ptr32 cup16) ptrArg04, Stack segptr32 dwArg08, Stack Eq_12 dwArg0C, Register out word16 cxOut, Register out cui16 dxOut)
// Called from:
//      fn1BF1_07A5
//      fn1BF1_165B
word16 fn1BF1_072D(Eq_12 ds, cup16 * ptrArg04, segptr32 dwArg08, Eq_12 dwArg0C, word16 & cxOut, cui16 & dxOut)
{
	*ptrArg04 = 0x00;
	<unknown> Eq_11506::* fp;
	fn1BF1_00AD(dwArg08, dwArg0C, fp - 0x0066);
	word16 cx_113;
	cui16 dx_114;
	Mem68[ds:0x17A6:word16] = fn1BF1_00F8(ds, ptrArg04, fp - 0x0066, out cx_113, out dx_114);
	word16 ax_124;
	if (Mem68[ds:0x17A6:word16] != 0x00)
	{
		fn1BF1_00AD(dwArg08, 0x00, fp - 0x0066);
		Mem121[ds:0x17A6:word16] = fn1BF1_00F8(ds, ptrArg04, fp - 0x0066, out cx_113, out dx_114);
		if (Mem121[ds:0x17A6:word16] != 0x00)
		{
			ax_124 = 0x01;
l1BF1_079E:
			cxOut = cx_113;
			dxOut = dx_114;
			return ax_124;
		}
	}
	ax_124 = 0x00;
	goto l1BF1_079E;
}

// 1BF1:07A5: Register word16 fn1BF1_07A5(Register Eq_12 ds, Stack Eq_12 dwArg02, Stack Eq_12 wArg06, Register out cui16 cxOut, Register out (ptr16 Eq_9) dxOut, Register out Eq_12 dsOut)
// Called from:
//      fn1BF1_0979
word16 fn1BF1_07A5(Eq_12 ds, Eq_12 dwArg02, Eq_12 wArg06, cui16 & cxOut, struct seg1BF1_t & dxOut, union Eq_12 & dsOut)
{
	fn1BF1_00AD(SEQ(ds, 0x1BE3), SEQ(ds, wArg06 *s16 0x1A + 6136), SEQ(ds, 5531));
	struct seg1BF1_t * dx_100 = (*((word32) ds + 6160))[wArg06].ptr0000;
	cui16 ax_46 = (*((word32) ds + 6158))[wArg06].w0000;
	Mem47[ds:5935:word16] = dx_100;
	Mem48[ds:5933:word16] = ax_46;
	if ((ax_46 | dx_100) == 0x00)
	{
		cui16 cx;
		word16 ax_224;
		if (fn1BF1_072D(ds, SEQ(ds, 0x179A), SEQ(ds, 5531), dwArg02, out cx, out dx_100) == 0x00)
		{
			if (fn1BF1_034E(ds, SEQ(ds, 0x1796), Mem72[ds:0x179A:word16], out cx, out dx_100, out ds) != 0x00)
			{
				fn1BF1_00EB(ds);
				Mem223[ds:0x17A6:word16] = ~0x04;
			}
			else if (fn1BF1_013D(ds, Mem121[ds:0x1796:word32], Mem118[ds:0x179A:word16], 0x00) != 0x00)
			{
				selector es_340;
				cx = fn1BF1_0380(ds, SEQ(ds, 0x1796), Mem127[ds:0x179A:word16], out dx_100, out es_340, out ds);
			}
			else
			{
				cui16 v24_142 = Mem127[ds:6040:word16];
				cx = v24_142;
				word16 cx_337;
				word16 dx_338;
				word16 bx_339;
				if (fn1BF1_03F4(SEQ(v24_142, Mem144[ds:0x1796:word16]), out cx_337, out dx_338, out bx_339) == wArg06)
				{
					dx_100 = (*((word32) ds + 6160))[wArg06].ptr0000;
					cui16 ax_170 = (*((word32) ds + 6158))[wArg06].w0000;
					Mem171[ds:5935:word16] = dx_100;
					Mem172[ds:5933:word16] = ax_170;
					fn1BF1_00EB(ds);
l1BF1_0899:
					ax_224 = 0x01;
					goto l1BF1_089C;
				}
				fn1BF1_00EB(ds);
				Mem179[ds:0x17A6:word16] = ~0x03;
				selector es_341;
				cx = fn1BF1_0380(ds, SEQ(ds, 0x1796), Mem179[ds:0x179A:word16], out dx_100, out es_341, out ds);
			}
		}
		ax_224 = 0x00;
l1BF1_089C:
		cxOut = cx;
		dxOut = dx_100;
		dsOut = ds;
		return ax_224;
	}
	else
	{
		Mem228[ds:6040:word16] = 0x00;
		Mem229[ds:0x1796:word16] = 0x00;
		Mem230[ds:0x179A:word16] = 0x00;
		goto l1BF1_0899;
	}
}

// 1BF1:08A1: Register word16 fn1BF1_08A1(Register out word16 dxOut, Register out word16 bxOut, Register out (ptr16 Eq_11796) esOut)
// Called from:
//      fn1BF1_0979
word16 fn1BF1_08A1(word16 & dxOut, word16 & bxOut, struct Eq_11796 & esOut)
{
	word16 bx_263;
	struct Eq_11796 * es_222;
	selector seg20D3;
	if (seg20D3->t17B9 == 0x00)
		fn1BF1_032A(0x20D3);
	struct Eq_11720 Eq_12::* bx_36 = (struct Eq_11720 Eq_12::*) seg20D3->t178A;
	fn1BF1_0F00(0x00, 0x00, (0x20D3->*bx_36).w0002, (0x20D3->*bx_36).w0004, 0x01);
	memcpy(&seg20D3->t17DB, fn1BF1_1DB3(), 0x11);
	fn1BF1_13E9(&seg20D3->t17DB);
	if (fn1BF1_1D98() != 0x01)
		fn1BF1_138D(0x00);
	seg20D3->t17B2 = 0x00;
	fn1BF1_1D5C((byte) fn1BF1_1D7D());
	fn1BF1_125E(&seg20D3->t1969, fn1BF1_1D7D());
	fn1BF1_1211(0x01, fn1BF1_1D7D());
	fn1BF1_115D(0x00, 0x00, 0x01);
	word16 dx_221 = fn1BF1_165B(0x00, 0x00, 0x01, out es_222);
	fn1BF1_161A(0x00, 0x02);
	fn1BF1_19E7(0x00);
	word16 cx_264 = fn1BF1_1007(0x00, 0x00, out bx_263);
	dxOut = dx_221;
	bxOut = bx_263;
	esOut = es_222;
	return cx_264;
}

// 1BF1:0979: Register cui16 fn1BF1_0979(Register Eq_12 si, Register Eq_12 di, Stack (ptr32 Eq_10974) ptrArg04, Stack (ptr32 ci16) ptrArg08, Stack Eq_6087 wArg0C, Stack Eq_12 wArg0E, Register out word16 dxOut, Register out word16 bxOut, Register out Eq_12 esOut)
// Called from:
//      main
cui16 fn1BF1_0979(Eq_12 si, Eq_12 di, union Eq_10974 * ptrArg04, ci16 * ptrArg08, Eq_6087 wArg0C, Eq_12 wArg0E, word16 & dxOut, word16 & bxOut, union Eq_12 & esOut)
{
	word16 dx_125;
	mp16 fp;
	Eq_12 wArg0A_497;
	wArg0A_497.u1 = SLICE(ptrArg08, word16, 16);
	Eq_10765 wArg08_499 = (word16) ptrArg08;
	selector seg20D3;
	seg20D3->t172B = (<unknown>) (seg20D3->t158E + (seg20D3->t158C + 0x20 >> 0x04));
	seg20D3->t1729 = 0x00;
	mp16 sp_103 = fp - 0x10;
	Eq_12 ds_20;
	ds_20.u0 = 0x20D3;
	Eq_12 wLoc0A_485;
	wLoc0A_485.u0 = 0x00;
	if (ptrArg04->u0 == 0x00)
	{
		while (wLoc0A_485 < seg20D3->t17F6 && ptrArg04->u0 == 0x00)
		{
			if (((*((byte) ~0x2C + 6154))[wLoc0A_485].w0000 | ((*((byte) ~0x2C + 6156)))[wLoc0A_485].w0000) != 0x00)
			{
				int32 dx_ax_61 = wLoc0A_485 *s32 0x1A;
				struct Eq_11965 Eq_12::* ax_63 = (word16) dx_ax_61;
				(0x20D3->*ax_63).ptr180A();
				ci16 ax_71;
				if (ax_71 >= 0x00)
				{
					seg20D3->t178E = wLoc0A_485;
					ptrArg04->u0 = (int16) ((word32) wLoc0A_485 + 0x0080);
					*ptrArg08 = ax_71;
					break;
				}
			}
			wLoc0A_485.u1 = (word32) wLoc0A_485 + 1;
		}
	}
	struct Eq_11864 Eq_11866::* sp_104 = sp_103 - 2;
	selector ss;
	(ss->*sp_104).t0000.u2 = (byte Eq_4085::*) wArg0A_497;
	(ss->*sp_104).tFFFFFFFE.u0 = (word16) wArg08_499;
	Eq_12 wArg06_500;
	wArg06_500.u1 = SLICE(ptrArg04, word16, 16);
	(ss->*sp_104).tFFFFFFFC.u2 = (byte Eq_4085::*) wArg06_500;
	(ss->*sp_104).tFFFFFFFA.u0 = (word16) (word16) ptrArg04;
	(ss->*sp_104).tFFFFFFF8.u2 = (byte Eq_4085::*) 0x20D3;
	(ss->*sp_104).tFFFFFFF6.u0 = 6030;
	cui16 cx_124 = fn1BF1_1AAB((ss->*sp_104).tFFFFFFF6.u1, (ss->*sp_104).tFFFFFFFA.u1, (ss->*sp_104).tFFFFFFFE.u1, out dx_125);
	Eq_12 es_132 = wArg06_500;
	word16 bx_403;
	if (ptrArg04->u0 < 0x00)
	{
		seg20D3->t17A6 = ~0x01;
		ptrArg04->u0 = ~0x01;
	}
	else
	{
		seg20D3->t1790 = *ptrArg08;
		if ((wArg0C | wArg0E) == 0x00)
			seg20D3->t15A8 = 0x00;
		else
		{
			(ss->*sp_104).t0000.u2 = (byte Eq_4085::*) 0x20D3;
			(ss->*sp_104).tFFFFFFFE.u0 = 5544;
			(ss->*sp_104).tFFFFFFFC.u2 = (byte Eq_4085::*) wArg0E;
			(ss->*sp_104).tFFFFFFFA.u0 = (word16) wArg0C;
			fn1BF1_0031((ss->*sp_104).tFFFFFFFA.u1, (ss->*sp_104).tFFFFFFFE.u1);
			if (seg20D3->t15A8 != 0x00)
			{
				(ss->*sp_104).t0000.u2 = (byte Eq_4085::*) 0x20D3;
				(ss->*sp_104).tFFFFFFFE.u0 = 5544;
				struct Eq_12038 * dx_ax_592 = fn1BF1_0094((ss->*sp_104).tFFFFFFFE.u1);
				word16 dx_175 = SLICE(dx_ax_592, word16, 16);
				word16 ax_173 = (word16) dx_ax_592;
				if (dx_ax_592->bFFFFFFFF != 0x3A && dx_ax_592->bFFFFFFFF != 0x5C)
				{
					dx_ax_592->b0000 = 0x5C;
					*SEQ(dx_175, ax_173 + 0x01) = 0x00;
				}
			}
		}
		if (ptrArg04->u0 > 0x80)
			seg20D3->t178E = ptrArg04->u0 & 0x7F;
		struct Eq_12066 Eq_11866::* sp_221 = sp_103 - 2;
		(ss->*sp_221).t0000.u2 = (byte Eq_4085::*) seg20D3->t178E;
		(ss->*sp_221).tFFFFFFFE.u2 = (byte Eq_4085::*) 0x20D3;
		(ss->*sp_221).tFFFFFFFC.u2 = (byte Eq_4085::*) 5544;
		if (fn1BF1_07A5(0x20D3, (ss->*sp_221).tFFFFFFFC.u1, (ss->*sp_221).t0000.u2, out cx_124, out dx_125, out ds_20) == 0x00)
		{
			Mem453[ptrArg04 + 0x00:word16] = Mem228[ds_20:0x17A6:word16];
			es_132 = wArg06_500;
		}
		else
		{
			(ss->*sp_221).t0000.u2 = (byte Eq_4085::*) si;
			(ss->*sp_221).tFFFFFFFE.u2 = (byte Eq_4085::*) di;
			(ss->*sp_221).tFFFFFFFC.u2 = (byte Eq_4085::*) ds_20;
			Eq_12 es_257;
			es_257.u2 = (ss->*sp_221).tFFFFFFFC.u2;
			byte Eq_12::* di_260 = 0x1744;
			word16 cx_262;
			for (cx_262 = 0x45; cx_262 != 0x00; --cx_262)
			{
				es_257->*di_260 = 0x00;
				++di_260;
			}
			Mem280[ss:sp_221 + 0x00:word16] = Mem273[es_257:5625:word16];
			(ss->*sp_221).tFFFFFFFE.u2 = (byte Eq_4085::*) es_257;
			(ss->*sp_221).tFFFFFFFC.u2 = (byte Eq_4085::*) 0x1750;
			word16 cx_596;
			word16 dx_597;
			if (fn1BF1_034E(es_257, (ss->*sp_221).tFFFFFFFC.u1, (ss->*sp_221).t0000.u2, out cx_596, out dx_597, out ds_20) != 0x00)
			{
				Mem417[ds_20:0x17A6:word16] = ~0x04;
				ptrArg04->u0 = ~0x04;
				Mem425[ss:sp_221 + 0x00:word16] = Mem422[ds_20:0x179A:word16];
				(ss->*sp_221).tFFFFFFFE.u2 = (byte Eq_4085::*) ds_20;
				(ss->*sp_221).tFFFFFFFC.u2 = (byte Eq_4085::*) 0x1796;
				cx_124 = fn1BF1_0380(ds_20, (ss->*sp_221).tFFFFFFFC.u1, (ss->*sp_221).t0000.u2, out dx_125, out es_132, out ds_20);
			}
			else
			{
				Mem303[ds_20:5957:byte] = 0x00;
				Mem304[ds_20:0x175A:byte] = 0x00;
				dx_125 = Mem304[ds_20:0x1752:word16];
				word16 ax_306 = Mem304[ds_20:0x1750:word16];
				Mem307[ds_20:6046:word16] = dx_125;
				Mem308[ds_20:6044:word16] = ax_306;
				Mem309[ds_20:5996:word16] = dx_125;
				Mem310[ds_20:5994:word16] = ax_306;
				Eq_12 ax_311 = Mem310[ds_20:5625:word16];
				Mem312[ds_20:0x1754:word16] = ax_311;
				Mem313[ds_20:5998:word16] = ax_311;
				Mem314[ds_20:0x1760:word16] = ds_20;
				Mem315[ds_20:0x175E:word16] = 0x17A6;
				if (Mem315[ds_20:0x1789:byte] != 0x00)
				{
					(ss->*sp_221).t0000.u2 = (byte Eq_4085::*) ds_20;
					(ss->*sp_221).tFFFFFFFE.u2 = (byte Eq_4085::*) 0x1744;
					fn1BF1_18B9((ss->*sp_221).tFFFFFFFE.u1);
				}
				else
				{
					(ss->*sp_221).t0000.u2 = (byte Eq_4085::*) ds_20;
					(ss->*sp_221).tFFFFFFFE.u2 = (byte Eq_4085::*) 0x1744;
					fn1BF1_18B4(ds_20, (ss->*sp_221).tFFFFFFFE.u1);
				}
				struct Eq_12297 Eq_11866::* sp_347 = sp_103 - 4;
				(ss->*sp_347).w0002 = 0x13;
				Mem359[ss:sp_347 + 0x00:word16] = Mem355[ds_20:6062:word16];
				Mem362[ss:sp_347 + -2:word16] = Mem359[ds_20:6060:word16];
				(ss->*sp_347).tFFFFFFFC.u2 = (byte Eq_4085::*) ds_20;
				(ss->*sp_347).tFFFFFFFA.u0 = 0x1731;
				cx_124 = fn1BF1_0178((ss->*sp_347).tFFFFFFFA.u1, (ss->*sp_347).tFFFFFFFE.u1, (ss->*sp_347).w0002);
				(ss->*sp_347).tFFFFFFF8.u2 = (byte Eq_4085::*) ds_20;
				(ss->*sp_347).ptrFFFFFFF6 = 0x1744;
				es_132 = fn1BF1_1B59((ss->*sp_347).ptrFFFFFFF6);
				if (Mem375[ds_20:0x1731:byte] == 0x00)
				{
					Mem386[ds_20:0x178C:word16] = 0x1744;
					Mem387[ds_20:6026:word16] = 0x1731;
					Mem393[ds_20:0x17A4:word16] = fn1BF1_1DF1();
					Mem395[ds_20:0x17A0:word16] = Mem393[ds_20:5951:word16];
					Mem396[ds_20:6050:word16] = 10000;
					Mem398[ds_20:0x1789:byte] = 0x03;
					Mem401[ds_20:0x17B9:word16] = 0x03;
					cx_124 = fn1BF1_08A1(out dx_125, out bx_403, out es_132);
					Mem412[ds_20:0x17A6:word16] = 0x00;
l1BF1_0BCF:
					dxOut = dx_125;
					bxOut = bx_403;
					esOut = es_132;
					return cx_124;
				}
				Mem416[ds_20:0x17A6:word16] = CONVERT(Mem375[ds_20:0x1731:byte], uint8, uint16);
			}
		}
	}
	bx_403 = fn1BF1_069F(ds_20);
	goto l1BF1_0BCF;
}

// 1BF1:0E0A: void fn1BF1_0E0A()
// Called from:
//      fn1BF1_0E3E
void fn1BF1_0E0A()
{
	fn1BF1_195F();
	selector seg20D3;
	if ((seg20D3->t1792 | seg20D3->t1794) == 0x00)
	{
		cui16 ax_28 = seg20D3->t1729;
		seg20D3->t1794 = seg20D3->t172B;
		seg20D3->t1792 = ax_28;
		selector seg1BF1;
		seg20D3->t172B = (<unknown>) seg1BF1;
		seg20D3->t1729 = 0x032A;
	}
}

// 1BF1:0E3E: void fn1BF1_0E3E()
// Called from:
//      main
void fn1BF1_0E3E()
{
	selector seg20D3;
	if (seg20D3->t1789 == 0x00)
		seg20D3->t17A6 = ~0x00;
	else
	{
		seg20D3->t1789 = 0x00;
		fn1BF1_0E0A();
		word16 dx_222;
		selector es_223;
		Eq_12 ds_43;
		fn1BF1_0380(0x20D3, &seg20D3->t179C, seg20D3->t15F9, out dx_222, out es_223, out ds_43);
		if ((Mem38[ds_43:0x1796:word16] | Mem38[ds_43:6040:word16]) != 0x00)
		{
			word16 dx_224;
			selector es_225;
			fn1BF1_0380(ds_43, SEQ(ds_43, 0x1796), Mem38[ds_43:0x179A:word16], out dx_224, out es_225, out ds_43);
			ds_43:0x1810[Mem63[ds_43:6030:word16] * 0x1A] = 0x00;
			ds_43:0x180E[Mem63[ds_43:6030:word16] * 0x1A] = 0x00;
		}
		fn1BF1_069F(ds_43);
		cup16 di_128 = 0x00;
		Eq_12 ds_si_219 = SEQ(ds_43, 0x15FD);
		while (true)
		{
			struct Eq_12497 Eq_12::* si_95 = (word16) ds_si_219;
			Eq_12 ds_114;
			ds_114.u1 = SLICE(ds_si_219, selector, 16);
			if (di_128 >= 0x14)
				break;
			if (ds_si_219.u1->b000A != 0x00 && ((ds_si_219.u1)->t0008).u2 != 0x00)
			{
				word16 dx_226;
				selector es_227;
				fn1BF1_0380(ds_114, ds_si_219, ds_si_219.u1->t0008.u2, out dx_226, out es_227, out ds_114);
				(ds_114->*si_95).w0002 = 0x00;
				(ds_114->*si_95).w0000 = 0x00;
				(ds_114->*si_95).w0006 = 0x00;
				(ds_114->*si_95).w0004 = 0x00;
				(ds_114->*si_95).w0008 = 0x00;
			}
			++di_128;
			ds_si_219 = SEQ(ds_114, (char *) &si_95->w0008 + 7);
		}
	}
}

// 1BF1:0F00: void fn1BF1_0F00(Stack wchar_t wArg04, Stack wchar_t wArg06, Stack wchar_t wArg08, Stack wchar_t wArg0A, Stack word16 wArg0C)
// Called from:
//      fn1BF1_08A1
void fn1BF1_0F00(wchar_t wArg04, wchar_t wArg06, wchar_t wArg08, wchar_t wArg0A, word16 wArg0C)
{
	selector seg20D3;
	if (wArg04 >= 0x00 && wArg06 >= 0x00)
	{
		struct Eq_11720 Eq_12::* bx_34 = (struct Eq_11720 Eq_12::*) seg20D3->t178A;
		if ((0x20D3->*bx_34).w0002 >= wArg08 && ((0x20D3->*bx_34).w0004 >= wArg0A && (wArg08 >= wArg04 && wArg0A >= wArg06)))
		{
			seg20D3->t17BF = wArg04;
			seg20D3->t17C1 = wArg06;
			seg20D3->t17C3 = wArg08;
			seg20D3->t17C5 = wArg0A;
			seg20D3->t17C7 = wArg0C;
			fn1BF1_18FD(wArg04, wArg06, wArg08, wArg0A, (byte) wArg0C);
			word16 bx_169;
			fn1BF1_1007(0x00, 0x00, out bx_169);
			return;
		}
	}
	seg20D3->t17A6 = ~0x0A;
}

// 1BF1:1007: Register word16 fn1BF1_1007(Stack word16 wArg04, Stack word16 wArg06, Register out word16 bxOut)
// Called from:
//      fn1BF1_08A1
//      fn1BF1_0F00
word16 fn1BF1_1007(word16 wArg04, word16 wArg06, word16 & bxOut)
{
	word16 bx_27 = fn1BF1_1B95(wArg04, wArg06);
	selector seg20D3;
	seg20D3->t17B5 = wArg04;
	seg20D3->t17B7 = wArg06;
	bxOut = bx_27;
	return wArg06;
}

// 1BF1:115D: void fn1BF1_115D(Stack Eq_12 wArg04, Stack int16 wArg06, Stack cup16 wArg08)
// Called from:
//      main
//      fn1BF1_08A1
void fn1BF1_115D(Eq_12 wArg04, int16 wArg06, cup16 wArg08)
{
	selector seg20D3;
	if (wArg04 <= 0x04 && wArg08 <= 0x03)
	{
		seg20D3->t17C9 = wArg04;
		seg20D3->t17CB = wArg06;
		seg20D3->t17CD = wArg08;
		fn1BF1_1E8C(wArg04, wArg06, (byte) wArg08);
	}
	else
		seg20D3->t17A6 = ~0x0A;
}

// 1BF1:119E: void fn1BF1_119E(Stack Eq_12 wArg04, Stack Eq_12 wArg06, Stack Eq_12 wArg08, Stack Eq_12 wArg0A)
// Called from:
//      fn1128_06D5
//      fn1128_43AC
//      fn1128_4827
//      fn1128_4979
//      fn1128_4ACF
void fn1BF1_119E(Eq_12 wArg04, Eq_12 wArg06, Eq_12 wArg08, Eq_12 wArg0A)
{
	fn1BF1_1BCF(wArg04, wArg06, wArg08, wArg06);
	fn1BF1_1BCF(wArg08, wArg06, wArg08, wArg0A);
	fn1BF1_1BCF(wArg08, wArg0A, wArg04, wArg0A);
	fn1BF1_1BCF(wArg04, wArg0A, wArg04, wArg06);
}

// 1BF1:1211: void fn1BF1_1211(Stack Eq_12 wArg04, Stack Eq_12 wArg06)
// Called from:
//      fn1128_0436
//      fn1128_05BB
//      fn1128_07AB
//      fn1128_43AC
//      fn1128_4827
//      fn1128_4ACF
//      fn1128_5F6B
//      fn1BF1_08A1
void fn1BF1_1211(Eq_12 wArg04, Eq_12 wArg06)
{
	selector seg20D3;
	if (wArg04 > 11)
		seg20D3->t17A6 = ~0x0A;
	else
	{
		seg20D3->t17CF = wArg04;
		seg20D3->t17D1 = wArg06;
		fn1BF1_1EFA((byte) wArg04, (byte) wArg06);
	}
}

// 1BF1:125E: void fn1BF1_125E(Stack (ptr32 Eq_6943) ptrArg04, Stack Eq_12 wArg08)
// Called from:
//      fn1128_43AC
//      fn1BF1_08A1
void fn1BF1_125E(<unknown>* ptrArg04, Eq_12 wArg08)
{
	selector seg20D3;
	if (fn1BF1_1D7D() < wArg08)
		seg20D3->t17A6 = ~0x0A;
	else
	{
		seg20D3->t17CF = 0x0C;
		seg20D3->t17D1 = wArg08;
		memcpy(&seg20D3->t17D3, ptrArg04, 0x08);
		fn1BF1_1A0A(ptrArg04, (byte) wArg08);
	}
}

// 1BF1:138D: void fn1BF1_138D(Stack Eq_11829 wArg04)
// Called from:
//      fn1BF1_08A1
void fn1BF1_138D(Eq_11829 wArg04)
{
	byte bArg04_51 = (byte) wArg04;
	if (wArg04 <= 0x0F)
	{
		selector seg20D3;
		seg20D3->t17B2 = bArg04_51;
		if (wArg04 == 0x00)
			seg20D3->t17DC = 0x00;
		else
			seg20D3->t17DC = 0x20D3->*((word16) wArg04 + 6108);
		fn1BF1_1E0D(seg20D3->t17DC);
	}
}

// 1BF1:13E9: void fn1BF1_13E9(Stack (ptr32 Eq_11743) dwArg04)
// Called from:
//      fn1BF1_08A1
void fn1BF1_13E9(struct Eq_11743 * dwArg04)
{
	struct Eq_12698 * wArg06 = SLICE(dwArg04, word16, 16);
	struct Eq_12700 Eq_12698::* wArg04 = (word16) dwArg04;
	selector seg20D3;
	if (seg20D3->t17B9 != 0x00)
	{
		Eq_12713 ax_37;
		if (dwArg04->b0000 > 0x10)
			ax_37.u0 = 0x10;
		else
			ax_37.u1 = (uint16) dwArg04->b0000;
		Eq_12713 wLoc04_148;
		wLoc04_148.u0 = 0x00;
		while (wLoc04_148 < ax_37)
		{
			if (wArg06->*((word16) (wArg04 + wLoc04_148) + 1) > ~0x00)
				0x20D3->*((word16) wLoc04_148 + 6108) = wArg06->*((word16) (wArg04 + wLoc04_148) + 1);
			wLoc04_148 = (word16) wLoc04_148 + 1;
		}
		if (dwArg04->b0001 != ~0x00)
			seg20D3->t17B2 = 0x00;
		mp16 fp;
		memcpy(fp - 28, &seg20D3->t17DB, 0x11);
		fn1BF1_1E71(fp - 28);
	}
}

// 1BF1:1526: void fn1BF1_1526(Stack wchar_t wArg04, Stack ci16 wArg06, Stack (ptr32 Eq_6881) ptrArg08, Stack byte bArg0C)
// Called from:
//      fn1128_07AB
//      fn1128_5F6B
//      fn1128_60AE
void fn1BF1_1526(wchar_t wArg04, ci16 wArg06, struct Eq_6881 * ptrArg08, byte bArg0C)
{
	selector seg20D3;
	cup16 dx_33 = 0x20D3->*(seg20D3->t178A + 4) - (wArg06 + seg20D3->t17C1);
	cup16 ax_25 = ptrArg08->w0000;
	cup16 si_27 = ptrArg08->w0002;
	cup16 si_34 = dx_33;
	if (dx_33 > si_27)
		si_34 = si_27;
	if (wArg04 + seg20D3->t17BF + ax_25 <= 0x20D3->*(seg20D3->t178A + 2) && (wArg04 + seg20D3->t17BF >= 0x00 && wArg06 + seg20D3->t17C1 >= 0x00))
	{
		ptrArg08->w0002 = si_34;
		word16 wArg0C;
		fn1BF1_20A3(wArg04, wArg06, ptrArg08, (byte) wArg0C);
		ptrArg08->w0002 = si_27;
	}
}

// 1BF1:161A: void fn1BF1_161A(Stack ci16 wArg04, Stack ci16 wArg06)
// Called from:
//      fn1BF1_08A1
void fn1BF1_161A(ci16 wArg04, ci16 wArg06)
{
	selector seg20D3;
	if (wArg04 >= 0x00 && (wArg04 <= 0x02 && (wArg06 >= 0x00 && wArg06 <= 0x02)))
	{
		seg20D3->t17F2 = wArg04;
		seg20D3->t17F4 = wArg06;
		fn1BF1_1A3D((byte) wArg04, (byte) wArg06);
	}
	else
		seg20D3->t17A6 = ~0x0A;
}

// 1BF1:165B: Register word16 fn1BF1_165B(Stack Eq_11287 wArg04, Stack word16 wArg06, Stack word16 wArg08, Register out (ptr16 Eq_11797) esOut)
// Called from:
//      fn1BF1_08A1
word16 fn1BF1_165B(Eq_11287 wArg04, word16 wArg06, word16 wArg08, struct Eq_11797 & esOut)
{
	cu16 wLoc08;
	word16 wLoc06;
	struct Eq_11797 * es_359;
	Eq_12 ds_170;
	ds_170.u0 = 0x20D3;
	Eq_11287 si_21 = wArg04;
	selector seg20D3;
	if (0x20D3->*(seg20D3->t178A + 1) == 0x03)
	{
l1BF1_17FE:
		Mem332[ds_170:0x17EC:word16] = si_21;
		Mem340[ds_170:0x17EE:word16] = wArg06;
		Mem342[ds_170:0x17F0:word16] = wArg08;
		word16 dx_358 = fn1BF1_1F60((byte) si_21, (byte) wArg06, (byte) wArg08, out es_359);
		esOut = es_359;
		return dx_358;
	}
	si_21 = wArg04;
	if (wArg04 == 0x00)
		goto l1BF1_17FE;
	si_21 = wArg04;
	if (wArg04 >= 0x00 && wArg04 <= seg20D3->t15FB)
	{
		if (wArg04 == seg20D3->t17EC)
			goto l1BF1_17FE;
		if (wArg04 == seg20D3->t17BD)
		{
l1BF1_17E2:
			word16 ax_314 = (*((word32) ds_170 + 5618))[wArg04].w0000;
			Mem315[ds_170:0x17AA:word16] = ds_170:0x15F4[wArg04 * 0x0F];
			Mem316[ds_170:6056:word16] = ax_314;
			goto l1BF1_17FE;
		}
		if ((*((byte) ~0x2C + 5637))[seg20D3->t17BD - 0x01].w0000 != 0x00)
		{
			int16 ax_59 = (seg20D3->t17BD - 0x01) *s 0x0F;
			word16 dx_499;
			selector es_500;
			fn1BF1_0380(0x20D3, SEQ(0x20D3, ax_59 + 0x15FD), 0x20D3:0x1605[(Mem18[20D3:17BD:word16] - 0x01) * 0x0F], out dx_499, out es_500, out ds_170);
			(*((word32) ds_170 + 0x000015FF))[seg20D3->t17BD - 0x01].w0000 = 0x00;
			(*((word32) ds_170 + 5629))[seg20D3->t17BD - 0x01].w0000 = 0x00;
			(*((word32) ds_170 + 5635))[seg20D3->t17BD - 0x01].w0000 = 0x00;
			(*((word32) ds_170 + 5633))[seg20D3->t17BD - 0x01].w0000 = 0x00;
			(*((word32) ds_170 + 5637))[seg20D3->t17BD - 0x01].w0000 = 0x00;
		}
		if (((*((word32) ds_170 + 5618))[wArg04].w0000 | ((*((word32) ds_170 + 5620)))[wArg04].w0000) != 0x00)
		{
l1BF1_17DE:
			Mem308[ds_170:6077:word16] = wArg04;
			goto l1BF1_17E2;
		}
		fn1BF1_00AD(SEQ(ds_170, 7144), SEQ(ds_170, wArg04 *s 0x0F + 0x15F8), SEQ(ds_170, 5522));
		<unknown> Eq_12987::* fp;
		word16 cx_501;
		word16 dx_502;
		if (fn1BF1_072D(ds_170, fp - 4, SEQ(ds_170, 5522), SEQ(ds_170, 5544), out cx_501, out dx_502) != 0x00)
		{
			if (Mem141[ds_170:0x17A6:word16] == ~0x02)
				Mem305[ds_170:0x17A6:word16] = ~0x07;
		}
		else
		{
			Eq_12 wLoc04;
			word16 cx_503;
			word16 dx_504;
			if (fn1BF1_034E(ds_170, fp - 8, (word32) wLoc04 + 16, out cx_503, out dx_504, out ds_170) != 0x00)
			{
				fn1BF1_00EB(ds_170);
				Mem302[ds_170:0x17A6:word16] = ~0x08;
			}
			else
			{
				word16 dx_189 = wLoc06 + (wLoc08 + 0x0F >> 0x04);
				if (fn1BF1_013D(ds_170, SEQ(dx_189, 0x00), wLoc04, 0x00) != 0x00)
				{
					word16 dx_505;
					selector es_506;
					fn1BF1_0380(ds_170, fp - 8, (word32) wLoc04 + 16, out dx_505, out es_506, out ds_170);
				}
				else
				{
					fn1BF1_00EB(ds_170);
					if (fn1BF1_04A8(SEQ(dx_189, 0x00)) == wArg04)
					{
						(*((word32) ds_170 + 5616))[wArg04].w0000 = wLoc06;
						(*((word32) ds_170 + 0x000015EE))[wArg04].w0000 = wLoc08;
						(*((word32) ds_170 + 5622))[wArg04].w0000 = (word16) ((word32) wLoc04 + 16);
						goto l1BF1_17DE;
					}
					word16 dx_507;
					selector es_508;
					fn1BF1_0380(ds_170, fp - 8, (word32) wLoc04 + 16, out dx_507, out es_508, out ds_170);
					Mem276[ds_170:0x17A6:word16] = ~0x0C;
				}
			}
		}
	}
	else
		seg20D3->t17A6 = ~0x0D;
	si_21.u0 = 0x00;
	wArg08 = 0x01;
	goto l1BF1_17FE;
}

struct Eq_13101 * g_ptr1859 = &g_t20D3; // 1BF1:1859
// 1BF1:185B: void fn1BF1_185B()
// Called from:
//      fn1BF1_19E7
void fn1BF1_185B()
{
}

// 1BF1:185E: void fn1BF1_185E(Register (ptr16 Eq_13101) ds)
// Called from:
//      fn1BF1_1B59
void fn1BF1_185E(struct Eq_13101 * ds)
{
	if (ds->b1BF7 != ~0x00)
		return;
	if (ds->b1590 != 0xA5)
	{
		byte ah_11;
		byte bh_12;
		ds->b1BF7 = bios_video_get_current_video_mode(out ah_11, out bh_12);
		byte al_18 = (byte) 0040:0010;
		ds->b1BF8 = al_18;
		if (ds->t1BF0 != 0x05 && ds->t1BF0 != 0x07)
			0040:0010 = (byte *) (al_18 & ~0x30 | 0x20);
	}
	else
		ds->b1BF7 = 0x00;
}

// 1BF1:18B4: void fn1BF1_18B4(Register Eq_12 ds, Stack Eq_12 ptrArg04)
// Called from:
//      fn1BF1_0979
void fn1BF1_18B4(Eq_12 ds, Eq_12 ptrArg04)
{
	Mem5[ds:0x1BF7:byte] = ~0x00;
	fn1BF1_18B9(ptrArg04);
}

// 1BF1:18B9: void fn1BF1_18B9(Stack Eq_12 ptrArg04)
// Called from:
//      fn1BF1_0979
//      fn1BF1_18B4
void fn1BF1_18B9(Eq_12 ptrArg04)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	ds_12->t1BF0 != 0x05;
	struct Eq_12865 * es_31 = SLICE(ptrArg04, selector, 16);
	if (ptrArg04.u1->b0016 == 0x00)
		es_31 = ds_12->ptr172F;
	ds_12->ptr1729();
	struct Eq_13173 * bx_55;
	ds_12->ptr17AC = bx_55;
	ds_12->ptr17AE = es_31;
}

// 1BF1:18FD: void fn1BF1_18FD(Stack wchar_t wArg04, Stack wchar_t wArg06, Stack wchar_t wArg08, Stack wchar_t wArg0A, Stack byte bArg0C)
// Called from:
//      fn1BF1_0F00
void fn1BF1_18FD(wchar_t wArg04, wchar_t wArg06, wchar_t wArg08, wchar_t wArg0A, byte bArg0C)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	ds_12->ptr1729();
}

// 1BF1:195F: void fn1BF1_195F()
// Called from:
//      fn1BF1_0E0A
void fn1BF1_195F()
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	if (ds_12->b1BF7 != ~0x00)
	{
		ds_12->ptr1729();
		if (ds_12->b1590 != 0xA5)
		{
			0040:0010 = (byte *) ds_12->b1BF8;
			bios_video_set_mode(ds_12->b1BF7);
		}
	}
	ds_12->b1BF7 = ~0x00;
}

// 1BF1:19E7: void fn1BF1_19E7(Stack uint8 bArg04)
// Called from:
//      fn1BF1_08A1
void fn1BF1_19E7(uint8 bArg04)
{
	uint16 ax_25 = (uint16) bArg04;
	Mem11[1BF1:1859:selector]->ptr1729();
	fn1BF1_185B();
}

// 1BF1:1A0A: void fn1BF1_1A0A(Stack (ptr32 Eq_6943) ptrArg04, Stack byte bArg08)
// Called from:
//      fn1BF1_125E
void fn1BF1_1A0A(<unknown>* ptrArg04, byte bArg08)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	ds_12->b17B1 = bArg08;
	ds_12->ptr1729();
	ds_12->b17B4 = 0x0C;
	ds_12->ptr1729();
}

// 1BF1:1A3D: void fn1BF1_1A3D(Stack byte bArg04, Stack byte bArg06)
// Called from:
//      fn1BF1_161A
void fn1BF1_1A3D(byte bArg04, byte bArg06)
{
	Mem11[1BF1:1859:selector]->ptr1729();
}

// 1BF1:1AAB: Register word16 fn1BF1_1AAB(Stack Eq_11890 ptrArg04, Stack Eq_6087 ptrArg08, Stack Eq_10765 ptrArg0C, Register out word16 dxOut)
// Called from:
//      fn1BF1_0979
word16 fn1BF1_1AAB(Eq_11890 ptrArg04, Eq_6087 ptrArg08, Eq_10765 ptrArg0C, word16 & dxOut)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	ds_12->b1BEE = ~0x00;
	ds_12->b1BEF = 0x00;
	ds_12->b1BF1 = 0x0A;
	Eq_13132 al_25;
	al_25.u0 = ptrArg08.u1->u0;
	ds_12->t1BF0 = al_25;
	word16 cx;
	word16 dx;
	uint8 al_57;
	if (al_25 == 0x00)
	{
		struct Eq_13288 * ss;
		<unknown> Eq_13288::* fp;
		cx = fn1BF1_1B37(&(ss->*((char *) fp + 2)), ds_12, out dx);
		al_57 = ds_12->b1BEE;
	}
	else
	{
		ds_12->b1BEF = *ptrArg0C.u2;
		Eq_13132 bl_40;
		bl_40.u0 = ptrArg08.u1->u0;
		if (bl_40 < 0x00)
			goto l1BF1_1B17;
		cu8 al_47 = 0x0A - bl_40;
		if (al_47 < 0x00)
			al_57 = -al_47;
		else
		{
			Eq_13310 bx_54;
			bx_54.u0 = (uint16) bl_40;
			ds_12->b1BF1 = (byte) (0x1BF1->*((word16) bx_54 + 8418));
			al_57 = (uint8) (0x1BF1->*((word16) bx_54 + 8390));
			ds_12->b1BEE = al_57;
		}
	}
	*ptrArg04.u1 = (uint16) al_57;
l1BF1_1B17:
	dxOut = dx;
	return cx;
}

// 1BF1:1B37: Register word16 fn1BF1_1B37(Sequence (ptr32 Eq_13286) ss_bp, Register (ptr16 Eq_13101) ds, Register out word16 dxOut)
// Called from:
//      fn1BF1_1AAB
word16 fn1BF1_1B37(struct Eq_13286 * ss_bp, struct Eq_13101 * ds, word16 & dxOut)
{
	word16 dx_12;
	word16 cx_11 = fn1BF1_20F0(ds, out dx_12);
	Eq_13132 al_22 = ds->t1BF0;
	uint16 * es_di_21 = ss_bp->ptr0006;
	uint16 ax_27 = (uint16) al_22;
	if (al_22 == ~0x00)
		ax_27 = SEQ(al_22, al_22);
	*es_di_21 = ax_27;
	*ss_bp->ptr000A = (uint16) ds->b1BEF;
	dxOut = dx_12;
	return cx_11;
}

// 1BF1:1B59: Register (ptr16 Eq_13362) fn1BF1_1B59(Stack segptr32 ptrArg04)
// Called from:
//      fn1BF1_0979
struct Eq_13362 * fn1BF1_1B59(segptr32 ptrArg04)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	fn1BF1_185E(ds_12);
	ds_12->ptr1BF3 = ptrArg04;
	ds_12->ptr1729();
	return SLICE(ptrArg04, selector, 16);
}

// 1BF1:1B95: Register word16 fn1BF1_1B95(Stack word16 wArg04, Stack word16 wArg06)
// Called from:
//      fn1BF1_1007
word16 fn1BF1_1B95(word16 wArg04, word16 wArg06)
{
	Mem11[1BF1:1859:selector]->ptr1729();
	word16 bx_24;
	return bx_24;
}

// 1BF1:1BCF: void fn1BF1_1BCF(Stack Eq_12 wArg04, Stack Eq_12 wArg06, Stack Eq_12 wArg08, Stack Eq_12 wArg0A)
// Called from:
//      fn1BF1_119E
void fn1BF1_1BCF(Eq_12 wArg04, Eq_12 wArg06, Eq_12 wArg08, Eq_12 wArg0A)
{
	Mem11[1BF1:1859:selector]->ptr1729();
}

// 1BF1:1C32: void fn1BF1_1C32(Stack Eq_12 wArg04, Stack Eq_12 wArg06, Stack Eq_12 wArg08, Stack Eq_12 wArg0A)
// Called from:
//      fn1128_0436
//      fn1128_05BB
//      fn1128_07AB
//      fn1128_43AC
//      fn1128_4827
//      fn1128_4979
//      fn1128_4ACF
//      fn1128_5F6B
void fn1BF1_1C32(Eq_12 wArg04, Eq_12 wArg06, Eq_12 wArg08, Eq_12 wArg0A)
{
	Mem11[1BF1:1859:selector]->ptr1729();
}

// 1BF1:1D5C: void fn1BF1_1D5C(Stack Eq_12 bArg04)
// Called from:
//      fn1128_0436
//      fn1128_05BB
//      fn1128_06D5
//      fn1128_07AB
//      fn1128_43AC
//      fn1128_4827
//      fn1128_4ACF
//      fn1128_5F6B
//      fn1BF1_08A1
void fn1BF1_1D5C(Eq_12 bArg04)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	ds_12->t17B0 = bArg04;
	ds_12->ptr1729();
}

// 1BF1:1D7D: Register word16 fn1BF1_1D7D()
// Called from:
//      fn1BF1_08A1
//      fn1BF1_125E
word16 fn1BF1_1D7D()
{
	Mem11[1BF1:1859:selector]->ptr1729();
	word16 cx_26;
	return cx_26;
}

// 1BF1:1D98: Register word16 fn1BF1_1D98()
// Called from:
//      fn1BF1_08A1
word16 fn1BF1_1D98()
{
	Mem11[1BF1:1859:selector]->ptr1729();
	word16 bx_26;
	return bx_26;
}

// 1BF1:1DB3: Sequence ptr32 fn1BF1_1DB3()
// Called from:
//      fn1BF1_08A1
ptr32 fn1BF1_1DB3()
{
	Mem11[1BF1:1859:selector]->ptr1729();
	<unknown> Eq_13414::* bx_24;
	return bx_24;
}

// 1BF1:1DF1: Register word16 fn1BF1_1DF1()
// Called from:
//      fn1BF1_0979
word16 fn1BF1_1DF1()
{
	Mem11[1BF1:1859:selector]->ptr1729();
	word16 cx_23;
	return cx_23 - 0x01;
}

// 1BF1:1E0D: void fn1BF1_1E0D(Stack byte bArg04)
// Called from:
//      fn1BF1_138D
void fn1BF1_1E0D(byte bArg04)
{
	Mem11[1BF1:1859:selector]->ptr1729();
}

// 1BF1:1E71: void fn1BF1_1E71(Stack segptr32 ptrArg04)
// Called from:
//      fn1BF1_13E9
void fn1BF1_1E71(segptr32 ptrArg04)
{
	Mem11[1BF1:1859:selector]->ptr1729();
}

// 1BF1:1E8C: void fn1BF1_1E8C(Stack Eq_12 wArg04, Stack int16 wArg06, Stack byte bArg08)
// Called from:
//      fn1BF1_115D
void fn1BF1_1E8C(Eq_12 wArg04, int16 wArg06, byte bArg08)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	ds_12->b17B3 = (byte) wArg04;
	ds_12->b1BF2 = bArg08;
	ds_12->ptr1729();
}

// 1BF1:1EFA: void fn1BF1_1EFA(Stack byte bArg04, Stack byte bArg06)
// Called from:
//      fn1BF1_1211
void fn1BF1_1EFA(byte bArg04, byte bArg06)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	ds_12->b17B1 = bArg06;
	ds_12->ptr1729();
	ds_12->b17B4 = bArg04;
	ds_12->ptr1729();
}

// 1BF1:1F2A: void fn1BF1_1F2A(Stack Eq_12 wArg04, Stack Eq_12 wArg06, Stack Eq_12 ptrArg08)
// Called from:
//      fn1128_0436
//      fn1128_05BB
//      fn1128_06D5
//      fn1128_07AB
//      fn1128_43AC
//      fn1128_4827
//      fn1128_4979
//      fn1128_4ACF
//      fn1128_5F6B
void fn1BF1_1F2A(Eq_12 wArg04, Eq_12 wArg06, Eq_12 ptrArg08)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	ds_12->ptr1729();
	word16 bx_29 = (word16) ptrArg08;
	ds_12->ptr1729();
}

// 1BF1:1F60: Register word16 fn1BF1_1F60(Stack byte bArg04, Stack byte bArg06, Stack byte bArg08, Register out (ptr16 Eq_12865) esOut)
// Called from:
//      fn1BF1_165B
word16 fn1BF1_1F60(byte bArg04, byte bArg06, byte bArg08, struct Eq_12865 & esOut)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	struct Eq_12865 * es_20 = ds_12->ptr17AE;
	if (bArg04 != 0x00)
	{
		struct Eq_13173 * es_di_40 = ds_12->ptr17AC;
		es_20 = SLICE(es_di_40, selector, 16);
		es_di_40->b0001 == 0x03;
	}
	ds_12->ptr1729();
	esOut = es_20;
	word16 dx_63;
	return dx_63;
}

// 1BF1:2046: void fn1BF1_2046(Stack int16 wArg04, Stack int16 wArg06, Stack byte bArg08)
// Called from:
//      fn1128_4A4A
//      fn1128_4F92
void fn1BF1_2046(int16 wArg04, int16 wArg06, byte bArg08)
{
	Mem11[1BF1:1859:selector]->ptr1729();
}

// 1BF1:2066: void fn1BF1_2066(Stack cup16 wArg04, Stack cup16 wArg06, Stack cup16 wArg08, Stack cup16 wArg0A, Stack (ptr32 Eq_6817) ptrArg0C)
// Called from:
//      fn1128_07AB
//      fn1128_5F6B
//      fn1128_60AE
void fn1BF1_2066(cup16 wArg04, cup16 wArg06, cup16 wArg08, cup16 wArg0A, struct Eq_6817 * ptrArg0C)
{
	selector seg1BF1;
	struct Eq_13101 * ds_12 = seg1BF1->ptr1859;
	cup16 cx_20 = wArg04;
	cup16 dx_21 = wArg06;
	cup16 si_22 = wArg08;
	cup16 di_23 = wArg0A;
	if (wArg04 >= wArg08)
	{
		cx_20 = wArg08;
		si_22 = wArg04;
	}
	if (wArg06 >= wArg0A)
	{
		dx_21 = wArg0A;
		di_23 = wArg06;
	}
	ptrArg0C->w0000 = si_22 - cx_20;
	ptrArg0C->w0002 = di_23 - dx_21;
	ds_12->ptr1729();
}

// 1BF1:20A3: void fn1BF1_20A3(Stack wchar_t wArg04, Stack ci16 wArg06, Stack (ptr32 Eq_6881) ptrArg08, Stack byte bArg0C)
// Called from:
//      fn1BF1_1526
void fn1BF1_20A3(wchar_t wArg04, ci16 wArg06, struct Eq_6881 * ptrArg08, byte bArg0C)
{
	Mem11[1BF1:1859:selector]->ptr1729();
}

// 1BF1:20F0: Register word16 fn1BF1_20F0(Register (ptr16 Eq_13101) ds, Register out word16 dxOut)
// Called from:
//      fn1BF1_1B37
word16 fn1BF1_20F0(struct Eq_13101 * ds, word16 & dxOut)
{
	word16 dx_12;
	ds->b1BEE = ~0x00;
	ds->t1BF0.u0 = ~0x00;
	ds->b1BEF = 0x00;
	word16 cx_10 = fn1BF1_2126(ds, out dx_12);
	Eq_13132 bl_18 = ds->t1BF0;
	if (bl_18 != ~0x00)
	{
		Eq_13546 bx_25;
		bx_25.u0 = (uint16) bl_18;
		ds->b1BEE = (uint8) (0x1BF1->*((word16) bx_25 + 8390));
		ds->b1BEF = (uint8) (0x1BF1->*((word16) bx_25 + 8404));
		ds->b1BF1 = (byte) (0x1BF1->*((word16) bx_25 + 8418));
	}
	dxOut = dx_12;
	return cx_10;
}

// 1BF1:2126: Register word16 fn1BF1_2126(Register (ptr16 Eq_13101) ds, Register out word16 dxOut)
// Called from:
//      fn1BF1_20F0
word16 fn1BF1_2126(struct Eq_13101 * ds, word16 & dxOut)
{
	byte ah_5;
	byte bh_6;
	word16 dx;
	word16 bx_84;
	word16 cx_161;
	if (bios_video_get_current_video_mode(out ah_5, out bh_6) != 0x07)
	{
		if (!fn1BF1_221B())
		{
			ds->t1BF0.u0 = 0x06;
			dxOut = dx;
			word16 cx;
			return cx;
		}
		word16 bx_160;
		bx_84 = bx_160;
		word16 cx_167;
		cx_161 = cx_167;
		if (fn1BF1_218D(out cx_167, out bx_160))
		{
			word16 cx_61;
			word16 dx_62;
			if (fn1BF1_2250(out cx_61, out dx_62) == 0x00)
			{
				ds->t1BF0.u0 = 0x01;
				if (!fn1BF1_21FA())
					ds->t1BF0.u0 = 0x02;
				dxOut = dx_62;
				return cx_61;
			}
			else
			{
				ds->t1BF0.u0 = 0x0A;
				dxOut = dx_62;
				return cx_61;
			}
		}
	}
	else
	{
		word16 bx_159;
		bx_84 = bx_159;
		word16 cx_166;
		cx_161 = cx_166;
		if (!fn1BF1_218D(out cx_166, out bx_159))
		{
			word16 cx_22;
			word16 dx_23;
			if (fn1BF1_221E(out cx_22, out dx_23) == 0x00)
			{
				word16 ax_38 = ~B800:0000;
				B800:0000 = (word16 *) ~B800:0000;
				if (ax_38 == B800:0000)
					ds->t1BF0.u0 = 0x01;
				dxOut = dx_23;
				return cx_22;
			}
			else
			{
				ds->t1BF0.u0 = 0x07;
				dxOut = dx_23;
				return cx_22;
			}
		}
	}
	fn1BF1_21AB((byte) cx_161, bx_84, ds);
	dxOut = dx;
	return cx_161;
}

// 1BF1:218D: FlagGroup bool fn1BF1_218D(Register out Eq_4797 cxOut, Register out Eq_4797 bxOut)
// Called from:
//      fn1BF1_2126
bool fn1BF1_218D(union Eq_4797 & cxOut, union Eq_4797 & bxOut)
{
	ci8 cl_9;
	byte ch_8;
	ci8 bl_7;
	ci8 bh_10 = bios_video_get_EGA_info(out bl_7, out ch_8, out cl_9);
	if (cl_9 >= 0x0C || (bh_10 > 0x01 || bl_7 > 0x03))
	{
		cxOut.u0 = <invalid>;
		bxOut.u0 = <invalid>;
		return false;
	}
	else
	{
		cxOut.u0 = <invalid>;
		bxOut.u0 = <invalid>;
		return true;
	}
}

// 1BF1:21AB: void fn1BF1_21AB(Register cu8 cl, Register word16 bx, Register (ptr16 Eq_13101) ds)
// Called from:
//      fn1BF1_2126
void fn1BF1_21AB(cu8 cl, word16 bx, struct Eq_13101 * ds)
{
	byte bh = SLICE(bx, byte, 8);
	byte bl = (byte) bx;
	ds->t1BF0.u0 = 0x04;
	if (bh == 0x01)
		ds->t1BF0.u0 = 0x05;
	else if (!fn1BF1_21EB(cl) && bl != 0x00)
	{
		ds->t1BF0.u0 = 0x03;
		if (fn1BF1_21FA() || C000:0039 == 0x345A && C000:003B == 14644)
			ds->t1BF0.u0 = 0x09;
	}
}

// 1BF1:21EB: FlagGroup bool fn1BF1_21EB(Register cu8 cl)
// Called from:
//      fn1BF1_21AB
bool fn1BF1_21EB(cu8 cl)
{
	ui32 C_11 = cond(cl - 0x02) & 0x02;
	if (cl >= 0x02)
	{
		C_11 = !(cond(cl - 0x06) & 0x02);
		if (cl >= 0x06)
			C_11 = cond(cl - 0x08) & 0x02;
	}
	return C_11 != 0x00;
}

// 1BF1:21FA: FlagGroup bool fn1BF1_21FA()
// Called from:
//      fn1BF1_2126
//      fn1BF1_21AB
bool fn1BF1_21FA()
{
	byte bh_5;
	cu8 bl_6 = bios_video_get_DAC_color_page_state(out bh_5);
	if (true || bl_6 != 0x07 && (bl_6 != 0x08 && (bl_6 < 11 || bl_6 > 0x0C)))
		return false;
	return true;
}

// 1BF1:221B: FlagGroup bool fn1BF1_221B()
// Called from:
//      fn1BF1_2126
bool fn1BF1_221B()
{
	return false;
}

// 1BF1:221E: Register byte fn1BF1_221E(Register out word16 cxOut, Register out Eq_4797 dxOut)
// Called from:
//      fn1BF1_2126
byte fn1BF1_221E(word16 & cxOut, union Eq_4797 & dxOut)
{
	cu8 bl_19 = 0x00;
	byte al_6 = __in<byte>(0x03BA);
	word16 cx_12;
	for (cx_12 = 0x8000; cx_12 != 0x00; --cx_12)
	{
		if ((__in<byte>(0x03BA) & 0x80) != (al_6 & 0x80))
		{
			++bl_19;
			if (bl_19 >= 0x0A)
			{
				word16 cx_23;
				for (cx_23 = 0x8000; cx_23 != 0x00; --cx_23)
				{
					if ((__in<byte>(0x03BA) & 0x30) != 0x10)
					{
						cxOut = cx_23;
						dxOut.u0 = <invalid>;
						return 0x01;
					}
				}
				cxOut = cx_23;
				dxOut.u0 = <invalid>;
				return 0x02;
			}
		}
	}
	cxOut = cx_12;
	dxOut.u0 = <invalid>;
	return 0x00;
}

// 1BF1:2250: Register word16 fn1BF1_2250(Register out Eq_4797 cxOut, Register out word16 dxOut)
// Called from:
//      fn1BF1_2126
word16 fn1BF1_2250(union Eq_4797 & cxOut, word16 & dxOut)
{
	bios_video_unknown_1030();
	word16 dx_30 = 0x00;
	if (false)
	{
		byte al_20 = (byte) 0000:0002;
		if (al_20 == 0x00 || al_20 == 0x02)
		{
			dx_30 = 0x0188;
			if ((__in<byte>(0x0188) & 0x04) != 0x00)
			{
				cxOut.u0 = <invalid>;
				dxOut = 0x0188;
				return 0x01;
			}
		}
	}
	cxOut.u0 = <invalid>;
	dxOut = dx_30;
	return 0x00;
}

